{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.common.v1@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Temporal.Temporal.Api.Common.V1.Message where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Proto.Encode
import Proto.Decode
import Proto.JSON
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Google.Protobuf.Duration (Duration(..))
import Proto.Google.Protobuf.Empty (Empty(..))
import Proto.Temporal.Temporal.Api.Enums.V1.Common (EncodingType(..))
import Proto.Temporal.Temporal.Api.Enums.V1.EventType (EventType(..))
import Proto.Temporal.Temporal.Api.Enums.V1.Reset (ResetReapplyExcludeType(..), ResetReapplyType(..))


data DataBlob = DataBlob
  { dataBlobEncodingtype :: !EncodingType
  , dataBlobData :: !ByteString
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultDataBlob :: DataBlob
defaultDataBlob = DataBlob
  { dataBlobEncodingtype = (toEnum 0)
  , dataBlobData = ""
  }

instance MessageEncode DataBlob where
  buildMessage msg =
    (if fromEnum msg.dataBlobEncodingtype == 0 then mempty else encodeFieldVarint 1 (fromIntegral (fromEnum msg.dataBlobEncodingtype)))
    <> (if BS.null msg.dataBlobData then mempty else encodeFieldBytes 2 msg.dataBlobData)

instance MessageSize DataBlob where
  messageSize msg =
    (if fromEnum msg.dataBlobEncodingtype == 0 then 0 else fieldVarintSize 1 (fromIntegral (fromEnum msg.dataBlobEncodingtype)))
    + (if BS.null msg.dataBlobData then 0 else fieldBytesSize 2 msg.dataBlobData)

instance MessageDecode DataBlob where
  messageDecoder = loop (toEnum 0) ""
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (DataBlob {dataBlobEncodingtype = acc_0, dataBlobData = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldEnum
              loop v acc_1
            2 -> do
              v <- decodeFieldBytes
              loop acc_0 v
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON DataBlob where
  protoToJSON msg = jsonObject
      [ "encodingType" .= msg.dataBlobEncodingtype
      , "data" .= msg.dataBlobData
      ]

instance ProtoFromJSON DataBlob where
  protoFromJSON (JsonObject obj) = do
    fld_dataBlobEncodingtype <- obj .:? "encodingType"
    fld_dataBlobData <- obj .:? "data"
    pure defaultDataBlob
      { dataBlobEncodingtype = maybe (dataBlobEncodingtype defaultDataBlob) id fld_dataBlobEncodingtype
      , dataBlobData = maybe (dataBlobData defaultDataBlob) id fld_dataBlobData
      }
  protoFromJSON _ = Right defaultDataBlob

data Payloads = Payloads
  { payloadsPayloads :: !(V.Vector Payload)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultPayloads :: Payloads
defaultPayloads = Payloads
  { payloadsPayloads = V.empty
  }

instance MessageEncode Payloads where
  buildMessage msg =
    V.foldl' (\acc v -> acc <> encodeFieldMessage 1 v) mempty msg.payloadsPayloads

instance MessageSize Payloads where
  messageSize msg =
    (V.foldl' (\acc v -> acc + fieldMessageSize 1 (messageSize v)) 0 msg.payloadsPayloads)

instance MessageDecode Payloads where
  messageDecoder = loop V.empty
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Payloads {payloadsPayloads = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (acc_0 <> V.singleton v)
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON Payloads where
  protoToJSON msg = jsonObject
      [ "payloads" .= msg.payloadsPayloads

      ]

instance ProtoFromJSON Payloads where
  protoFromJSON (JsonObject obj) = do
    fld_payloadsPayloads <- obj .:? "payloads"
    pure defaultPayloads
      { payloadsPayloads = maybe (payloadsPayloads defaultPayloads) id fld_payloadsPayloads
      }
  protoFromJSON _ = Right defaultPayloads

data Payload = Payload
  { payloadMetadata :: !(Map.Map Text ByteString)
  , payloadData :: !ByteString
  , payloadExternalpayloads :: !(V.Vector Payload'ExternalPayloadDetails)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

data Payload'ExternalPayloadDetails = Payload'ExternalPayloadDetails
  { payloadExternalPayloadDetailsSizebytes :: {-# UNPACK #-} !Int64
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultPayload'ExternalPayloadDetails :: Payload'ExternalPayloadDetails
defaultPayload'ExternalPayloadDetails = Payload'ExternalPayloadDetails
  { payloadExternalPayloadDetailsSizebytes = 0
  }

instance MessageEncode Payload'ExternalPayloadDetails where
  buildMessage msg =
    (if msg.payloadExternalPayloadDetailsSizebytes == 0 then mempty else encodeFieldVarint 1 (fromIntegral msg.payloadExternalPayloadDetailsSizebytes))

instance MessageSize Payload'ExternalPayloadDetails where
  messageSize msg =
    (if msg.payloadExternalPayloadDetailsSizebytes == 0 then 0 else fieldVarintSize 1 (fromIntegral msg.payloadExternalPayloadDetailsSizebytes))

instance MessageDecode Payload'ExternalPayloadDetails where
  messageDecoder = loop 0
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Payload'ExternalPayloadDetails {payloadExternalPayloadDetailsSizebytes = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON Payload'ExternalPayloadDetails where
  protoToJSON msg = jsonObject
      [ "sizeBytes" .= msg.payloadExternalPayloadDetailsSizebytes

      ]

instance ProtoFromJSON Payload'ExternalPayloadDetails where
  protoFromJSON (JsonObject obj) = do
    fld_payloadExternalPayloadDetailsSizebytes <- obj .:? "sizeBytes"
    pure defaultPayload'ExternalPayloadDetails
      { payloadExternalPayloadDetailsSizebytes = maybe (payloadExternalPayloadDetailsSizebytes defaultPayload'ExternalPayloadDetails) id fld_payloadExternalPayloadDetailsSizebytes
      }
  protoFromJSON _ = Right defaultPayload'ExternalPayloadDetails

defaultPayload :: Payload
defaultPayload = Payload
  { payloadMetadata = Map.empty
  , payloadData = ""
  , payloadExternalpayloads = V.empty
  }

instance MessageEncode Payload where
  buildMessage msg =
    Map.foldlWithKey' (\acc k v -> acc <> encodeMapField 1 (encodeFieldString 1 k) (encodeFieldBytes 2 v)) mempty msg.payloadMetadata
    <> (if BS.null msg.payloadData then mempty else encodeFieldBytes 2 msg.payloadData)
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 3 v) mempty msg.payloadExternalpayloads

instance MessageSize Payload where
  messageSize msg =
    (Map.foldlWithKey' (\acc k v -> let entrySz = fieldTextSize 1 k + fieldBytesSize 2 v in acc + tagSize 1 + varintSize (fromIntegral entrySz) + entrySz) 0 msg.payloadMetadata)
    + (if BS.null msg.payloadData then 0 else fieldBytesSize 2 msg.payloadData)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 3 (messageSize v)) 0 msg.payloadExternalpayloads)

instance MessageDecode Payload where
  messageDecoder = loop Map.empty "" V.empty
    where
      loop acc_0 acc_1 acc_2 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Payload {payloadMetadata = acc_0, payloadData = acc_1, payloadExternalpayloads = acc_2})
          Just (Tag fn wt) -> case fn of
            1 -> do
              bs' <- getLengthDelimited
              let decodeEntry = runDecoder (decodeMapEntry decodeFieldString decodeFieldBytes "" "") bs'
              case decodeEntry of
                Left _ -> loop acc_0 acc_1 acc_2
                Right (mk', mv') -> loop (Map.union acc_0 (Map.singleton mk' mv')) acc_1 acc_2
            2 -> do
              v <- decodeFieldBytes
              loop acc_0 v acc_2
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (acc_2 <> V.singleton v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2

instance ProtoToJSON Payload where
  protoToJSON msg = jsonObject
      [ "metadata" .= msg.payloadMetadata
      , "data" .= msg.payloadData
      , "externalPayloads" .= msg.payloadExternalpayloads
      ]

instance ProtoFromJSON Payload where
  protoFromJSON (JsonObject obj) = do
    fld_payloadMetadata <- obj .:? "metadata"
    fld_payloadData <- obj .:? "data"
    fld_payloadExternalpayloads <- obj .:? "externalPayloads"
    pure defaultPayload
      { payloadMetadata = maybe (payloadMetadata defaultPayload) id fld_payloadMetadata
      , payloadData = maybe (payloadData defaultPayload) id fld_payloadData
      , payloadExternalpayloads = maybe (payloadExternalpayloads defaultPayload) id fld_payloadExternalpayloads
      }
  protoFromJSON _ = Right defaultPayload

data SearchAttributes = SearchAttributes
  { searchAttributesIndexedfields :: !(Map.Map Text Payload)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultSearchAttributes :: SearchAttributes
defaultSearchAttributes = SearchAttributes
  { searchAttributesIndexedfields = Map.empty
  }

instance MessageEncode SearchAttributes where
  buildMessage msg =
    Map.foldlWithKey' (\acc k v -> acc <> encodeMapField 1 (encodeFieldString 1 k) (encodeFieldMessage 2 v)) mempty msg.searchAttributesIndexedfields

instance MessageSize SearchAttributes where
  messageSize msg =
    (Map.foldlWithKey' (\acc k v -> let entrySz = fieldTextSize 1 k + fieldMessageSize 2 (messageSize v) in acc + tagSize 1 + varintSize (fromIntegral entrySz) + entrySz) 0 msg.searchAttributesIndexedfields)

instance MessageDecode SearchAttributes where
  messageDecoder = loop Map.empty
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (SearchAttributes {searchAttributesIndexedfields = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              bs' <- getLengthDelimited
              let decodeEntry = runDecoder (decodeMapEntry decodeFieldString decodeFieldMessage "" undefined) bs'
              case decodeEntry of
                Left _ -> loop acc_0
                Right (mk', mv') -> loop (Map.union acc_0 (Map.singleton mk' mv'))
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON SearchAttributes where
  protoToJSON msg = jsonObject
      [ "indexedFields" .= msg.searchAttributesIndexedfields

      ]

instance ProtoFromJSON SearchAttributes where
  protoFromJSON (JsonObject obj) = do
    fld_searchAttributesIndexedfields <- obj .:? "indexedFields"
    pure defaultSearchAttributes
      { searchAttributesIndexedfields = maybe (searchAttributesIndexedfields defaultSearchAttributes) id fld_searchAttributesIndexedfields
      }
  protoFromJSON _ = Right defaultSearchAttributes

data Memo = Memo
  { memoFields :: !(Map.Map Text Payload)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultMemo :: Memo
defaultMemo = Memo
  { memoFields = Map.empty
  }

instance MessageEncode Memo where
  buildMessage msg =
    Map.foldlWithKey' (\acc k v -> acc <> encodeMapField 1 (encodeFieldString 1 k) (encodeFieldMessage 2 v)) mempty msg.memoFields

instance MessageSize Memo where
  messageSize msg =
    (Map.foldlWithKey' (\acc k v -> let entrySz = fieldTextSize 1 k + fieldMessageSize 2 (messageSize v) in acc + tagSize 1 + varintSize (fromIntegral entrySz) + entrySz) 0 msg.memoFields)

instance MessageDecode Memo where
  messageDecoder = loop Map.empty
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Memo {memoFields = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              bs' <- getLengthDelimited
              let decodeEntry = runDecoder (decodeMapEntry decodeFieldString decodeFieldMessage "" undefined) bs'
              case decodeEntry of
                Left _ -> loop acc_0
                Right (mk', mv') -> loop (Map.union acc_0 (Map.singleton mk' mv'))
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON Memo where
  protoToJSON msg = jsonObject
      [ "fields" .= msg.memoFields

      ]

instance ProtoFromJSON Memo where
  protoFromJSON (JsonObject obj) = do
    fld_memoFields <- obj .:? "fields"
    pure defaultMemo
      { memoFields = maybe (memoFields defaultMemo) id fld_memoFields
      }
  protoFromJSON _ = Right defaultMemo

data Header = Header
  { headerFields :: !(Map.Map Text Payload)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultHeader :: Header
defaultHeader = Header
  { headerFields = Map.empty
  }

instance MessageEncode Header where
  buildMessage msg =
    Map.foldlWithKey' (\acc k v -> acc <> encodeMapField 1 (encodeFieldString 1 k) (encodeFieldMessage 2 v)) mempty msg.headerFields

instance MessageSize Header where
  messageSize msg =
    (Map.foldlWithKey' (\acc k v -> let entrySz = fieldTextSize 1 k + fieldMessageSize 2 (messageSize v) in acc + tagSize 1 + varintSize (fromIntegral entrySz) + entrySz) 0 msg.headerFields)

instance MessageDecode Header where
  messageDecoder = loop Map.empty
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Header {headerFields = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              bs' <- getLengthDelimited
              let decodeEntry = runDecoder (decodeMapEntry decodeFieldString decodeFieldMessage "" undefined) bs'
              case decodeEntry of
                Left _ -> loop acc_0
                Right (mk', mv') -> loop (Map.union acc_0 (Map.singleton mk' mv'))
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON Header where
  protoToJSON msg = jsonObject
      [ "fields" .= msg.headerFields

      ]

instance ProtoFromJSON Header where
  protoFromJSON (JsonObject obj) = do
    fld_headerFields <- obj .:? "fields"
    pure defaultHeader
      { headerFields = maybe (headerFields defaultHeader) id fld_headerFields
      }
  protoFromJSON _ = Right defaultHeader

data WorkflowExecution = WorkflowExecution
  { workflowExecutionWorkflowid :: !Text
  , workflowExecutionRunid :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkflowExecution :: WorkflowExecution
defaultWorkflowExecution = WorkflowExecution
  { workflowExecutionWorkflowid = ""
  , workflowExecutionRunid = ""
  }

instance MessageEncode WorkflowExecution where
  buildMessage msg =
    (if msg.workflowExecutionWorkflowid == T.empty then mempty else encodeFieldString 1 msg.workflowExecutionWorkflowid)
    <> (if msg.workflowExecutionRunid == T.empty then mempty else encodeFieldString 2 msg.workflowExecutionRunid)

instance MessageSize WorkflowExecution where
  messageSize msg =
    (if msg.workflowExecutionWorkflowid == T.empty then 0 else fieldTextSize 1 msg.workflowExecutionWorkflowid)
    + (if msg.workflowExecutionRunid == T.empty then 0 else fieldTextSize 2 msg.workflowExecutionRunid)

instance MessageDecode WorkflowExecution where
  messageDecoder = loop "" ""
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (WorkflowExecution {workflowExecutionWorkflowid = acc_0, workflowExecutionRunid = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1
            2 -> do
              v <- decodeFieldString
              loop acc_0 v
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON WorkflowExecution where
  protoToJSON msg = jsonObject
      [ "workflowId" .= msg.workflowExecutionWorkflowid
      , "runId" .= msg.workflowExecutionRunid
      ]

instance ProtoFromJSON WorkflowExecution where
  protoFromJSON (JsonObject obj) = do
    fld_workflowExecutionWorkflowid <- obj .:? "workflowId"
    fld_workflowExecutionRunid <- obj .:? "runId"
    pure defaultWorkflowExecution
      { workflowExecutionWorkflowid = maybe (workflowExecutionWorkflowid defaultWorkflowExecution) id fld_workflowExecutionWorkflowid
      , workflowExecutionRunid = maybe (workflowExecutionRunid defaultWorkflowExecution) id fld_workflowExecutionRunid
      }
  protoFromJSON _ = Right defaultWorkflowExecution

data WorkflowType = WorkflowType
  { workflowTypeName :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkflowType :: WorkflowType
defaultWorkflowType = WorkflowType
  { workflowTypeName = ""
  }

instance MessageEncode WorkflowType where
  buildMessage msg =
    (if msg.workflowTypeName == T.empty then mempty else encodeFieldString 1 msg.workflowTypeName)

instance MessageSize WorkflowType where
  messageSize msg =
    (if msg.workflowTypeName == T.empty then 0 else fieldTextSize 1 msg.workflowTypeName)

instance MessageDecode WorkflowType where
  messageDecoder = loop ""
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (WorkflowType {workflowTypeName = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON WorkflowType where
  protoToJSON msg = jsonObject
      [ "name" .= msg.workflowTypeName

      ]

instance ProtoFromJSON WorkflowType where
  protoFromJSON (JsonObject obj) = do
    fld_workflowTypeName <- obj .:? "name"
    pure defaultWorkflowType
      { workflowTypeName = maybe (workflowTypeName defaultWorkflowType) id fld_workflowTypeName
      }
  protoFromJSON _ = Right defaultWorkflowType

data ActivityType = ActivityType
  { activityTypeName :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultActivityType :: ActivityType
defaultActivityType = ActivityType
  { activityTypeName = ""
  }

instance MessageEncode ActivityType where
  buildMessage msg =
    (if msg.activityTypeName == T.empty then mempty else encodeFieldString 1 msg.activityTypeName)

instance MessageSize ActivityType where
  messageSize msg =
    (if msg.activityTypeName == T.empty then 0 else fieldTextSize 1 msg.activityTypeName)

instance MessageDecode ActivityType where
  messageDecoder = loop ""
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (ActivityType {activityTypeName = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON ActivityType where
  protoToJSON msg = jsonObject
      [ "name" .= msg.activityTypeName

      ]

instance ProtoFromJSON ActivityType where
  protoFromJSON (JsonObject obj) = do
    fld_activityTypeName <- obj .:? "name"
    pure defaultActivityType
      { activityTypeName = maybe (activityTypeName defaultActivityType) id fld_activityTypeName
      }
  protoFromJSON _ = Right defaultActivityType

data RetryPolicy = RetryPolicy
  { retryPolicyInitialinterval :: !(Maybe Duration)
  , retryPolicyBackoffcoefficient :: {-# UNPACK #-} !Double
  , retryPolicyMaximuminterval :: !(Maybe Duration)
  , retryPolicyMaximumattempts :: {-# UNPACK #-} !Int32
  , retryPolicyNonretryableerrortypes :: !(V.Vector Text)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultRetryPolicy :: RetryPolicy
defaultRetryPolicy = RetryPolicy
  { retryPolicyInitialinterval = Nothing
  , retryPolicyBackoffcoefficient = 0
  , retryPolicyMaximuminterval = Nothing
  , retryPolicyMaximumattempts = 0
  , retryPolicyNonretryableerrortypes = V.empty
  }

instance MessageEncode RetryPolicy where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.retryPolicyInitialinterval)
    <> (if msg.retryPolicyBackoffcoefficient == 0 then mempty else encodeFieldDouble 2 msg.retryPolicyBackoffcoefficient)
    <> (maybe mempty (\v -> encodeFieldMessage 3 v) msg.retryPolicyMaximuminterval)
    <> (if msg.retryPolicyMaximumattempts == 0 then mempty else encodeFieldVarint 4 (fromIntegral msg.retryPolicyMaximumattempts))
    <> V.foldl' (\acc v -> acc <> encodeFieldString 5 v) mempty msg.retryPolicyNonretryableerrortypes

instance MessageSize RetryPolicy where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.retryPolicyInitialinterval)
    + (if msg.retryPolicyBackoffcoefficient == 0 then 0 else fieldDoubleSize 2)
    + (maybe 0 (\v -> fieldMessageSize 3 (messageSize v)) msg.retryPolicyMaximuminterval)
    + (if msg.retryPolicyMaximumattempts == 0 then 0 else fieldVarintSize 4 (fromIntegral msg.retryPolicyMaximumattempts))
    + (V.foldl' (\acc v -> acc + fieldTextSize 5 v) 0 msg.retryPolicyNonretryableerrortypes)

instance MessageDecode RetryPolicy where
  messageDecoder = loop Nothing 0 Nothing 0 V.empty
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (RetryPolicy {retryPolicyInitialinterval = acc_0, retryPolicyBackoffcoefficient = acc_1, retryPolicyMaximuminterval = acc_2, retryPolicyMaximumattempts = acc_3, retryPolicyNonretryableerrortypes = acc_4})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v) acc_1 acc_2 acc_3 acc_4
            2 -> do
              v <- decodeFieldDouble
              loop acc_0 v acc_2 acc_3 acc_4
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (Just v) acc_3 acc_4
            4 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop acc_0 acc_1 acc_2 v acc_4
            5 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 acc_3 (acc_4 <> V.singleton v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4

instance ProtoToJSON RetryPolicy where
  protoToJSON msg = jsonObject
      [ "initialInterval" .= msg.retryPolicyInitialinterval
      , "backoffCoefficient" .= msg.retryPolicyBackoffcoefficient
      , "maximumInterval" .= msg.retryPolicyMaximuminterval
      , "maximumAttempts" .= msg.retryPolicyMaximumattempts
      , "nonRetryableErrorTypes" .= msg.retryPolicyNonretryableerrortypes
      ]

instance ProtoFromJSON RetryPolicy where
  protoFromJSON (JsonObject obj) = do
    fld_retryPolicyInitialinterval <- obj .:? "initialInterval"
    fld_retryPolicyBackoffcoefficient <- obj .:? "backoffCoefficient"
    fld_retryPolicyMaximuminterval <- obj .:? "maximumInterval"
    fld_retryPolicyMaximumattempts <- obj .:? "maximumAttempts"
    fld_retryPolicyNonretryableerrortypes <- obj .:? "nonRetryableErrorTypes"
    pure defaultRetryPolicy
      { retryPolicyInitialinterval = maybe (retryPolicyInitialinterval defaultRetryPolicy) id fld_retryPolicyInitialinterval
      , retryPolicyBackoffcoefficient = maybe (retryPolicyBackoffcoefficient defaultRetryPolicy) id fld_retryPolicyBackoffcoefficient
      , retryPolicyMaximuminterval = maybe (retryPolicyMaximuminterval defaultRetryPolicy) id fld_retryPolicyMaximuminterval
      , retryPolicyMaximumattempts = maybe (retryPolicyMaximumattempts defaultRetryPolicy) id fld_retryPolicyMaximumattempts
      , retryPolicyNonretryableerrortypes = maybe (retryPolicyNonretryableerrortypes defaultRetryPolicy) id fld_retryPolicyNonretryableerrortypes
      }
  protoFromJSON _ = Right defaultRetryPolicy

data MeteringMetadata = MeteringMetadata
  { meteringMetadataNonfirstlocalactivityexecutionattempts :: {-# UNPACK #-} !Word32
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultMeteringMetadata :: MeteringMetadata
defaultMeteringMetadata = MeteringMetadata
  { meteringMetadataNonfirstlocalactivityexecutionattempts = 0
  }

instance MessageEncode MeteringMetadata where
  buildMessage msg =
    (if msg.meteringMetadataNonfirstlocalactivityexecutionattempts == 0 then mempty else encodeFieldVarint 13 (fromIntegral msg.meteringMetadataNonfirstlocalactivityexecutionattempts))

instance MessageSize MeteringMetadata where
  messageSize msg =
    (if msg.meteringMetadataNonfirstlocalactivityexecutionattempts == 0 then 0 else fieldVarintSize 13 (fromIntegral msg.meteringMetadataNonfirstlocalactivityexecutionattempts))

instance MessageDecode MeteringMetadata where
  messageDecoder = loop 0
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (MeteringMetadata {meteringMetadataNonfirstlocalactivityexecutionattempts = acc_0})
          Just (Tag fn wt) -> case fn of
            13 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON MeteringMetadata where
  protoToJSON msg = jsonObject
      [ "nonfirstLocalActivityExecutionAttempts" .= msg.meteringMetadataNonfirstlocalactivityexecutionattempts

      ]

instance ProtoFromJSON MeteringMetadata where
  protoFromJSON (JsonObject obj) = do
    fld_meteringMetadataNonfirstlocalactivityexecutionattempts <- obj .:? "nonfirstLocalActivityExecutionAttempts"
    pure defaultMeteringMetadata
      { meteringMetadataNonfirstlocalactivityexecutionattempts = maybe (meteringMetadataNonfirstlocalactivityexecutionattempts defaultMeteringMetadata) id fld_meteringMetadataNonfirstlocalactivityexecutionattempts
      }
  protoFromJSON _ = Right defaultMeteringMetadata

data WorkerVersionStamp = WorkerVersionStamp
  { workerVersionStampBuildid :: !Text
  , workerVersionStampUseversioning :: {-# UNPACK #-} !Bool
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkerVersionStamp :: WorkerVersionStamp
defaultWorkerVersionStamp = WorkerVersionStamp
  { workerVersionStampBuildid = ""
  , workerVersionStampUseversioning = False
  }

instance MessageEncode WorkerVersionStamp where
  buildMessage msg =
    (if msg.workerVersionStampBuildid == T.empty then mempty else encodeFieldString 1 msg.workerVersionStampBuildid)
    <> (if msg.workerVersionStampUseversioning == False then mempty else encodeFieldBool 3 msg.workerVersionStampUseversioning)

instance MessageSize WorkerVersionStamp where
  messageSize msg =
    (if msg.workerVersionStampBuildid == T.empty then 0 else fieldTextSize 1 msg.workerVersionStampBuildid)
    + (if msg.workerVersionStampUseversioning == False then 0 else fieldBoolSize 3)

instance MessageDecode WorkerVersionStamp where
  messageDecoder = loop "" False
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (WorkerVersionStamp {workerVersionStampBuildid = acc_0, workerVersionStampUseversioning = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1
            3 -> do
              v <- decodeFieldBool
              loop acc_0 v
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON WorkerVersionStamp where
  protoToJSON msg = jsonObject
      [ "buildId" .= msg.workerVersionStampBuildid
      , "useVersioning" .= msg.workerVersionStampUseversioning
      ]

instance ProtoFromJSON WorkerVersionStamp where
  protoFromJSON (JsonObject obj) = do
    fld_workerVersionStampBuildid <- obj .:? "buildId"
    fld_workerVersionStampUseversioning <- obj .:? "useVersioning"
    pure defaultWorkerVersionStamp
      { workerVersionStampBuildid = maybe (workerVersionStampBuildid defaultWorkerVersionStamp) id fld_workerVersionStampBuildid
      , workerVersionStampUseversioning = maybe (workerVersionStampUseversioning defaultWorkerVersionStamp) id fld_workerVersionStampUseversioning
      }
  protoFromJSON _ = Right defaultWorkerVersionStamp

data WorkerVersionCapabilities = WorkerVersionCapabilities
  { workerVersionCapabilitiesBuildid :: !Text
  , workerVersionCapabilitiesUseversioning :: {-# UNPACK #-} !Bool
  , workerVersionCapabilitiesDeploymentseriesname :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkerVersionCapabilities :: WorkerVersionCapabilities
defaultWorkerVersionCapabilities = WorkerVersionCapabilities
  { workerVersionCapabilitiesBuildid = ""
  , workerVersionCapabilitiesUseversioning = False
  , workerVersionCapabilitiesDeploymentseriesname = ""
  }

instance MessageEncode WorkerVersionCapabilities where
  buildMessage msg =
    (if msg.workerVersionCapabilitiesBuildid == T.empty then mempty else encodeFieldString 1 msg.workerVersionCapabilitiesBuildid)
    <> (if msg.workerVersionCapabilitiesUseversioning == False then mempty else encodeFieldBool 2 msg.workerVersionCapabilitiesUseversioning)
    <> (if msg.workerVersionCapabilitiesDeploymentseriesname == T.empty then mempty else encodeFieldString 4 msg.workerVersionCapabilitiesDeploymentseriesname)

instance MessageSize WorkerVersionCapabilities where
  messageSize msg =
    (if msg.workerVersionCapabilitiesBuildid == T.empty then 0 else fieldTextSize 1 msg.workerVersionCapabilitiesBuildid)
    + (if msg.workerVersionCapabilitiesUseversioning == False then 0 else fieldBoolSize 2)
    + (if msg.workerVersionCapabilitiesDeploymentseriesname == T.empty then 0 else fieldTextSize 4 msg.workerVersionCapabilitiesDeploymentseriesname)

instance MessageDecode WorkerVersionCapabilities where
  messageDecoder = loop "" False ""
    where
      loop acc_0 acc_1 acc_2 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (WorkerVersionCapabilities {workerVersionCapabilitiesBuildid = acc_0, workerVersionCapabilitiesUseversioning = acc_1, workerVersionCapabilitiesDeploymentseriesname = acc_2})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2
            2 -> do
              v <- decodeFieldBool
              loop acc_0 v acc_2
            4 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2

instance ProtoToJSON WorkerVersionCapabilities where
  protoToJSON msg = jsonObject
      [ "buildId" .= msg.workerVersionCapabilitiesBuildid
      , "useVersioning" .= msg.workerVersionCapabilitiesUseversioning
      , "deploymentSeriesName" .= msg.workerVersionCapabilitiesDeploymentseriesname
      ]

instance ProtoFromJSON WorkerVersionCapabilities where
  protoFromJSON (JsonObject obj) = do
    fld_workerVersionCapabilitiesBuildid <- obj .:? "buildId"
    fld_workerVersionCapabilitiesUseversioning <- obj .:? "useVersioning"
    fld_workerVersionCapabilitiesDeploymentseriesname <- obj .:? "deploymentSeriesName"
    pure defaultWorkerVersionCapabilities
      { workerVersionCapabilitiesBuildid = maybe (workerVersionCapabilitiesBuildid defaultWorkerVersionCapabilities) id fld_workerVersionCapabilitiesBuildid
      , workerVersionCapabilitiesUseversioning = maybe (workerVersionCapabilitiesUseversioning defaultWorkerVersionCapabilities) id fld_workerVersionCapabilitiesUseversioning
      , workerVersionCapabilitiesDeploymentseriesname = maybe (workerVersionCapabilitiesDeploymentseriesname defaultWorkerVersionCapabilities) id fld_workerVersionCapabilitiesDeploymentseriesname
      }
  protoFromJSON _ = Right defaultWorkerVersionCapabilities

data ResetOptions = ResetOptions
  { resetOptionsTarget :: !(Maybe ResetOptions'Target)
  , resetOptionsResetreapplytype :: !ResetReapplyType
  , resetOptionsCurrentrunonly :: {-# UNPACK #-} !Bool
  , resetOptionsResetreapplyexcludetypes :: !(V.Vector ResetReapplyExcludeType)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
data ResetOptions'Target
  = ResetOptions'Target'FirstWorkflowTask !Empty
  | ResetOptions'Target'LastWorkflowTask !Empty
  | ResetOptions'Target'WorkflowTaskId {-# UNPACK #-} !Int64
  | ResetOptions'Target'BuildId !Text
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
instance ProtoToJSON ResetOptions'Target where
  protoToJSON _ = JsonNull
instance ProtoFromJSON ResetOptions'Target where
  protoFromJSON _ = Left "Cannot parse oneof from JSON"

defaultResetOptions :: ResetOptions
defaultResetOptions = ResetOptions
  { resetOptionsTarget = Nothing
  , resetOptionsResetreapplytype = (toEnum 0)
  , resetOptionsCurrentrunonly = False
  , resetOptionsResetreapplyexcludetypes = V.empty
  }

instance MessageEncode ResetOptions where
  buildMessage msg =
    (case msg.resetOptionsTarget of
      Nothing -> mempty
      Just (ResetOptions'Target'FirstWorkflowTask v) -> encodeFieldMessage 1 v
      Just (ResetOptions'Target'LastWorkflowTask v) -> encodeFieldMessage 2 v
      Just (ResetOptions'Target'WorkflowTaskId v) -> encodeFieldVarint 3 (fromIntegral v)
      Just (ResetOptions'Target'BuildId v) -> encodeFieldString 4 v)
    <> (if fromEnum msg.resetOptionsResetreapplytype == 0 then mempty else encodeFieldVarint 10 (fromIntegral (fromEnum msg.resetOptionsResetreapplytype)))
    <> (if msg.resetOptionsCurrentrunonly == False then mempty else encodeFieldBool 11 msg.resetOptionsCurrentrunonly)
    <> V.foldl' (\acc v -> acc <> encodeFieldVarint 12 (fromIntegral (fromEnum v))) mempty msg.resetOptionsResetreapplyexcludetypes

instance MessageSize ResetOptions where
  messageSize msg =
    (case msg.resetOptionsTarget of { Nothing -> 0; Just (ResetOptions'Target'FirstWorkflowTask v) -> fieldMessageSize 1 (messageSize v)
    ; Just (ResetOptions'Target'LastWorkflowTask v) -> fieldMessageSize 2 (messageSize v)
    ; Just (ResetOptions'Target'WorkflowTaskId v) -> fieldVarintSize 3 (fromIntegral v)
    ; Just (ResetOptions'Target'BuildId v) -> fieldTextSize 4 v })
    + (if fromEnum msg.resetOptionsResetreapplytype == 0 then 0 else fieldVarintSize 10 (fromIntegral (fromEnum msg.resetOptionsResetreapplytype)))
    + (if msg.resetOptionsCurrentrunonly == False then 0 else fieldBoolSize 11)
    + (V.foldl' (\acc v -> acc + fieldVarintSize 12 (fromIntegral (fromEnum v))) 0 msg.resetOptionsResetreapplyexcludetypes)

instance MessageDecode ResetOptions where
  messageDecoder = loop Nothing (toEnum 0) False V.empty
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (ResetOptions {resetOptionsTarget = acc_0, resetOptionsResetreapplytype = acc_1, resetOptionsCurrentrunonly = acc_2, resetOptionsResetreapplyexcludetypes = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just (ResetOptions'Target'FirstWorkflowTask v)) acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldMessage
              loop (Just (ResetOptions'Target'LastWorkflowTask v)) acc_1 acc_2 acc_3
            3 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop (Just (ResetOptions'Target'WorkflowTaskId v)) acc_1 acc_2 acc_3
            4 -> do
              v <- decodeFieldString
              loop (Just (ResetOptions'Target'BuildId v)) acc_1 acc_2 acc_3
            10 -> do
              v <- decodeFieldEnum
              loop acc_0 v acc_2 acc_3
            11 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 v acc_3
            12 -> do
              v <- decodeFieldEnum
              loop acc_0 acc_1 acc_2 (acc_3 <> V.singleton v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON ResetOptions where
  protoToJSON msg = jsonObject
      [ "target" .= msg.resetOptionsTarget
      , "resetReapplyType" .= msg.resetOptionsResetreapplytype
      , "currentRunOnly" .= msg.resetOptionsCurrentrunonly
      , "resetReapplyExcludeTypes" .= msg.resetOptionsResetreapplyexcludetypes
      ]

instance ProtoFromJSON ResetOptions where
  protoFromJSON (JsonObject obj) = do
    fld_resetOptionsTarget <- obj .:? "target"
    fld_resetOptionsResetreapplytype <- obj .:? "resetReapplyType"
    fld_resetOptionsCurrentrunonly <- obj .:? "currentRunOnly"
    fld_resetOptionsResetreapplyexcludetypes <- obj .:? "resetReapplyExcludeTypes"
    pure defaultResetOptions
      { resetOptionsTarget = maybe (resetOptionsTarget defaultResetOptions) id fld_resetOptionsTarget
      , resetOptionsResetreapplytype = maybe (resetOptionsResetreapplytype defaultResetOptions) id fld_resetOptionsResetreapplytype
      , resetOptionsCurrentrunonly = maybe (resetOptionsCurrentrunonly defaultResetOptions) id fld_resetOptionsCurrentrunonly
      , resetOptionsResetreapplyexcludetypes = maybe (resetOptionsResetreapplyexcludetypes defaultResetOptions) id fld_resetOptionsResetreapplyexcludetypes
      }
  protoFromJSON _ = Right defaultResetOptions

data Callback = Callback
  { callbackVariant :: !(Maybe Callback'Variant)
  , callbackLinks :: !(V.Vector Link)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

data Callback'Nexus = Callback'Nexus
  { callbackNexusUrl :: !Text
  , callbackNexusHeader :: !(Map.Map Text Text)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultCallback'Nexus :: Callback'Nexus
defaultCallback'Nexus = Callback'Nexus
  { callbackNexusUrl = ""
  , callbackNexusHeader = Map.empty
  }

instance MessageEncode Callback'Nexus where
  buildMessage msg =
    (if msg.callbackNexusUrl == T.empty then mempty else encodeFieldString 1 msg.callbackNexusUrl)
    <> Map.foldlWithKey' (\acc k v -> acc <> encodeMapField 2 (encodeFieldString 1 k) (encodeFieldString 2 v)) mempty msg.callbackNexusHeader

instance MessageSize Callback'Nexus where
  messageSize msg =
    (if msg.callbackNexusUrl == T.empty then 0 else fieldTextSize 1 msg.callbackNexusUrl)
    + (Map.foldlWithKey' (\acc k v -> let entrySz = fieldTextSize 1 k + fieldTextSize 2 v in acc + tagSize 2 + varintSize (fromIntegral entrySz) + entrySz) 0 msg.callbackNexusHeader)

instance MessageDecode Callback'Nexus where
  messageDecoder = loop "" Map.empty
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Callback'Nexus {callbackNexusUrl = acc_0, callbackNexusHeader = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1
            2 -> do
              bs' <- getLengthDelimited
              let decodeEntry = runDecoder (decodeMapEntry decodeFieldString decodeFieldString "" "") bs'
              case decodeEntry of
                Left _ -> loop acc_0 acc_1
                Right (mk', mv') -> loop acc_0 (Map.union acc_1 (Map.singleton mk' mv'))
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON Callback'Nexus where
  protoToJSON msg = jsonObject
      [ "url" .= msg.callbackNexusUrl
      , "header" .= msg.callbackNexusHeader
      ]

instance ProtoFromJSON Callback'Nexus where
  protoFromJSON (JsonObject obj) = do
    fld_callbackNexusUrl <- obj .:? "url"
    fld_callbackNexusHeader <- obj .:? "header"
    pure defaultCallback'Nexus
      { callbackNexusUrl = maybe (callbackNexusUrl defaultCallback'Nexus) id fld_callbackNexusUrl
      , callbackNexusHeader = maybe (callbackNexusHeader defaultCallback'Nexus) id fld_callbackNexusHeader
      }
  protoFromJSON _ = Right defaultCallback'Nexus

data Callback'Internal = Callback'Internal
  { callbackInternalData :: !ByteString
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultCallback'Internal :: Callback'Internal
defaultCallback'Internal = Callback'Internal
  { callbackInternalData = ""
  }

instance MessageEncode Callback'Internal where
  buildMessage msg =
    (if BS.null msg.callbackInternalData then mempty else encodeFieldBytes 1 msg.callbackInternalData)

instance MessageSize Callback'Internal where
  messageSize msg =
    (if BS.null msg.callbackInternalData then 0 else fieldBytesSize 1 msg.callbackInternalData)

instance MessageDecode Callback'Internal where
  messageDecoder = loop ""
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Callback'Internal {callbackInternalData = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldBytes
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON Callback'Internal where
  protoToJSON msg = jsonObject
      [ "data" .= msg.callbackInternalData

      ]

instance ProtoFromJSON Callback'Internal where
  protoFromJSON (JsonObject obj) = do
    fld_callbackInternalData <- obj .:? "data"
    pure defaultCallback'Internal
      { callbackInternalData = maybe (callbackInternalData defaultCallback'Internal) id fld_callbackInternalData
      }
  protoFromJSON _ = Right defaultCallback'Internal
data Callback'Variant
  = Callback'Variant'Nexus !Callback'Nexus
  | Callback'Variant'Internal !Callback'Internal
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
instance ProtoToJSON Callback'Variant where
  protoToJSON _ = JsonNull
instance ProtoFromJSON Callback'Variant where
  protoFromJSON _ = Left "Cannot parse oneof from JSON"

defaultCallback :: Callback
defaultCallback = Callback
  { callbackVariant = Nothing
  , callbackLinks = V.empty
  }

instance MessageEncode Callback where
  buildMessage msg =
    (case msg.callbackVariant of
      Nothing -> mempty
      Just (Callback'Variant'Nexus v) -> encodeFieldMessage 2 v
      Just (Callback'Variant'Internal v) -> encodeFieldMessage 3 v)
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 100 v) mempty msg.callbackLinks

instance MessageSize Callback where
  messageSize msg =
    (case msg.callbackVariant of { Nothing -> 0; Just (Callback'Variant'Nexus v) -> fieldMessageSize 2 (messageSize v)
    ; Just (Callback'Variant'Internal v) -> fieldMessageSize 3 (messageSize v) })
    + (V.foldl' (\acc v -> acc + fieldMessageSize 100 (messageSize v)) 0 msg.callbackLinks)

instance MessageDecode Callback where
  messageDecoder = loop Nothing V.empty
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Callback {callbackVariant = acc_0, callbackLinks = acc_1})
          Just (Tag fn wt) -> case fn of
            2 -> do
              v <- decodeFieldMessage
              loop (Just (Callback'Variant'Nexus v)) acc_1
            3 -> do
              v <- decodeFieldMessage
              loop (Just (Callback'Variant'Internal v)) acc_1
            100 -> do
              v <- decodeFieldMessage
              loop acc_0 (acc_1 <> V.singleton v)
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON Callback where
  protoToJSON msg = jsonObject
      [ "variant" .= msg.callbackVariant
      , "links" .= msg.callbackLinks
      ]

instance ProtoFromJSON Callback where
  protoFromJSON (JsonObject obj) = do
    fld_callbackVariant <- obj .:? "variant"
    fld_callbackLinks <- obj .:? "links"
    pure defaultCallback
      { callbackVariant = maybe (callbackVariant defaultCallback) id fld_callbackVariant
      , callbackLinks = maybe (callbackLinks defaultCallback) id fld_callbackLinks
      }
  protoFromJSON _ = Right defaultCallback

data Link = Link
  { linkVariant :: !(Maybe Link'Variant)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

data Link'WorkflowEvent = Link'WorkflowEvent
  { linkWorkflowEventNamespace :: !Text
  , linkWorkflowEventWorkflowid :: !Text
  , linkWorkflowEventRunid :: !Text
  , linkWorkflowEventReference :: !(Maybe Link'WorkflowEvent'Reference)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

data Link'WorkflowEvent'EventReference = Link'WorkflowEvent'EventReference
  { linkWorkflowEventEventReferenceEventid :: {-# UNPACK #-} !Int64
  , linkWorkflowEventEventReferenceEventtype :: !EventType
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultLink'WorkflowEvent'EventReference :: Link'WorkflowEvent'EventReference
defaultLink'WorkflowEvent'EventReference = Link'WorkflowEvent'EventReference
  { linkWorkflowEventEventReferenceEventid = 0
  , linkWorkflowEventEventReferenceEventtype = (toEnum 0)
  }

instance MessageEncode Link'WorkflowEvent'EventReference where
  buildMessage msg =
    (if msg.linkWorkflowEventEventReferenceEventid == 0 then mempty else encodeFieldVarint 1 (fromIntegral msg.linkWorkflowEventEventReferenceEventid))
    <> (if fromEnum msg.linkWorkflowEventEventReferenceEventtype == 0 then mempty else encodeFieldVarint 2 (fromIntegral (fromEnum msg.linkWorkflowEventEventReferenceEventtype)))

instance MessageSize Link'WorkflowEvent'EventReference where
  messageSize msg =
    (if msg.linkWorkflowEventEventReferenceEventid == 0 then 0 else fieldVarintSize 1 (fromIntegral msg.linkWorkflowEventEventReferenceEventid))
    + (if fromEnum msg.linkWorkflowEventEventReferenceEventtype == 0 then 0 else fieldVarintSize 2 (fromIntegral (fromEnum msg.linkWorkflowEventEventReferenceEventtype)))

instance MessageDecode Link'WorkflowEvent'EventReference where
  messageDecoder = loop 0 (toEnum 0)
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Link'WorkflowEvent'EventReference {linkWorkflowEventEventReferenceEventid = acc_0, linkWorkflowEventEventReferenceEventtype = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop v acc_1
            2 -> do
              v <- decodeFieldEnum
              loop acc_0 v
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON Link'WorkflowEvent'EventReference where
  protoToJSON msg = jsonObject
      [ "eventId" .= msg.linkWorkflowEventEventReferenceEventid
      , "eventType" .= msg.linkWorkflowEventEventReferenceEventtype
      ]

instance ProtoFromJSON Link'WorkflowEvent'EventReference where
  protoFromJSON (JsonObject obj) = do
    fld_linkWorkflowEventEventReferenceEventid <- obj .:? "eventId"
    fld_linkWorkflowEventEventReferenceEventtype <- obj .:? "eventType"
    pure defaultLink'WorkflowEvent'EventReference
      { linkWorkflowEventEventReferenceEventid = maybe (linkWorkflowEventEventReferenceEventid defaultLink'WorkflowEvent'EventReference) id fld_linkWorkflowEventEventReferenceEventid
      , linkWorkflowEventEventReferenceEventtype = maybe (linkWorkflowEventEventReferenceEventtype defaultLink'WorkflowEvent'EventReference) id fld_linkWorkflowEventEventReferenceEventtype
      }
  protoFromJSON _ = Right defaultLink'WorkflowEvent'EventReference

data Link'WorkflowEvent'RequestIdReference = Link'WorkflowEvent'RequestIdReference
  { linkWorkflowEventRequestIdReferenceRequestid :: !Text
  , linkWorkflowEventRequestIdReferenceEventtype :: !EventType
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultLink'WorkflowEvent'RequestIdReference :: Link'WorkflowEvent'RequestIdReference
defaultLink'WorkflowEvent'RequestIdReference = Link'WorkflowEvent'RequestIdReference
  { linkWorkflowEventRequestIdReferenceRequestid = ""
  , linkWorkflowEventRequestIdReferenceEventtype = (toEnum 0)
  }

instance MessageEncode Link'WorkflowEvent'RequestIdReference where
  buildMessage msg =
    (if msg.linkWorkflowEventRequestIdReferenceRequestid == T.empty then mempty else encodeFieldString 1 msg.linkWorkflowEventRequestIdReferenceRequestid)
    <> (if fromEnum msg.linkWorkflowEventRequestIdReferenceEventtype == 0 then mempty else encodeFieldVarint 2 (fromIntegral (fromEnum msg.linkWorkflowEventRequestIdReferenceEventtype)))

instance MessageSize Link'WorkflowEvent'RequestIdReference where
  messageSize msg =
    (if msg.linkWorkflowEventRequestIdReferenceRequestid == T.empty then 0 else fieldTextSize 1 msg.linkWorkflowEventRequestIdReferenceRequestid)
    + (if fromEnum msg.linkWorkflowEventRequestIdReferenceEventtype == 0 then 0 else fieldVarintSize 2 (fromIntegral (fromEnum msg.linkWorkflowEventRequestIdReferenceEventtype)))

instance MessageDecode Link'WorkflowEvent'RequestIdReference where
  messageDecoder = loop "" (toEnum 0)
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Link'WorkflowEvent'RequestIdReference {linkWorkflowEventRequestIdReferenceRequestid = acc_0, linkWorkflowEventRequestIdReferenceEventtype = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1
            2 -> do
              v <- decodeFieldEnum
              loop acc_0 v
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON Link'WorkflowEvent'RequestIdReference where
  protoToJSON msg = jsonObject
      [ "requestId" .= msg.linkWorkflowEventRequestIdReferenceRequestid
      , "eventType" .= msg.linkWorkflowEventRequestIdReferenceEventtype
      ]

instance ProtoFromJSON Link'WorkflowEvent'RequestIdReference where
  protoFromJSON (JsonObject obj) = do
    fld_linkWorkflowEventRequestIdReferenceRequestid <- obj .:? "requestId"
    fld_linkWorkflowEventRequestIdReferenceEventtype <- obj .:? "eventType"
    pure defaultLink'WorkflowEvent'RequestIdReference
      { linkWorkflowEventRequestIdReferenceRequestid = maybe (linkWorkflowEventRequestIdReferenceRequestid defaultLink'WorkflowEvent'RequestIdReference) id fld_linkWorkflowEventRequestIdReferenceRequestid
      , linkWorkflowEventRequestIdReferenceEventtype = maybe (linkWorkflowEventRequestIdReferenceEventtype defaultLink'WorkflowEvent'RequestIdReference) id fld_linkWorkflowEventRequestIdReferenceEventtype
      }
  protoFromJSON _ = Right defaultLink'WorkflowEvent'RequestIdReference
data Link'WorkflowEvent'Reference
  = Link'WorkflowEvent'Reference'EventRef !Link'WorkflowEvent'EventReference
  | Link'WorkflowEvent'Reference'RequestIdRef !Link'WorkflowEvent'RequestIdReference
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
instance ProtoToJSON Link'WorkflowEvent'Reference where
  protoToJSON _ = JsonNull
instance ProtoFromJSON Link'WorkflowEvent'Reference where
  protoFromJSON _ = Left "Cannot parse oneof from JSON"

defaultLink'WorkflowEvent :: Link'WorkflowEvent
defaultLink'WorkflowEvent = Link'WorkflowEvent
  { linkWorkflowEventNamespace = ""
  , linkWorkflowEventWorkflowid = ""
  , linkWorkflowEventRunid = ""
  , linkWorkflowEventReference = Nothing
  }

instance MessageEncode Link'WorkflowEvent where
  buildMessage msg =
    (if msg.linkWorkflowEventNamespace == T.empty then mempty else encodeFieldString 1 msg.linkWorkflowEventNamespace)
    <> (if msg.linkWorkflowEventWorkflowid == T.empty then mempty else encodeFieldString 2 msg.linkWorkflowEventWorkflowid)
    <> (if msg.linkWorkflowEventRunid == T.empty then mempty else encodeFieldString 3 msg.linkWorkflowEventRunid)
    <> (case msg.linkWorkflowEventReference of
      Nothing -> mempty
      Just (Link'WorkflowEvent'Reference'EventRef v) -> encodeFieldMessage 100 v
      Just (Link'WorkflowEvent'Reference'RequestIdRef v) -> encodeFieldMessage 101 v)

instance MessageSize Link'WorkflowEvent where
  messageSize msg =
    (if msg.linkWorkflowEventNamespace == T.empty then 0 else fieldTextSize 1 msg.linkWorkflowEventNamespace)
    + (if msg.linkWorkflowEventWorkflowid == T.empty then 0 else fieldTextSize 2 msg.linkWorkflowEventWorkflowid)
    + (if msg.linkWorkflowEventRunid == T.empty then 0 else fieldTextSize 3 msg.linkWorkflowEventRunid)
    + (case msg.linkWorkflowEventReference of { Nothing -> 0; Just (Link'WorkflowEvent'Reference'EventRef v) -> fieldMessageSize 100 (messageSize v)
    ; Just (Link'WorkflowEvent'Reference'RequestIdRef v) -> fieldMessageSize 101 (messageSize v) })

instance MessageDecode Link'WorkflowEvent where
  messageDecoder = loop "" "" "" Nothing
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Link'WorkflowEvent {linkWorkflowEventNamespace = acc_0, linkWorkflowEventWorkflowid = acc_1, linkWorkflowEventRunid = acc_2, linkWorkflowEventReference = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldString
              loop acc_0 v acc_2 acc_3
            3 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 v acc_3
            100 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 (Just (Link'WorkflowEvent'Reference'EventRef v))
            101 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 (Just (Link'WorkflowEvent'Reference'RequestIdRef v))
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON Link'WorkflowEvent where
  protoToJSON msg = jsonObject
      [ "namespace" .= msg.linkWorkflowEventNamespace
      , "workflowId" .= msg.linkWorkflowEventWorkflowid
      , "runId" .= msg.linkWorkflowEventRunid
      , "reference" .= msg.linkWorkflowEventReference
      ]

instance ProtoFromJSON Link'WorkflowEvent where
  protoFromJSON (JsonObject obj) = do
    fld_linkWorkflowEventNamespace <- obj .:? "namespace"
    fld_linkWorkflowEventWorkflowid <- obj .:? "workflowId"
    fld_linkWorkflowEventRunid <- obj .:? "runId"
    fld_linkWorkflowEventReference <- obj .:? "reference"
    pure defaultLink'WorkflowEvent
      { linkWorkflowEventNamespace = maybe (linkWorkflowEventNamespace defaultLink'WorkflowEvent) id fld_linkWorkflowEventNamespace
      , linkWorkflowEventWorkflowid = maybe (linkWorkflowEventWorkflowid defaultLink'WorkflowEvent) id fld_linkWorkflowEventWorkflowid
      , linkWorkflowEventRunid = maybe (linkWorkflowEventRunid defaultLink'WorkflowEvent) id fld_linkWorkflowEventRunid
      , linkWorkflowEventReference = maybe (linkWorkflowEventReference defaultLink'WorkflowEvent) id fld_linkWorkflowEventReference
      }
  protoFromJSON _ = Right defaultLink'WorkflowEvent

data Link'BatchJob = Link'BatchJob
  { linkBatchJobJobid :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultLink'BatchJob :: Link'BatchJob
defaultLink'BatchJob = Link'BatchJob
  { linkBatchJobJobid = ""
  }

instance MessageEncode Link'BatchJob where
  buildMessage msg =
    (if msg.linkBatchJobJobid == T.empty then mempty else encodeFieldString 1 msg.linkBatchJobJobid)

instance MessageSize Link'BatchJob where
  messageSize msg =
    (if msg.linkBatchJobJobid == T.empty then 0 else fieldTextSize 1 msg.linkBatchJobJobid)

instance MessageDecode Link'BatchJob where
  messageDecoder = loop ""
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Link'BatchJob {linkBatchJobJobid = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON Link'BatchJob where
  protoToJSON msg = jsonObject
      [ "jobId" .= msg.linkBatchJobJobid

      ]

instance ProtoFromJSON Link'BatchJob where
  protoFromJSON (JsonObject obj) = do
    fld_linkBatchJobJobid <- obj .:? "jobId"
    pure defaultLink'BatchJob
      { linkBatchJobJobid = maybe (linkBatchJobJobid defaultLink'BatchJob) id fld_linkBatchJobJobid
      }
  protoFromJSON _ = Right defaultLink'BatchJob
data Link'Variant
  = Link'Variant'WorkflowEvent !Link'WorkflowEvent
  | Link'Variant'BatchJob !Link'BatchJob
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
instance ProtoToJSON Link'Variant where
  protoToJSON _ = JsonNull
instance ProtoFromJSON Link'Variant where
  protoFromJSON _ = Left "Cannot parse oneof from JSON"

defaultLink :: Link
defaultLink = Link
  { linkVariant = Nothing
  }

instance MessageEncode Link where
  buildMessage msg =
    (case msg.linkVariant of
      Nothing -> mempty
      Just (Link'Variant'WorkflowEvent v) -> encodeFieldMessage 1 v
      Just (Link'Variant'BatchJob v) -> encodeFieldMessage 2 v)

instance MessageSize Link where
  messageSize msg =
    (case msg.linkVariant of { Nothing -> 0; Just (Link'Variant'WorkflowEvent v) -> fieldMessageSize 1 (messageSize v)
    ; Just (Link'Variant'BatchJob v) -> fieldMessageSize 2 (messageSize v) })

instance MessageDecode Link where
  messageDecoder = loop Nothing
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Link {linkVariant = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just (Link'Variant'WorkflowEvent v))
            2 -> do
              v <- decodeFieldMessage
              loop (Just (Link'Variant'BatchJob v))
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON Link where
  protoToJSON msg = jsonObject
      [ "variant" .= msg.linkVariant

      ]

instance ProtoFromJSON Link where
  protoFromJSON (JsonObject obj) = do
    fld_linkVariant <- obj .:? "variant"
    pure defaultLink
      { linkVariant = maybe (linkVariant defaultLink) id fld_linkVariant
      }
  protoFromJSON _ = Right defaultLink

data Priority = Priority
  { priorityPrioritykey :: {-# UNPACK #-} !Int32
  , priorityFairnesskey :: !Text
  , priorityFairnessweight :: {-# UNPACK #-} !Float
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultPriority :: Priority
defaultPriority = Priority
  { priorityPrioritykey = 0
  , priorityFairnesskey = ""
  , priorityFairnessweight = 0
  }

instance MessageEncode Priority where
  buildMessage msg =
    (if msg.priorityPrioritykey == 0 then mempty else encodeFieldVarint 1 (fromIntegral msg.priorityPrioritykey))
    <> (if msg.priorityFairnesskey == T.empty then mempty else encodeFieldString 2 msg.priorityFairnesskey)
    <> (if msg.priorityFairnessweight == 0 then mempty else encodeFieldFloat 3 msg.priorityFairnessweight)

instance MessageSize Priority where
  messageSize msg =
    (if msg.priorityPrioritykey == 0 then 0 else fieldVarintSize 1 (fromIntegral msg.priorityPrioritykey))
    + (if msg.priorityFairnesskey == T.empty then 0 else fieldTextSize 2 msg.priorityFairnesskey)
    + (if msg.priorityFairnessweight == 0 then 0 else fieldFloatSize 3)

instance MessageDecode Priority where
  messageDecoder = loop 0 "" 0
    where
      loop acc_0 acc_1 acc_2 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Priority {priorityPrioritykey = acc_0, priorityFairnesskey = acc_1, priorityFairnessweight = acc_2})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop v acc_1 acc_2
            2 -> do
              v <- decodeFieldString
              loop acc_0 v acc_2
            3 -> do
              v <- decodeFieldFloat
              loop acc_0 acc_1 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2

instance ProtoToJSON Priority where
  protoToJSON msg = jsonObject
      [ "priorityKey" .= msg.priorityPrioritykey
      , "fairnessKey" .= msg.priorityFairnesskey
      , "fairnessWeight" .= msg.priorityFairnessweight
      ]

instance ProtoFromJSON Priority where
  protoFromJSON (JsonObject obj) = do
    fld_priorityPrioritykey <- obj .:? "priorityKey"
    fld_priorityFairnesskey <- obj .:? "fairnessKey"
    fld_priorityFairnessweight <- obj .:? "fairnessWeight"
    pure defaultPriority
      { priorityPrioritykey = maybe (priorityPrioritykey defaultPriority) id fld_priorityPrioritykey
      , priorityFairnesskey = maybe (priorityFairnesskey defaultPriority) id fld_priorityFairnesskey
      , priorityFairnessweight = maybe (priorityFairnessweight defaultPriority) id fld_priorityFairnessweight
      }
  protoFromJSON _ = Right defaultPriority

data WorkerSelector = WorkerSelector
  { workerSelectorSelector :: !(Maybe WorkerSelector'Selector)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
data WorkerSelector'Selector
  = WorkerSelector'Selector'WorkerInstanceKey !Text
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
instance ProtoToJSON WorkerSelector'Selector where
  protoToJSON _ = JsonNull
instance ProtoFromJSON WorkerSelector'Selector where
  protoFromJSON _ = Left "Cannot parse oneof from JSON"

defaultWorkerSelector :: WorkerSelector
defaultWorkerSelector = WorkerSelector
  { workerSelectorSelector = Nothing
  }

instance MessageEncode WorkerSelector where
  buildMessage msg =
    (case msg.workerSelectorSelector of
      Nothing -> mempty
      Just (WorkerSelector'Selector'WorkerInstanceKey v) -> encodeFieldString 1 v)

instance MessageSize WorkerSelector where
  messageSize msg =
    (case msg.workerSelectorSelector of { Nothing -> 0; Just (WorkerSelector'Selector'WorkerInstanceKey v) -> fieldTextSize 1 v })

instance MessageDecode WorkerSelector where
  messageDecoder = loop Nothing
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (WorkerSelector {workerSelectorSelector = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop (Just (WorkerSelector'Selector'WorkerInstanceKey v))
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON WorkerSelector where
  protoToJSON msg = jsonObject
      [ "selector" .= msg.workerSelectorSelector

      ]

instance ProtoFromJSON WorkerSelector where
  protoFromJSON (JsonObject obj) = do
    fld_workerSelectorSelector <- obj .:? "selector"
    pure defaultWorkerSelector
      { workerSelectorSelector = maybe (workerSelectorSelector defaultWorkerSelector) id fld_workerSelectorSelector
      }
  protoFromJSON _ = Right defaultWorkerSelector