{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.export.v1@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Temporalio.Api.Export.V1.Message where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.JSON (jsonObject, (.=:), parseFieldMaybe)
import Data.Proxy (Proxy(..))
import Proto.Message (IsMessage(..))
import qualified Proto.Registry
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import qualified Proto.Temporalio.Api.History.V1.Message as TE_History_V1_Message


data WorkflowExecution = WorkflowExecution
  { workflowExecutionHistory :: !(Maybe TE_History_V1_Message.History)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkflowExecution :: WorkflowExecution
defaultWorkflowExecution = WorkflowExecution
  { workflowExecutionHistory = Nothing
  }

instance MessageEncode WorkflowExecution where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.workflowExecutionHistory)

instance MessageSize WorkflowExecution where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.workflowExecutionHistory)

instance MessageDecode WorkflowExecution where
  messageDecoder = loop Nothing
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (WorkflowExecution {workflowExecutionHistory = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v)
            _ -> skipField wt >> loop acc_0

instance IsMessage WorkflowExecution where
  messageTypeName _ = "temporal.api.export.v1.WorkflowExecution"

instance Aeson.ToJSON WorkflowExecution where
  toJSON msg = jsonObject
      [ "history" .=: msg.workflowExecutionHistory

      ]

instance Aeson.FromJSON WorkflowExecution where
  parseJSON = Aeson.withObject "" $ \obj -> do
    fld_workflowExecutionHistory <- parseFieldMaybe obj "history"
    pure defaultWorkflowExecution
      { workflowExecutionHistory = maybe (workflowExecutionHistory defaultWorkflowExecution) id fld_workflowExecutionHistory
      }

data WorkflowExecutions = WorkflowExecutions
  { workflowExecutionsItems :: !(V.Vector WorkflowExecution)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkflowExecutions :: WorkflowExecutions
defaultWorkflowExecutions = WorkflowExecutions
  { workflowExecutionsItems = V.empty
  }

instance MessageEncode WorkflowExecutions where
  buildMessage msg =
    V.foldl' (\acc v -> acc <> encodeFieldMessage 1 v) mempty msg.workflowExecutionsItems

instance MessageSize WorkflowExecutions where
  messageSize msg =
    (V.foldl' (\acc v -> acc + fieldMessageSize 1 (messageSize v)) 0 msg.workflowExecutionsItems)

instance MessageDecode WorkflowExecutions where
  messageDecoder = loop V.empty
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (WorkflowExecutions {workflowExecutionsItems = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (acc_0 <> V.singleton v)
            _ -> skipField wt >> loop acc_0

instance IsMessage WorkflowExecutions where
  messageTypeName _ = "temporal.api.export.v1.WorkflowExecutions"

instance Aeson.ToJSON WorkflowExecutions where
  toJSON msg = jsonObject
      [ "items" .=: msg.workflowExecutionsItems

      ]

instance Aeson.FromJSON WorkflowExecutions where
  parseJSON = Aeson.withObject "" $ \obj -> do
    fld_workflowExecutionsItems <- parseFieldMaybe obj "items"
    pure defaultWorkflowExecutions
      { workflowExecutionsItems = maybe (workflowExecutionsItems defaultWorkflowExecutions) id fld_workflowExecutionsItems
      }

-- | Register all message types defined in this module.
registerModuleTypes :: Proto.Registry.MessageRegistry -> Proto.Registry.MessageRegistry
registerModuleTypes =
  Proto.Registry.registerType (Proxy :: Proxy WorkflowExecution) .
  Proto.Registry.registerType (Proxy :: Proxy WorkflowExecutions) .  id