{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.schedule.v1@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Temporal.Temporal.Api.Schedule.V1.Message where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Proto.Encode
import Proto.Decode
import Proto.JSON
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize)
import Proto.Google.Protobuf.Duration (Duration)
import Proto.Google.Protobuf.Timestamp (Timestamp)
import Proto.Temporal.Temporal.Api.Common.V1.Message (Memo, SearchAttributes, WorkflowExecution, WorkflowType)
import Proto.Temporal.Temporal.Api.Enums.V1.Schedule (ScheduleOverlapPolicy)
import Proto.Temporal.Temporal.Api.Enums.V1.Workflow (WorkflowExecutionStatus)
import Proto.Temporal.Temporal.Api.Workflow.V1.Message (NewWorkflowExecutionInfo)


data CalendarSpec = CalendarSpec
  { calendarSpecSecond :: !Text
  , calendarSpecMinute :: !Text
  , calendarSpecHour :: !Text
  , calendarSpecDayofmonth :: !Text
  , calendarSpecMonth :: !Text
  , calendarSpecYear :: !Text
  , calendarSpecDayofweek :: !Text
  , calendarSpecComment :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultCalendarSpec :: CalendarSpec
defaultCalendarSpec = CalendarSpec
  { calendarSpecSecond = ""
  , calendarSpecMinute = ""
  , calendarSpecHour = ""
  , calendarSpecDayofmonth = ""
  , calendarSpecMonth = ""
  , calendarSpecYear = ""
  , calendarSpecDayofweek = ""
  , calendarSpecComment = ""
  }

instance MessageEncode CalendarSpec where
  buildMessage msg =
    (if msg.calendarSpecSecond == T.empty then mempty else encodeFieldString 1 msg.calendarSpecSecond)
    <> (if msg.calendarSpecMinute == T.empty then mempty else encodeFieldString 2 msg.calendarSpecMinute)
    <> (if msg.calendarSpecHour == T.empty then mempty else encodeFieldString 3 msg.calendarSpecHour)
    <> (if msg.calendarSpecDayofmonth == T.empty then mempty else encodeFieldString 4 msg.calendarSpecDayofmonth)
    <> (if msg.calendarSpecMonth == T.empty then mempty else encodeFieldString 5 msg.calendarSpecMonth)
    <> (if msg.calendarSpecYear == T.empty then mempty else encodeFieldString 6 msg.calendarSpecYear)
    <> (if msg.calendarSpecDayofweek == T.empty then mempty else encodeFieldString 7 msg.calendarSpecDayofweek)
    <> (if msg.calendarSpecComment == T.empty then mempty else encodeFieldString 8 msg.calendarSpecComment)

instance MessageSize CalendarSpec where
  messageSize msg =
    (if msg.calendarSpecSecond == T.empty then 0 else fieldTextSize 1 msg.calendarSpecSecond)
    + (if msg.calendarSpecMinute == T.empty then 0 else fieldTextSize 2 msg.calendarSpecMinute)
    + (if msg.calendarSpecHour == T.empty then 0 else fieldTextSize 3 msg.calendarSpecHour)
    + (if msg.calendarSpecDayofmonth == T.empty then 0 else fieldTextSize 4 msg.calendarSpecDayofmonth)
    + (if msg.calendarSpecMonth == T.empty then 0 else fieldTextSize 5 msg.calendarSpecMonth)
    + (if msg.calendarSpecYear == T.empty then 0 else fieldTextSize 6 msg.calendarSpecYear)
    + (if msg.calendarSpecDayofweek == T.empty then 0 else fieldTextSize 7 msg.calendarSpecDayofweek)
    + (if msg.calendarSpecComment == T.empty then 0 else fieldTextSize 8 msg.calendarSpecComment)

instance MessageDecode CalendarSpec where
  messageDecoder = loop "" "" "" "" "" "" "" ""
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (CalendarSpec {calendarSpecSecond = acc_0, calendarSpecMinute = acc_1, calendarSpecHour = acc_2, calendarSpecDayofmonth = acc_3, calendarSpecMonth = acc_4, calendarSpecYear = acc_5, calendarSpecDayofweek = acc_6, calendarSpecComment = acc_7})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7
            2 -> do
              v <- decodeFieldString
              loop acc_0 v acc_2 acc_3 acc_4 acc_5 acc_6 acc_7
            3 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 v acc_3 acc_4 acc_5 acc_6 acc_7
            4 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 v acc_4 acc_5 acc_6 acc_7
            5 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 acc_3 v acc_5 acc_6 acc_7
            6 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 acc_3 acc_4 v acc_6 acc_7
            7 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 v acc_7
            8 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7

instance ProtoToJSON CalendarSpec where
  protoToJSON msg = jsonObject
      [ "second" .= msg.calendarSpecSecond
      , "minute" .= msg.calendarSpecMinute
      , "hour" .= msg.calendarSpecHour
      , "dayOfMonth" .= msg.calendarSpecDayofmonth
      , "month" .= msg.calendarSpecMonth
      , "year" .= msg.calendarSpecYear
      , "dayOfWeek" .= msg.calendarSpecDayofweek
      , "comment" .= msg.calendarSpecComment
      ]

instance ProtoFromJSON CalendarSpec where
  protoFromJSON (JsonObject obj) = do
    v_calendarSpecSecond <- obj .:? "second"
    v_calendarSpecMinute <- obj .:? "minute"
    v_calendarSpecHour <- obj .:? "hour"
    v_calendarSpecDayofmonth <- obj .:? "dayOfMonth"
    v_calendarSpecMonth <- obj .:? "month"
    v_calendarSpecYear <- obj .:? "year"
    v_calendarSpecDayofweek <- obj .:? "dayOfWeek"
    v_calendarSpecComment <- obj .:? "comment"
    pure (CalendarSpec {
       calendarSpecSecond = v_calendarSpecSecond
      , calendarSpecMinute = v_calendarSpecMinute
      , calendarSpecHour = v_calendarSpecHour
      , calendarSpecDayofmonth = v_calendarSpecDayofmonth
      , calendarSpecMonth = v_calendarSpecMonth
      , calendarSpecYear = v_calendarSpecYear
      , calendarSpecDayofweek = v_calendarSpecDayofweek
      , calendarSpecComment = v_calendarSpecComment
    })
  protoFromJSON _ = Left "Expected JSON object"

data Range = Range
  { rangeStart :: {-# UNPACK #-} !Int32
  , rangeEnd :: {-# UNPACK #-} !Int32
  , rangeStep :: {-# UNPACK #-} !Int32
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultRange :: Range
defaultRange = Range
  { rangeStart = 0
  , rangeEnd = 0
  , rangeStep = 0
  }

instance MessageEncode Range where
  buildMessage msg =
    (if msg.rangeStart == 0 then mempty else encodeFieldVarint 1 (fromIntegral msg.rangeStart))
    <> (if msg.rangeEnd == 0 then mempty else encodeFieldVarint 2 (fromIntegral msg.rangeEnd))
    <> (if msg.rangeStep == 0 then mempty else encodeFieldVarint 3 (fromIntegral msg.rangeStep))

instance MessageSize Range where
  messageSize msg =
    (if msg.rangeStart == 0 then 0 else fieldVarintSize 1 (fromIntegral msg.rangeStart))
    + (if msg.rangeEnd == 0 then 0 else fieldVarintSize 2 (fromIntegral msg.rangeEnd))
    + (if msg.rangeStep == 0 then 0 else fieldVarintSize 3 (fromIntegral msg.rangeStep))

instance MessageDecode Range where
  messageDecoder = loop 0 0 0
    where
      loop acc_0 acc_1 acc_2 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Range {rangeStart = acc_0, rangeEnd = acc_1, rangeStep = acc_2})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- fromIntegral <$> decodeFieldVarint
              loop v acc_1 acc_2
            2 -> do
              v <- fromIntegral <$> decodeFieldVarint
              loop acc_0 v acc_2
            3 -> do
              v <- fromIntegral <$> decodeFieldVarint
              loop acc_0 acc_1 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2

instance ProtoToJSON Range where
  protoToJSON msg = jsonObject
      [ "start" .= msg.rangeStart
      , "end" .= msg.rangeEnd
      , "step" .= msg.rangeStep
      ]

instance ProtoFromJSON Range where
  protoFromJSON (JsonObject obj) = do
    v_rangeStart <- obj .:? "start"
    v_rangeEnd <- obj .:? "end"
    v_rangeStep <- obj .:? "step"
    pure (Range {
       rangeStart = v_rangeStart
      , rangeEnd = v_rangeEnd
      , rangeStep = v_rangeStep
    })
  protoFromJSON _ = Left "Expected JSON object"

data StructuredCalendarSpec = StructuredCalendarSpec
  { structuredCalendarSpecSecond :: !(V.Vector Range)
  , structuredCalendarSpecMinute :: !(V.Vector Range)
  , structuredCalendarSpecHour :: !(V.Vector Range)
  , structuredCalendarSpecDayofmonth :: !(V.Vector Range)
  , structuredCalendarSpecMonth :: !(V.Vector Range)
  , structuredCalendarSpecYear :: !(V.Vector Range)
  , structuredCalendarSpecDayofweek :: !(V.Vector Range)
  , structuredCalendarSpecComment :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultStructuredCalendarSpec :: StructuredCalendarSpec
defaultStructuredCalendarSpec = StructuredCalendarSpec
  { structuredCalendarSpecSecond = V.empty
  , structuredCalendarSpecMinute = V.empty
  , structuredCalendarSpecHour = V.empty
  , structuredCalendarSpecDayofmonth = V.empty
  , structuredCalendarSpecMonth = V.empty
  , structuredCalendarSpecYear = V.empty
  , structuredCalendarSpecDayofweek = V.empty
  , structuredCalendarSpecComment = ""
  }

instance MessageEncode StructuredCalendarSpec where
  buildMessage msg =
    V.foldl' (\acc v -> acc <> encodeFieldMessage 1 v) mempty msg.structuredCalendarSpecSecond
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 2 v) mempty msg.structuredCalendarSpecMinute
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 3 v) mempty msg.structuredCalendarSpecHour
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 4 v) mempty msg.structuredCalendarSpecDayofmonth
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 5 v) mempty msg.structuredCalendarSpecMonth
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 6 v) mempty msg.structuredCalendarSpecYear
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 7 v) mempty msg.structuredCalendarSpecDayofweek
    <> (if msg.structuredCalendarSpecComment == T.empty then mempty else encodeFieldString 8 msg.structuredCalendarSpecComment)

instance MessageSize StructuredCalendarSpec where
  messageSize msg =
    (V.foldl' (\acc v -> acc + fieldMessageSize 1 (messageSize v)) 0 msg.structuredCalendarSpecSecond)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 2 (messageSize v)) 0 msg.structuredCalendarSpecMinute)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 3 (messageSize v)) 0 msg.structuredCalendarSpecHour)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 4 (messageSize v)) 0 msg.structuredCalendarSpecDayofmonth)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 5 (messageSize v)) 0 msg.structuredCalendarSpecMonth)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 6 (messageSize v)) 0 msg.structuredCalendarSpecYear)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 7 (messageSize v)) 0 msg.structuredCalendarSpecDayofweek)
    + (if msg.structuredCalendarSpecComment == T.empty then 0 else fieldTextSize 8 msg.structuredCalendarSpecComment)

instance MessageDecode StructuredCalendarSpec where
  messageDecoder = loop V.empty V.empty V.empty V.empty V.empty V.empty V.empty ""
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (StructuredCalendarSpec {structuredCalendarSpecSecond = acc_0, structuredCalendarSpecMinute = acc_1, structuredCalendarSpecHour = acc_2, structuredCalendarSpecDayofmonth = acc_3, structuredCalendarSpecMonth = acc_4, structuredCalendarSpecYear = acc_5, structuredCalendarSpecDayofweek = acc_6, structuredCalendarSpecComment = acc_7})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (acc_0 <> V.singleton v) acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (acc_1 <> V.singleton v) acc_2 acc_3 acc_4 acc_5 acc_6 acc_7
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (acc_2 <> V.singleton v) acc_3 acc_4 acc_5 acc_6 acc_7
            4 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 (acc_3 <> V.singleton v) acc_4 acc_5 acc_6 acc_7
            5 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 (acc_4 <> V.singleton v) acc_5 acc_6 acc_7
            6 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 (acc_5 <> V.singleton v) acc_6 acc_7
            7 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 (acc_6 <> V.singleton v) acc_7
            8 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7

instance ProtoToJSON StructuredCalendarSpec where
  protoToJSON msg = jsonObject
      [ "second" .= msg.structuredCalendarSpecSecond
      , "minute" .= msg.structuredCalendarSpecMinute
      , "hour" .= msg.structuredCalendarSpecHour
      , "dayOfMonth" .= msg.structuredCalendarSpecDayofmonth
      , "month" .= msg.structuredCalendarSpecMonth
      , "year" .= msg.structuredCalendarSpecYear
      , "dayOfWeek" .= msg.structuredCalendarSpecDayofweek
      , "comment" .= msg.structuredCalendarSpecComment
      ]

instance ProtoFromJSON StructuredCalendarSpec where
  protoFromJSON (JsonObject obj) = do
    v_structuredCalendarSpecSecond <- obj .:? "second"
    v_structuredCalendarSpecMinute <- obj .:? "minute"
    v_structuredCalendarSpecHour <- obj .:? "hour"
    v_structuredCalendarSpecDayofmonth <- obj .:? "dayOfMonth"
    v_structuredCalendarSpecMonth <- obj .:? "month"
    v_structuredCalendarSpecYear <- obj .:? "year"
    v_structuredCalendarSpecDayofweek <- obj .:? "dayOfWeek"
    v_structuredCalendarSpecComment <- obj .:? "comment"
    pure (StructuredCalendarSpec {
       structuredCalendarSpecSecond = v_structuredCalendarSpecSecond
      , structuredCalendarSpecMinute = v_structuredCalendarSpecMinute
      , structuredCalendarSpecHour = v_structuredCalendarSpecHour
      , structuredCalendarSpecDayofmonth = v_structuredCalendarSpecDayofmonth
      , structuredCalendarSpecMonth = v_structuredCalendarSpecMonth
      , structuredCalendarSpecYear = v_structuredCalendarSpecYear
      , structuredCalendarSpecDayofweek = v_structuredCalendarSpecDayofweek
      , structuredCalendarSpecComment = v_structuredCalendarSpecComment
    })
  protoFromJSON _ = Left "Expected JSON object"

data IntervalSpec = IntervalSpec
  { intervalSpecInterval :: !(Maybe Duration)
  , intervalSpecPhase :: !(Maybe Duration)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultIntervalSpec :: IntervalSpec
defaultIntervalSpec = IntervalSpec
  { intervalSpecInterval = Nothing
  , intervalSpecPhase = Nothing
  }

instance MessageEncode IntervalSpec where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.intervalSpecInterval)
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.intervalSpecPhase)

instance MessageSize IntervalSpec where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.intervalSpecInterval)
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.intervalSpecPhase)

instance MessageDecode IntervalSpec where
  messageDecoder = loop Nothing Nothing
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (IntervalSpec {intervalSpecInterval = acc_0, intervalSpecPhase = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v) acc_1
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v)
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON IntervalSpec where
  protoToJSON msg = jsonObject
      [ "interval" .= msg.intervalSpecInterval
      , "phase" .= msg.intervalSpecPhase
      ]

instance ProtoFromJSON IntervalSpec where
  protoFromJSON (JsonObject obj) = do
    v_intervalSpecInterval <- obj .:? "interval"
    v_intervalSpecPhase <- obj .:? "phase"
    pure (IntervalSpec {
       intervalSpecInterval = v_intervalSpecInterval
      , intervalSpecPhase = v_intervalSpecPhase
    })
  protoFromJSON _ = Left "Expected JSON object"

data ScheduleSpec = ScheduleSpec
  { scheduleSpecStructuredcalendar :: !(V.Vector StructuredCalendarSpec)
  , scheduleSpecCronstring :: !(V.Vector Text)
  , scheduleSpecCalendar :: !(V.Vector CalendarSpec)
  , scheduleSpecInterval :: !(V.Vector IntervalSpec)
  , scheduleSpecExcludecalendar :: !(V.Vector CalendarSpec)
  , scheduleSpecExcludestructuredcalendar :: !(V.Vector StructuredCalendarSpec)
  , scheduleSpecStarttime :: !(Maybe Timestamp)
  , scheduleSpecEndtime :: !(Maybe Timestamp)
  , scheduleSpecJitter :: !(Maybe Duration)
  , scheduleSpecTimezonename :: !Text
  , scheduleSpecTimezonedata :: !ByteString
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultScheduleSpec :: ScheduleSpec
defaultScheduleSpec = ScheduleSpec
  { scheduleSpecStructuredcalendar = V.empty
  , scheduleSpecCronstring = V.empty
  , scheduleSpecCalendar = V.empty
  , scheduleSpecInterval = V.empty
  , scheduleSpecExcludecalendar = V.empty
  , scheduleSpecExcludestructuredcalendar = V.empty
  , scheduleSpecStarttime = Nothing
  , scheduleSpecEndtime = Nothing
  , scheduleSpecJitter = Nothing
  , scheduleSpecTimezonename = ""
  , scheduleSpecTimezonedata = ""
  }

instance MessageEncode ScheduleSpec where
  buildMessage msg =
    V.foldl' (\acc v -> acc <> encodeFieldMessage 7 v) mempty msg.scheduleSpecStructuredcalendar
    <> V.foldl' (\acc v -> acc <> encodeFieldString 8 v) mempty msg.scheduleSpecCronstring
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 1 v) mempty msg.scheduleSpecCalendar
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 2 v) mempty msg.scheduleSpecInterval
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 3 v) mempty msg.scheduleSpecExcludecalendar
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 9 v) mempty msg.scheduleSpecExcludestructuredcalendar
    <> (maybe mempty (\v -> encodeFieldMessage 4 v) msg.scheduleSpecStarttime)
    <> (maybe mempty (\v -> encodeFieldMessage 5 v) msg.scheduleSpecEndtime)
    <> (maybe mempty (\v -> encodeFieldMessage 6 v) msg.scheduleSpecJitter)
    <> (if msg.scheduleSpecTimezonename == T.empty then mempty else encodeFieldString 10 msg.scheduleSpecTimezonename)
    <> (if BS.null msg.scheduleSpecTimezonedata then mempty else encodeFieldBytes 11 msg.scheduleSpecTimezonedata)

instance MessageSize ScheduleSpec where
  messageSize msg =
    (V.foldl' (\acc v -> acc + fieldMessageSize 7 (messageSize v)) 0 msg.scheduleSpecStructuredcalendar)
    + (sizeRepeated 8 msg.scheduleSpecCronstring)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 1 (messageSize v)) 0 msg.scheduleSpecCalendar)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 2 (messageSize v)) 0 msg.scheduleSpecInterval)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 3 (messageSize v)) 0 msg.scheduleSpecExcludecalendar)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 9 (messageSize v)) 0 msg.scheduleSpecExcludestructuredcalendar)
    + (maybe 0 (\v -> fieldMessageSize 4 (messageSize v)) msg.scheduleSpecStarttime)
    + (maybe 0 (\v -> fieldMessageSize 5 (messageSize v)) msg.scheduleSpecEndtime)
    + (maybe 0 (\v -> fieldMessageSize 6 (messageSize v)) msg.scheduleSpecJitter)
    + (if msg.scheduleSpecTimezonename == T.empty then 0 else fieldTextSize 10 msg.scheduleSpecTimezonename)
    + (if BS.null msg.scheduleSpecTimezonedata then 0 else fieldBytesSize 11 msg.scheduleSpecTimezonedata)

instance MessageDecode ScheduleSpec where
  messageDecoder = loop V.empty V.empty V.empty V.empty V.empty V.empty Nothing Nothing Nothing "" ""
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (ScheduleSpec {scheduleSpecStructuredcalendar = acc_0, scheduleSpecCronstring = acc_1, scheduleSpecCalendar = acc_2, scheduleSpecInterval = acc_3, scheduleSpecExcludecalendar = acc_4, scheduleSpecExcludestructuredcalendar = acc_5, scheduleSpecStarttime = acc_6, scheduleSpecEndtime = acc_7, scheduleSpecJitter = acc_8, scheduleSpecTimezonename = acc_9, scheduleSpecTimezonedata = acc_10})
          Just (Tag fn wt) -> case fn of
            7 -> do
              v <- decodeFieldMessage
              loop (acc_0 <> V.singleton v) acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10
            8 -> do
              v <- decodeFieldString
              loop acc_0 (acc_1 <> V.singleton v) acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10
            1 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (acc_2 <> V.singleton v) acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 (acc_3 <> V.singleton v) acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 (acc_4 <> V.singleton v) acc_5 acc_6 acc_7 acc_8 acc_9 acc_10
            9 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 (acc_5 <> V.singleton v) acc_6 acc_7 acc_8 acc_9 acc_10
            4 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 (Just v) acc_7 acc_8 acc_9 acc_10
            5 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 (Just v) acc_8 acc_9 acc_10
            6 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 (Just v) acc_9 acc_10
            10 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 v acc_10
            11 -> do
              v <- decodeFieldBytes
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10

instance ProtoToJSON ScheduleSpec where
  protoToJSON msg = jsonObject
      [ "structuredCalendar" .= msg.scheduleSpecStructuredcalendar
      , "cronString" .= msg.scheduleSpecCronstring
      , "calendar" .= msg.scheduleSpecCalendar
      , "interval" .= msg.scheduleSpecInterval
      , "excludeCalendar" .= msg.scheduleSpecExcludecalendar
      , "excludeStructuredCalendar" .= msg.scheduleSpecExcludestructuredcalendar
      , "startTime" .= msg.scheduleSpecStarttime
      , "endTime" .= msg.scheduleSpecEndtime
      , "jitter" .= msg.scheduleSpecJitter
      , "timezoneName" .= msg.scheduleSpecTimezonename
      , "timezoneData" .= msg.scheduleSpecTimezonedata
      ]

instance ProtoFromJSON ScheduleSpec where
  protoFromJSON (JsonObject obj) = do
    v_scheduleSpecStructuredcalendar <- obj .:? "structuredCalendar"
    v_scheduleSpecCronstring <- obj .:? "cronString"
    v_scheduleSpecCalendar <- obj .:? "calendar"
    v_scheduleSpecInterval <- obj .:? "interval"
    v_scheduleSpecExcludecalendar <- obj .:? "excludeCalendar"
    v_scheduleSpecExcludestructuredcalendar <- obj .:? "excludeStructuredCalendar"
    v_scheduleSpecStarttime <- obj .:? "startTime"
    v_scheduleSpecEndtime <- obj .:? "endTime"
    v_scheduleSpecJitter <- obj .:? "jitter"
    v_scheduleSpecTimezonename <- obj .:? "timezoneName"
    v_scheduleSpecTimezonedata <- obj .:? "timezoneData"
    pure (ScheduleSpec {
       scheduleSpecStructuredcalendar = v_scheduleSpecStructuredcalendar
      , scheduleSpecCronstring = v_scheduleSpecCronstring
      , scheduleSpecCalendar = v_scheduleSpecCalendar
      , scheduleSpecInterval = v_scheduleSpecInterval
      , scheduleSpecExcludecalendar = v_scheduleSpecExcludecalendar
      , scheduleSpecExcludestructuredcalendar = v_scheduleSpecExcludestructuredcalendar
      , scheduleSpecStarttime = v_scheduleSpecStarttime
      , scheduleSpecEndtime = v_scheduleSpecEndtime
      , scheduleSpecJitter = v_scheduleSpecJitter
      , scheduleSpecTimezonename = v_scheduleSpecTimezonename
      , scheduleSpecTimezonedata = v_scheduleSpecTimezonedata
    })
  protoFromJSON _ = Left "Expected JSON object"

data SchedulePolicies = SchedulePolicies
  { schedulePoliciesOverlappolicy :: !ScheduleOverlapPolicy
  , schedulePoliciesCatchupwindow :: !(Maybe Duration)
  , schedulePoliciesPauseonfailure :: {-# UNPACK #-} !Bool
  , schedulePoliciesKeeporiginalworkflowid :: {-# UNPACK #-} !Bool
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultSchedulePolicies :: SchedulePolicies
defaultSchedulePolicies = SchedulePolicies
  { schedulePoliciesOverlappolicy = (toEnum 0)
  , schedulePoliciesCatchupwindow = Nothing
  , schedulePoliciesPauseonfailure = False
  , schedulePoliciesKeeporiginalworkflowid = False
  }

instance MessageEncode SchedulePolicies where
  buildMessage msg =
    (if fromEnum msg.schedulePoliciesOverlappolicy == 0 then mempty else encodeFieldVarint 1 (fromIntegral (fromEnum msg.schedulePoliciesOverlappolicy)))
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.schedulePoliciesCatchupwindow)
    <> (if msg.schedulePoliciesPauseonfailure == False then mempty else encodeFieldBool 3 msg.schedulePoliciesPauseonfailure)
    <> (if msg.schedulePoliciesKeeporiginalworkflowid == False then mempty else encodeFieldBool 4 msg.schedulePoliciesKeeporiginalworkflowid)

instance MessageSize SchedulePolicies where
  messageSize msg =
    (if fromEnum msg.schedulePoliciesOverlappolicy == 0 then 0 else fieldVarintSize 1 (fromIntegral (fromEnum msg.schedulePoliciesOverlappolicy)))
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.schedulePoliciesCatchupwindow)
    + (if msg.schedulePoliciesPauseonfailure == False then 0 else fieldBoolSize 3)
    + (if msg.schedulePoliciesKeeporiginalworkflowid == False then 0 else fieldBoolSize 4)

instance MessageDecode SchedulePolicies where
  messageDecoder = loop (toEnum 0) Nothing False False
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (SchedulePolicies {schedulePoliciesOverlappolicy = acc_0, schedulePoliciesCatchupwindow = acc_1, schedulePoliciesPauseonfailure = acc_2, schedulePoliciesKeeporiginalworkflowid = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldEnum
              loop v acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2 acc_3
            3 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 v acc_3
            4 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON SchedulePolicies where
  protoToJSON msg = jsonObject
      [ "overlapPolicy" .= msg.schedulePoliciesOverlappolicy
      , "catchupWindow" .= msg.schedulePoliciesCatchupwindow
      , "pauseOnFailure" .= msg.schedulePoliciesPauseonfailure
      , "keepOriginalWorkflowId" .= msg.schedulePoliciesKeeporiginalworkflowid
      ]

instance ProtoFromJSON SchedulePolicies where
  protoFromJSON (JsonObject obj) = do
    v_schedulePoliciesOverlappolicy <- obj .:? "overlapPolicy"
    v_schedulePoliciesCatchupwindow <- obj .:? "catchupWindow"
    v_schedulePoliciesPauseonfailure <- obj .:? "pauseOnFailure"
    v_schedulePoliciesKeeporiginalworkflowid <- obj .:? "keepOriginalWorkflowId"
    pure (SchedulePolicies {
       schedulePoliciesOverlappolicy = v_schedulePoliciesOverlappolicy
      , schedulePoliciesCatchupwindow = v_schedulePoliciesCatchupwindow
      , schedulePoliciesPauseonfailure = v_schedulePoliciesPauseonfailure
      , schedulePoliciesKeeporiginalworkflowid = v_schedulePoliciesKeeporiginalworkflowid
    })
  protoFromJSON _ = Left "Expected JSON object"

data ScheduleAction = ScheduleAction
  { scheduleActionAction :: !(Maybe ScheduleAction'Action)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
data ScheduleAction'Action
  = ScheduleAction'StartWorkflow !NewWorkflowExecutionInfo
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultScheduleAction :: ScheduleAction
defaultScheduleAction = ScheduleAction
  { scheduleActionAction = Nothing
  }

instance MessageEncode ScheduleAction where
  buildMessage msg =
    (case msg.scheduleActionAction of
      Nothing -> mempty
      Just (ScheduleAction'StartWorkflow v) -> encodeFieldMessage 1 v)

instance MessageSize ScheduleAction where
  messageSize msg =
    (case msg.scheduleActionAction of { Nothing -> 0; Just (ScheduleAction'StartWorkflow v) -> fieldMessageSize 1 (messageSize v) })

instance MessageDecode ScheduleAction where
  messageDecoder = loop Nothing
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (ScheduleAction {scheduleActionAction = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just (ScheduleAction'StartWorkflow v))
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON ScheduleAction where
  protoToJSON msg = jsonObject
      [ "action" .= msg.scheduleActionAction

      ]

instance ProtoFromJSON ScheduleAction where
  protoFromJSON (JsonObject obj) = do
    v_scheduleActionAction <- obj .:? "action"
    pure (ScheduleAction {
       scheduleActionAction = v_scheduleActionAction
    })
  protoFromJSON _ = Left "Expected JSON object"

data ScheduleActionResult = ScheduleActionResult
  { scheduleActionResultScheduletime :: !(Maybe Timestamp)
  , scheduleActionResultActualtime :: !(Maybe Timestamp)
  , scheduleActionResultStartworkflowresult :: !(Maybe WorkflowExecution)
  , scheduleActionResultStartworkflowstatus :: !WorkflowExecutionStatus
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultScheduleActionResult :: ScheduleActionResult
defaultScheduleActionResult = ScheduleActionResult
  { scheduleActionResultScheduletime = Nothing
  , scheduleActionResultActualtime = Nothing
  , scheduleActionResultStartworkflowresult = Nothing
  , scheduleActionResultStartworkflowstatus = (toEnum 0)
  }

instance MessageEncode ScheduleActionResult where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.scheduleActionResultScheduletime)
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.scheduleActionResultActualtime)
    <> (maybe mempty (\v -> encodeFieldMessage 11 v) msg.scheduleActionResultStartworkflowresult)
    <> (if fromEnum msg.scheduleActionResultStartworkflowstatus == 0 then mempty else encodeFieldVarint 12 (fromIntegral (fromEnum msg.scheduleActionResultStartworkflowstatus)))

instance MessageSize ScheduleActionResult where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.scheduleActionResultScheduletime)
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.scheduleActionResultActualtime)
    + (maybe 0 (\v -> fieldMessageSize 11 (messageSize v)) msg.scheduleActionResultStartworkflowresult)
    + (if fromEnum msg.scheduleActionResultStartworkflowstatus == 0 then 0 else fieldVarintSize 12 (fromIntegral (fromEnum msg.scheduleActionResultStartworkflowstatus)))

instance MessageDecode ScheduleActionResult where
  messageDecoder = loop Nothing Nothing Nothing (toEnum 0)
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (ScheduleActionResult {scheduleActionResultScheduletime = acc_0, scheduleActionResultActualtime = acc_1, scheduleActionResultStartworkflowresult = acc_2, scheduleActionResultStartworkflowstatus = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v) acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2 acc_3
            11 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (Just v) acc_3
            12 -> do
              v <- decodeFieldEnum
              loop acc_0 acc_1 acc_2 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON ScheduleActionResult where
  protoToJSON msg = jsonObject
      [ "scheduleTime" .= msg.scheduleActionResultScheduletime
      , "actualTime" .= msg.scheduleActionResultActualtime
      , "startWorkflowResult" .= msg.scheduleActionResultStartworkflowresult
      , "startWorkflowStatus" .= msg.scheduleActionResultStartworkflowstatus
      ]

instance ProtoFromJSON ScheduleActionResult where
  protoFromJSON (JsonObject obj) = do
    v_scheduleActionResultScheduletime <- obj .:? "scheduleTime"
    v_scheduleActionResultActualtime <- obj .:? "actualTime"
    v_scheduleActionResultStartworkflowresult <- obj .:? "startWorkflowResult"
    v_scheduleActionResultStartworkflowstatus <- obj .:? "startWorkflowStatus"
    pure (ScheduleActionResult {
       scheduleActionResultScheduletime = v_scheduleActionResultScheduletime
      , scheduleActionResultActualtime = v_scheduleActionResultActualtime
      , scheduleActionResultStartworkflowresult = v_scheduleActionResultStartworkflowresult
      , scheduleActionResultStartworkflowstatus = v_scheduleActionResultStartworkflowstatus
    })
  protoFromJSON _ = Left "Expected JSON object"

data ScheduleState = ScheduleState
  { scheduleStateNotes :: !Text
  , scheduleStatePaused :: {-# UNPACK #-} !Bool
  , scheduleStateLimitedactions :: {-# UNPACK #-} !Bool
  , scheduleStateRemainingactions :: {-# UNPACK #-} !Int64
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultScheduleState :: ScheduleState
defaultScheduleState = ScheduleState
  { scheduleStateNotes = ""
  , scheduleStatePaused = False
  , scheduleStateLimitedactions = False
  , scheduleStateRemainingactions = 0
  }

instance MessageEncode ScheduleState where
  buildMessage msg =
    (if msg.scheduleStateNotes == T.empty then mempty else encodeFieldString 1 msg.scheduleStateNotes)
    <> (if msg.scheduleStatePaused == False then mempty else encodeFieldBool 2 msg.scheduleStatePaused)
    <> (if msg.scheduleStateLimitedactions == False then mempty else encodeFieldBool 3 msg.scheduleStateLimitedactions)
    <> (if msg.scheduleStateRemainingactions == 0 then mempty else encodeFieldVarint 4 (fromIntegral msg.scheduleStateRemainingactions))

instance MessageSize ScheduleState where
  messageSize msg =
    (if msg.scheduleStateNotes == T.empty then 0 else fieldTextSize 1 msg.scheduleStateNotes)
    + (if msg.scheduleStatePaused == False then 0 else fieldBoolSize 2)
    + (if msg.scheduleStateLimitedactions == False then 0 else fieldBoolSize 3)
    + (if msg.scheduleStateRemainingactions == 0 then 0 else fieldVarintSize 4 (fromIntegral msg.scheduleStateRemainingactions))

instance MessageDecode ScheduleState where
  messageDecoder = loop "" False False 0
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (ScheduleState {scheduleStateNotes = acc_0, scheduleStatePaused = acc_1, scheduleStateLimitedactions = acc_2, scheduleStateRemainingactions = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldBool
              loop acc_0 v acc_2 acc_3
            3 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 v acc_3
            4 -> do
              v <- fromIntegral <$> decodeFieldVarint
              loop acc_0 acc_1 acc_2 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON ScheduleState where
  protoToJSON msg = jsonObject
      [ "notes" .= msg.scheduleStateNotes
      , "paused" .= msg.scheduleStatePaused
      , "limitedActions" .= msg.scheduleStateLimitedactions
      , "remainingActions" .= msg.scheduleStateRemainingactions
      ]

instance ProtoFromJSON ScheduleState where
  protoFromJSON (JsonObject obj) = do
    v_scheduleStateNotes <- obj .:? "notes"
    v_scheduleStatePaused <- obj .:? "paused"
    v_scheduleStateLimitedactions <- obj .:? "limitedActions"
    v_scheduleStateRemainingactions <- obj .:? "remainingActions"
    pure (ScheduleState {
       scheduleStateNotes = v_scheduleStateNotes
      , scheduleStatePaused = v_scheduleStatePaused
      , scheduleStateLimitedactions = v_scheduleStateLimitedactions
      , scheduleStateRemainingactions = v_scheduleStateRemainingactions
    })
  protoFromJSON _ = Left "Expected JSON object"

data TriggerImmediatelyRequest = TriggerImmediatelyRequest
  { triggerImmediatelyRequestOverlappolicy :: !ScheduleOverlapPolicy
  , triggerImmediatelyRequestScheduledtime :: !(Maybe Timestamp)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultTriggerImmediatelyRequest :: TriggerImmediatelyRequest
defaultTriggerImmediatelyRequest = TriggerImmediatelyRequest
  { triggerImmediatelyRequestOverlappolicy = (toEnum 0)
  , triggerImmediatelyRequestScheduledtime = Nothing
  }

instance MessageEncode TriggerImmediatelyRequest where
  buildMessage msg =
    (if fromEnum msg.triggerImmediatelyRequestOverlappolicy == 0 then mempty else encodeFieldVarint 1 (fromIntegral (fromEnum msg.triggerImmediatelyRequestOverlappolicy)))
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.triggerImmediatelyRequestScheduledtime)

instance MessageSize TriggerImmediatelyRequest where
  messageSize msg =
    (if fromEnum msg.triggerImmediatelyRequestOverlappolicy == 0 then 0 else fieldVarintSize 1 (fromIntegral (fromEnum msg.triggerImmediatelyRequestOverlappolicy)))
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.triggerImmediatelyRequestScheduledtime)

instance MessageDecode TriggerImmediatelyRequest where
  messageDecoder = loop (toEnum 0) Nothing
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (TriggerImmediatelyRequest {triggerImmediatelyRequestOverlappolicy = acc_0, triggerImmediatelyRequestScheduledtime = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldEnum
              loop v acc_1
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v)
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON TriggerImmediatelyRequest where
  protoToJSON msg = jsonObject
      [ "overlapPolicy" .= msg.triggerImmediatelyRequestOverlappolicy
      , "scheduledTime" .= msg.triggerImmediatelyRequestScheduledtime
      ]

instance ProtoFromJSON TriggerImmediatelyRequest where
  protoFromJSON (JsonObject obj) = do
    v_triggerImmediatelyRequestOverlappolicy <- obj .:? "overlapPolicy"
    v_triggerImmediatelyRequestScheduledtime <- obj .:? "scheduledTime"
    pure (TriggerImmediatelyRequest {
       triggerImmediatelyRequestOverlappolicy = v_triggerImmediatelyRequestOverlappolicy
      , triggerImmediatelyRequestScheduledtime = v_triggerImmediatelyRequestScheduledtime
    })
  protoFromJSON _ = Left "Expected JSON object"

data BackfillRequest = BackfillRequest
  { backfillRequestStarttime :: !(Maybe Timestamp)
  , backfillRequestEndtime :: !(Maybe Timestamp)
  , backfillRequestOverlappolicy :: !ScheduleOverlapPolicy
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBackfillRequest :: BackfillRequest
defaultBackfillRequest = BackfillRequest
  { backfillRequestStarttime = Nothing
  , backfillRequestEndtime = Nothing
  , backfillRequestOverlappolicy = (toEnum 0)
  }

instance MessageEncode BackfillRequest where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.backfillRequestStarttime)
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.backfillRequestEndtime)
    <> (if fromEnum msg.backfillRequestOverlappolicy == 0 then mempty else encodeFieldVarint 3 (fromIntegral (fromEnum msg.backfillRequestOverlappolicy)))

instance MessageSize BackfillRequest where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.backfillRequestStarttime)
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.backfillRequestEndtime)
    + (if fromEnum msg.backfillRequestOverlappolicy == 0 then 0 else fieldVarintSize 3 (fromIntegral (fromEnum msg.backfillRequestOverlappolicy)))

instance MessageDecode BackfillRequest where
  messageDecoder = loop Nothing Nothing (toEnum 0)
    where
      loop acc_0 acc_1 acc_2 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BackfillRequest {backfillRequestStarttime = acc_0, backfillRequestEndtime = acc_1, backfillRequestOverlappolicy = acc_2})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v) acc_1 acc_2
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2
            3 -> do
              v <- decodeFieldEnum
              loop acc_0 acc_1 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2

instance ProtoToJSON BackfillRequest where
  protoToJSON msg = jsonObject
      [ "startTime" .= msg.backfillRequestStarttime
      , "endTime" .= msg.backfillRequestEndtime
      , "overlapPolicy" .= msg.backfillRequestOverlappolicy
      ]

instance ProtoFromJSON BackfillRequest where
  protoFromJSON (JsonObject obj) = do
    v_backfillRequestStarttime <- obj .:? "startTime"
    v_backfillRequestEndtime <- obj .:? "endTime"
    v_backfillRequestOverlappolicy <- obj .:? "overlapPolicy"
    pure (BackfillRequest {
       backfillRequestStarttime = v_backfillRequestStarttime
      , backfillRequestEndtime = v_backfillRequestEndtime
      , backfillRequestOverlappolicy = v_backfillRequestOverlappolicy
    })
  protoFromJSON _ = Left "Expected JSON object"

data SchedulePatch = SchedulePatch
  { schedulePatchTriggerimmediately :: !(Maybe TriggerImmediatelyRequest)
  , schedulePatchBackfillrequest :: !(V.Vector BackfillRequest)
  , schedulePatchPause :: !Text
  , schedulePatchUnpause :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultSchedulePatch :: SchedulePatch
defaultSchedulePatch = SchedulePatch
  { schedulePatchTriggerimmediately = Nothing
  , schedulePatchBackfillrequest = V.empty
  , schedulePatchPause = ""
  , schedulePatchUnpause = ""
  }

instance MessageEncode SchedulePatch where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.schedulePatchTriggerimmediately)
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 2 v) mempty msg.schedulePatchBackfillrequest
    <> (if msg.schedulePatchPause == T.empty then mempty else encodeFieldString 3 msg.schedulePatchPause)
    <> (if msg.schedulePatchUnpause == T.empty then mempty else encodeFieldString 4 msg.schedulePatchUnpause)

instance MessageSize SchedulePatch where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.schedulePatchTriggerimmediately)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 2 (messageSize v)) 0 msg.schedulePatchBackfillrequest)
    + (if msg.schedulePatchPause == T.empty then 0 else fieldTextSize 3 msg.schedulePatchPause)
    + (if msg.schedulePatchUnpause == T.empty then 0 else fieldTextSize 4 msg.schedulePatchUnpause)

instance MessageDecode SchedulePatch where
  messageDecoder = loop Nothing V.empty "" ""
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (SchedulePatch {schedulePatchTriggerimmediately = acc_0, schedulePatchBackfillrequest = acc_1, schedulePatchPause = acc_2, schedulePatchUnpause = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v) acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (acc_1 <> V.singleton v) acc_2 acc_3
            3 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 v acc_3
            4 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON SchedulePatch where
  protoToJSON msg = jsonObject
      [ "triggerImmediately" .= msg.schedulePatchTriggerimmediately
      , "backfillRequest" .= msg.schedulePatchBackfillrequest
      , "pause" .= msg.schedulePatchPause
      , "unpause" .= msg.schedulePatchUnpause
      ]

instance ProtoFromJSON SchedulePatch where
  protoFromJSON (JsonObject obj) = do
    v_schedulePatchTriggerimmediately <- obj .:? "triggerImmediately"
    v_schedulePatchBackfillrequest <- obj .:? "backfillRequest"
    v_schedulePatchPause <- obj .:? "pause"
    v_schedulePatchUnpause <- obj .:? "unpause"
    pure (SchedulePatch {
       schedulePatchTriggerimmediately = v_schedulePatchTriggerimmediately
      , schedulePatchBackfillrequest = v_schedulePatchBackfillrequest
      , schedulePatchPause = v_schedulePatchPause
      , schedulePatchUnpause = v_schedulePatchUnpause
    })
  protoFromJSON _ = Left "Expected JSON object"

data ScheduleInfo = ScheduleInfo
  { scheduleInfoActioncount :: {-# UNPACK #-} !Int64
  , scheduleInfoMissedcatchupwindow :: {-# UNPACK #-} !Int64
  , scheduleInfoOverlapskipped :: {-# UNPACK #-} !Int64
  , scheduleInfoBufferdropped :: {-# UNPACK #-} !Int64
  , scheduleInfoBuffersize :: {-# UNPACK #-} !Int64
  , scheduleInfoRunningworkflows :: !(V.Vector WorkflowExecution)
  , scheduleInfoRecentactions :: !(V.Vector ScheduleActionResult)
  , scheduleInfoFutureactiontimes :: !(V.Vector Timestamp)
  , scheduleInfoCreatetime :: !(Maybe Timestamp)
  , scheduleInfoUpdatetime :: !(Maybe Timestamp)
  , scheduleInfoInvalidscheduleerror :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultScheduleInfo :: ScheduleInfo
defaultScheduleInfo = ScheduleInfo
  { scheduleInfoActioncount = 0
  , scheduleInfoMissedcatchupwindow = 0
  , scheduleInfoOverlapskipped = 0
  , scheduleInfoBufferdropped = 0
  , scheduleInfoBuffersize = 0
  , scheduleInfoRunningworkflows = V.empty
  , scheduleInfoRecentactions = V.empty
  , scheduleInfoFutureactiontimes = V.empty
  , scheduleInfoCreatetime = Nothing
  , scheduleInfoUpdatetime = Nothing
  , scheduleInfoInvalidscheduleerror = ""
  }

instance MessageEncode ScheduleInfo where
  buildMessage msg =
    (if msg.scheduleInfoActioncount == 0 then mempty else encodeFieldVarint 1 (fromIntegral msg.scheduleInfoActioncount))
    <> (if msg.scheduleInfoMissedcatchupwindow == 0 then mempty else encodeFieldVarint 2 (fromIntegral msg.scheduleInfoMissedcatchupwindow))
    <> (if msg.scheduleInfoOverlapskipped == 0 then mempty else encodeFieldVarint 3 (fromIntegral msg.scheduleInfoOverlapskipped))
    <> (if msg.scheduleInfoBufferdropped == 0 then mempty else encodeFieldVarint 10 (fromIntegral msg.scheduleInfoBufferdropped))
    <> (if msg.scheduleInfoBuffersize == 0 then mempty else encodeFieldVarint 11 (fromIntegral msg.scheduleInfoBuffersize))
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 9 v) mempty msg.scheduleInfoRunningworkflows
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 4 v) mempty msg.scheduleInfoRecentactions
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 5 v) mempty msg.scheduleInfoFutureactiontimes
    <> (maybe mempty (\v -> encodeFieldMessage 6 v) msg.scheduleInfoCreatetime)
    <> (maybe mempty (\v -> encodeFieldMessage 7 v) msg.scheduleInfoUpdatetime)
    <> (if msg.scheduleInfoInvalidscheduleerror == T.empty then mempty else encodeFieldString 8 msg.scheduleInfoInvalidscheduleerror)

instance MessageSize ScheduleInfo where
  messageSize msg =
    (if msg.scheduleInfoActioncount == 0 then 0 else fieldVarintSize 1 (fromIntegral msg.scheduleInfoActioncount))
    + (if msg.scheduleInfoMissedcatchupwindow == 0 then 0 else fieldVarintSize 2 (fromIntegral msg.scheduleInfoMissedcatchupwindow))
    + (if msg.scheduleInfoOverlapskipped == 0 then 0 else fieldVarintSize 3 (fromIntegral msg.scheduleInfoOverlapskipped))
    + (if msg.scheduleInfoBufferdropped == 0 then 0 else fieldVarintSize 10 (fromIntegral msg.scheduleInfoBufferdropped))
    + (if msg.scheduleInfoBuffersize == 0 then 0 else fieldVarintSize 11 (fromIntegral msg.scheduleInfoBuffersize))
    + (V.foldl' (\acc v -> acc + fieldMessageSize 9 (messageSize v)) 0 msg.scheduleInfoRunningworkflows)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 4 (messageSize v)) 0 msg.scheduleInfoRecentactions)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 5 (messageSize v)) 0 msg.scheduleInfoFutureactiontimes)
    + (maybe 0 (\v -> fieldMessageSize 6 (messageSize v)) msg.scheduleInfoCreatetime)
    + (maybe 0 (\v -> fieldMessageSize 7 (messageSize v)) msg.scheduleInfoUpdatetime)
    + (if msg.scheduleInfoInvalidscheduleerror == T.empty then 0 else fieldTextSize 8 msg.scheduleInfoInvalidscheduleerror)

instance MessageDecode ScheduleInfo where
  messageDecoder = loop 0 0 0 0 0 V.empty V.empty V.empty Nothing Nothing ""
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (ScheduleInfo {scheduleInfoActioncount = acc_0, scheduleInfoMissedcatchupwindow = acc_1, scheduleInfoOverlapskipped = acc_2, scheduleInfoBufferdropped = acc_3, scheduleInfoBuffersize = acc_4, scheduleInfoRunningworkflows = acc_5, scheduleInfoRecentactions = acc_6, scheduleInfoFutureactiontimes = acc_7, scheduleInfoCreatetime = acc_8, scheduleInfoUpdatetime = acc_9, scheduleInfoInvalidscheduleerror = acc_10})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- fromIntegral <$> decodeFieldVarint
              loop v acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10
            2 -> do
              v <- fromIntegral <$> decodeFieldVarint
              loop acc_0 v acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10
            3 -> do
              v <- fromIntegral <$> decodeFieldVarint
              loop acc_0 acc_1 v acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10
            10 -> do
              v <- fromIntegral <$> decodeFieldVarint
              loop acc_0 acc_1 acc_2 v acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10
            11 -> do
              v <- fromIntegral <$> decodeFieldVarint
              loop acc_0 acc_1 acc_2 acc_3 v acc_5 acc_6 acc_7 acc_8 acc_9 acc_10
            9 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 (acc_5 <> V.singleton v) acc_6 acc_7 acc_8 acc_9 acc_10
            4 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 (acc_6 <> V.singleton v) acc_7 acc_8 acc_9 acc_10
            5 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 (acc_7 <> V.singleton v) acc_8 acc_9 acc_10
            6 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 (Just v) acc_9 acc_10
            7 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 (Just v) acc_10
            8 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 acc_9 acc_10

instance ProtoToJSON ScheduleInfo where
  protoToJSON msg = jsonObject
      [ "actionCount" .= msg.scheduleInfoActioncount
      , "missedCatchupWindow" .= msg.scheduleInfoMissedcatchupwindow
      , "overlapSkipped" .= msg.scheduleInfoOverlapskipped
      , "bufferDropped" .= msg.scheduleInfoBufferdropped
      , "bufferSize" .= msg.scheduleInfoBuffersize
      , "runningWorkflows" .= msg.scheduleInfoRunningworkflows
      , "recentActions" .= msg.scheduleInfoRecentactions
      , "futureActionTimes" .= msg.scheduleInfoFutureactiontimes
      , "createTime" .= msg.scheduleInfoCreatetime
      , "updateTime" .= msg.scheduleInfoUpdatetime
      , "invalidScheduleError" .= msg.scheduleInfoInvalidscheduleerror
      ]

instance ProtoFromJSON ScheduleInfo where
  protoFromJSON (JsonObject obj) = do
    v_scheduleInfoActioncount <- obj .:? "actionCount"
    v_scheduleInfoMissedcatchupwindow <- obj .:? "missedCatchupWindow"
    v_scheduleInfoOverlapskipped <- obj .:? "overlapSkipped"
    v_scheduleInfoBufferdropped <- obj .:? "bufferDropped"
    v_scheduleInfoBuffersize <- obj .:? "bufferSize"
    v_scheduleInfoRunningworkflows <- obj .:? "runningWorkflows"
    v_scheduleInfoRecentactions <- obj .:? "recentActions"
    v_scheduleInfoFutureactiontimes <- obj .:? "futureActionTimes"
    v_scheduleInfoCreatetime <- obj .:? "createTime"
    v_scheduleInfoUpdatetime <- obj .:? "updateTime"
    v_scheduleInfoInvalidscheduleerror <- obj .:? "invalidScheduleError"
    pure (ScheduleInfo {
       scheduleInfoActioncount = v_scheduleInfoActioncount
      , scheduleInfoMissedcatchupwindow = v_scheduleInfoMissedcatchupwindow
      , scheduleInfoOverlapskipped = v_scheduleInfoOverlapskipped
      , scheduleInfoBufferdropped = v_scheduleInfoBufferdropped
      , scheduleInfoBuffersize = v_scheduleInfoBuffersize
      , scheduleInfoRunningworkflows = v_scheduleInfoRunningworkflows
      , scheduleInfoRecentactions = v_scheduleInfoRecentactions
      , scheduleInfoFutureactiontimes = v_scheduleInfoFutureactiontimes
      , scheduleInfoCreatetime = v_scheduleInfoCreatetime
      , scheduleInfoUpdatetime = v_scheduleInfoUpdatetime
      , scheduleInfoInvalidscheduleerror = v_scheduleInfoInvalidscheduleerror
    })
  protoFromJSON _ = Left "Expected JSON object"

data Schedule = Schedule
  { scheduleSpec :: !(Maybe ScheduleSpec)
  , scheduleAction :: !(Maybe ScheduleAction)
  , schedulePolicies :: !(Maybe SchedulePolicies)
  , scheduleState :: !(Maybe ScheduleState)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultSchedule :: Schedule
defaultSchedule = Schedule
  { scheduleSpec = Nothing
  , scheduleAction = Nothing
  , schedulePolicies = Nothing
  , scheduleState = Nothing
  }

instance MessageEncode Schedule where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.scheduleSpec)
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.scheduleAction)
    <> (maybe mempty (\v -> encodeFieldMessage 3 v) msg.schedulePolicies)
    <> (maybe mempty (\v -> encodeFieldMessage 4 v) msg.scheduleState)

instance MessageSize Schedule where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.scheduleSpec)
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.scheduleAction)
    + (maybe 0 (\v -> fieldMessageSize 3 (messageSize v)) msg.schedulePolicies)
    + (maybe 0 (\v -> fieldMessageSize 4 (messageSize v)) msg.scheduleState)

instance MessageDecode Schedule where
  messageDecoder = loop Nothing Nothing Nothing Nothing
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (Schedule {scheduleSpec = acc_0, scheduleAction = acc_1, schedulePolicies = acc_2, scheduleState = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v) acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2 acc_3
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (Just v) acc_3
            4 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 (Just v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON Schedule where
  protoToJSON msg = jsonObject
      [ "spec" .= msg.scheduleSpec
      , "action" .= msg.scheduleAction
      , "policies" .= msg.schedulePolicies
      , "state" .= msg.scheduleState
      ]

instance ProtoFromJSON Schedule where
  protoFromJSON (JsonObject obj) = do
    v_scheduleSpec <- obj .:? "spec"
    v_scheduleAction <- obj .:? "action"
    v_schedulePolicies <- obj .:? "policies"
    v_scheduleState <- obj .:? "state"
    pure (Schedule {
       scheduleSpec = v_scheduleSpec
      , scheduleAction = v_scheduleAction
      , schedulePolicies = v_schedulePolicies
      , scheduleState = v_scheduleState
    })
  protoFromJSON _ = Left "Expected JSON object"

data ScheduleListInfo = ScheduleListInfo
  { scheduleListInfoSpec :: !(Maybe ScheduleSpec)
  , scheduleListInfoWorkflowtype :: !(Maybe WorkflowType)
  , scheduleListInfoNotes :: !Text
  , scheduleListInfoPaused :: {-# UNPACK #-} !Bool
  , scheduleListInfoRecentactions :: !(V.Vector ScheduleActionResult)
  , scheduleListInfoFutureactiontimes :: !(V.Vector Timestamp)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultScheduleListInfo :: ScheduleListInfo
defaultScheduleListInfo = ScheduleListInfo
  { scheduleListInfoSpec = Nothing
  , scheduleListInfoWorkflowtype = Nothing
  , scheduleListInfoNotes = ""
  , scheduleListInfoPaused = False
  , scheduleListInfoRecentactions = V.empty
  , scheduleListInfoFutureactiontimes = V.empty
  }

instance MessageEncode ScheduleListInfo where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.scheduleListInfoSpec)
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.scheduleListInfoWorkflowtype)
    <> (if msg.scheduleListInfoNotes == T.empty then mempty else encodeFieldString 3 msg.scheduleListInfoNotes)
    <> (if msg.scheduleListInfoPaused == False then mempty else encodeFieldBool 4 msg.scheduleListInfoPaused)
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 5 v) mempty msg.scheduleListInfoRecentactions
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 6 v) mempty msg.scheduleListInfoFutureactiontimes

instance MessageSize ScheduleListInfo where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.scheduleListInfoSpec)
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.scheduleListInfoWorkflowtype)
    + (if msg.scheduleListInfoNotes == T.empty then 0 else fieldTextSize 3 msg.scheduleListInfoNotes)
    + (if msg.scheduleListInfoPaused == False then 0 else fieldBoolSize 4)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 5 (messageSize v)) 0 msg.scheduleListInfoRecentactions)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 6 (messageSize v)) 0 msg.scheduleListInfoFutureactiontimes)

instance MessageDecode ScheduleListInfo where
  messageDecoder = loop Nothing Nothing "" False V.empty V.empty
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (ScheduleListInfo {scheduleListInfoSpec = acc_0, scheduleListInfoWorkflowtype = acc_1, scheduleListInfoNotes = acc_2, scheduleListInfoPaused = acc_3, scheduleListInfoRecentactions = acc_4, scheduleListInfoFutureactiontimes = acc_5})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v) acc_1 acc_2 acc_3 acc_4 acc_5
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2 acc_3 acc_4 acc_5
            3 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 v acc_3 acc_4 acc_5
            4 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 v acc_4 acc_5
            5 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 (acc_4 <> V.singleton v) acc_5
            6 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 (acc_5 <> V.singleton v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5

instance ProtoToJSON ScheduleListInfo where
  protoToJSON msg = jsonObject
      [ "spec" .= msg.scheduleListInfoSpec
      , "workflowType" .= msg.scheduleListInfoWorkflowtype
      , "notes" .= msg.scheduleListInfoNotes
      , "paused" .= msg.scheduleListInfoPaused
      , "recentActions" .= msg.scheduleListInfoRecentactions
      , "futureActionTimes" .= msg.scheduleListInfoFutureactiontimes
      ]

instance ProtoFromJSON ScheduleListInfo where
  protoFromJSON (JsonObject obj) = do
    v_scheduleListInfoSpec <- obj .:? "spec"
    v_scheduleListInfoWorkflowtype <- obj .:? "workflowType"
    v_scheduleListInfoNotes <- obj .:? "notes"
    v_scheduleListInfoPaused <- obj .:? "paused"
    v_scheduleListInfoRecentactions <- obj .:? "recentActions"
    v_scheduleListInfoFutureactiontimes <- obj .:? "futureActionTimes"
    pure (ScheduleListInfo {
       scheduleListInfoSpec = v_scheduleListInfoSpec
      , scheduleListInfoWorkflowtype = v_scheduleListInfoWorkflowtype
      , scheduleListInfoNotes = v_scheduleListInfoNotes
      , scheduleListInfoPaused = v_scheduleListInfoPaused
      , scheduleListInfoRecentactions = v_scheduleListInfoRecentactions
      , scheduleListInfoFutureactiontimes = v_scheduleListInfoFutureactiontimes
    })
  protoFromJSON _ = Left "Expected JSON object"

data ScheduleListEntry = ScheduleListEntry
  { scheduleListEntryScheduleid :: !Text
  , scheduleListEntryMemo :: !(Maybe Memo)
  , scheduleListEntrySearchattributes :: !(Maybe SearchAttributes)
  , scheduleListEntryInfo :: !(Maybe ScheduleListInfo)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultScheduleListEntry :: ScheduleListEntry
defaultScheduleListEntry = ScheduleListEntry
  { scheduleListEntryScheduleid = ""
  , scheduleListEntryMemo = Nothing
  , scheduleListEntrySearchattributes = Nothing
  , scheduleListEntryInfo = Nothing
  }

instance MessageEncode ScheduleListEntry where
  buildMessage msg =
    (if msg.scheduleListEntryScheduleid == T.empty then mempty else encodeFieldString 1 msg.scheduleListEntryScheduleid)
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.scheduleListEntryMemo)
    <> (maybe mempty (\v -> encodeFieldMessage 3 v) msg.scheduleListEntrySearchattributes)
    <> (maybe mempty (\v -> encodeFieldMessage 4 v) msg.scheduleListEntryInfo)

instance MessageSize ScheduleListEntry where
  messageSize msg =
    (if msg.scheduleListEntryScheduleid == T.empty then 0 else fieldTextSize 1 msg.scheduleListEntryScheduleid)
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.scheduleListEntryMemo)
    + (maybe 0 (\v -> fieldMessageSize 3 (messageSize v)) msg.scheduleListEntrySearchattributes)
    + (maybe 0 (\v -> fieldMessageSize 4 (messageSize v)) msg.scheduleListEntryInfo)

instance MessageDecode ScheduleListEntry where
  messageDecoder = loop "" Nothing Nothing Nothing
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (ScheduleListEntry {scheduleListEntryScheduleid = acc_0, scheduleListEntryMemo = acc_1, scheduleListEntrySearchattributes = acc_2, scheduleListEntryInfo = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2 acc_3
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (Just v) acc_3
            4 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 (Just v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON ScheduleListEntry where
  protoToJSON msg = jsonObject
      [ "scheduleId" .= msg.scheduleListEntryScheduleid
      , "memo" .= msg.scheduleListEntryMemo
      , "searchAttributes" .= msg.scheduleListEntrySearchattributes
      , "info" .= msg.scheduleListEntryInfo
      ]

instance ProtoFromJSON ScheduleListEntry where
  protoFromJSON (JsonObject obj) = do
    v_scheduleListEntryScheduleid <- obj .:? "scheduleId"
    v_scheduleListEntryMemo <- obj .:? "memo"
    v_scheduleListEntrySearchattributes <- obj .:? "searchAttributes"
    v_scheduleListEntryInfo <- obj .:? "info"
    pure (ScheduleListEntry {
       scheduleListEntryScheduleid = v_scheduleListEntryScheduleid
      , scheduleListEntryMemo = v_scheduleListEntryMemo
      , scheduleListEntrySearchattributes = v_scheduleListEntrySearchattributes
      , scheduleListEntryInfo = v_scheduleListEntryInfo
    })
  protoFromJSON _ = Left "Expected JSON object"