{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.replication.v1@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Temporal.Temporal.Api.Replication.V1.Message where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Proto.Encode
import Proto.Decode
import Proto.JSON
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize)
import Proto.Google.Protobuf.Timestamp hiding (ClusterReplicationConfig, FailoverStatus, NamespaceReplicationConfig)
import Proto.Temporal.Temporal.Api.Enums.V1.Namespace hiding (ClusterReplicationConfig, FailoverStatus, NamespaceReplicationConfig)


data ClusterReplicationConfig = ClusterReplicationConfig
  { clusterReplicationConfigClustername :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultClusterReplicationConfig :: ClusterReplicationConfig
defaultClusterReplicationConfig = ClusterReplicationConfig
  { clusterReplicationConfigClustername = ""
  }

instance MessageEncode ClusterReplicationConfig where
  buildMessage msg =
    (if msg.clusterReplicationConfigClustername == T.empty then mempty else encodeFieldString 1 msg.clusterReplicationConfigClustername)

instance MessageSize ClusterReplicationConfig where
  messageSize msg =
    (if msg.clusterReplicationConfigClustername == T.empty then 0 else fieldTextSize 1 msg.clusterReplicationConfigClustername)

instance MessageDecode ClusterReplicationConfig where
  messageDecoder = loop ""
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (ClusterReplicationConfig {clusterReplicationConfigClustername = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON ClusterReplicationConfig where
  protoToJSON msg = jsonObject
      [ "clusterName" .= msg.clusterReplicationConfigClustername

      ]

instance ProtoFromJSON ClusterReplicationConfig where
  protoFromJSON _ = Right defaultClusterReplicationConfig

data NamespaceReplicationConfig = NamespaceReplicationConfig
  { namespaceReplicationConfigActiveclustername :: !Text
  , namespaceReplicationConfigClusters :: !(V.Vector ClusterReplicationConfig)
  , namespaceReplicationConfigState :: !ReplicationState
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultNamespaceReplicationConfig :: NamespaceReplicationConfig
defaultNamespaceReplicationConfig = NamespaceReplicationConfig
  { namespaceReplicationConfigActiveclustername = ""
  , namespaceReplicationConfigClusters = V.empty
  , namespaceReplicationConfigState = (toEnum 0)
  }

instance MessageEncode NamespaceReplicationConfig where
  buildMessage msg =
    (if msg.namespaceReplicationConfigActiveclustername == T.empty then mempty else encodeFieldString 1 msg.namespaceReplicationConfigActiveclustername)
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 2 v) mempty msg.namespaceReplicationConfigClusters
    <> (if fromEnum msg.namespaceReplicationConfigState == 0 then mempty else encodeFieldVarint 3 (fromIntegral (fromEnum msg.namespaceReplicationConfigState)))

instance MessageSize NamespaceReplicationConfig where
  messageSize msg =
    (if msg.namespaceReplicationConfigActiveclustername == T.empty then 0 else fieldTextSize 1 msg.namespaceReplicationConfigActiveclustername)
    + (V.foldl' (\acc v -> acc + fieldMessageSize 2 (messageSize v)) 0 msg.namespaceReplicationConfigClusters)
    + (if fromEnum msg.namespaceReplicationConfigState == 0 then 0 else fieldVarintSize 3 (fromIntegral (fromEnum msg.namespaceReplicationConfigState)))

instance MessageDecode NamespaceReplicationConfig where
  messageDecoder = loop "" V.empty (toEnum 0)
    where
      loop acc_0 acc_1 acc_2 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (NamespaceReplicationConfig {namespaceReplicationConfigActiveclustername = acc_0, namespaceReplicationConfigClusters = acc_1, namespaceReplicationConfigState = acc_2})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (acc_1 <> V.singleton v) acc_2
            3 -> do
              v <- decodeFieldEnum
              loop acc_0 acc_1 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2

instance ProtoToJSON NamespaceReplicationConfig where
  protoToJSON msg = jsonObject
      [ "activeClusterName" .= msg.namespaceReplicationConfigActiveclustername
      , "clusters" .= msg.namespaceReplicationConfigClusters
      , "state" .= msg.namespaceReplicationConfigState
      ]

instance ProtoFromJSON NamespaceReplicationConfig where
  protoFromJSON _ = Right defaultNamespaceReplicationConfig

data FailoverStatus = FailoverStatus
  { failoverStatusFailovertime :: !(Maybe Timestamp)
  , failoverStatusFailoverversion :: {-# UNPACK #-} !Int64
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultFailoverStatus :: FailoverStatus
defaultFailoverStatus = FailoverStatus
  { failoverStatusFailovertime = Nothing
  , failoverStatusFailoverversion = 0
  }

instance MessageEncode FailoverStatus where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.failoverStatusFailovertime)
    <> (if msg.failoverStatusFailoverversion == 0 then mempty else encodeFieldVarint 2 (fromIntegral msg.failoverStatusFailoverversion))

instance MessageSize FailoverStatus where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.failoverStatusFailovertime)
    + (if msg.failoverStatusFailoverversion == 0 then 0 else fieldVarintSize 2 (fromIntegral msg.failoverStatusFailoverversion))

instance MessageDecode FailoverStatus where
  messageDecoder = loop Nothing 0
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (FailoverStatus {failoverStatusFailovertime = acc_0, failoverStatusFailoverversion = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v) acc_1
            2 -> do
              v <- fromIntegral <$> decodeFieldVarint
              loop acc_0 v
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON FailoverStatus where
  protoToJSON msg = jsonObject
      [ "failoverTime" .= msg.failoverStatusFailovertime
      , "failoverVersion" .= msg.failoverStatusFailoverversion
      ]

instance ProtoFromJSON FailoverStatus where
  protoFromJSON _ = Right defaultFailoverStatus