{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.enums.v1@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Temporalio.Api.Enums.V1.Schedule where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.JSON (jsonObject, (.=:), parseFieldMaybe)
import Data.Proxy (Proxy(..))
import Proto.Message (IsMessage(..))
import qualified Proto.Registry
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)


data ScheduleOverlapPolicy
  = ScheduleOverlapPolicy'ScheduleOverlapPolicyUnspecified
  | ScheduleOverlapPolicy'ScheduleOverlapPolicySkip
  | ScheduleOverlapPolicy'ScheduleOverlapPolicyBufferOne
  | ScheduleOverlapPolicy'ScheduleOverlapPolicyBufferAll
  | ScheduleOverlapPolicy'ScheduleOverlapPolicyCancelOther
  | ScheduleOverlapPolicy'ScheduleOverlapPolicyTerminateOther
  | ScheduleOverlapPolicy'ScheduleOverlapPolicyAllowAll
  deriving stock (Show, Eq, Ord, Enum, Bounded, Generic)
  deriving anyclass NFData

toProtoEnumScheduleOverlapPolicy :: ScheduleOverlapPolicy -> Int
toProtoEnumScheduleOverlapPolicy ScheduleOverlapPolicy'ScheduleOverlapPolicyUnspecified = 0
toProtoEnumScheduleOverlapPolicy ScheduleOverlapPolicy'ScheduleOverlapPolicySkip = 1
toProtoEnumScheduleOverlapPolicy ScheduleOverlapPolicy'ScheduleOverlapPolicyBufferOne = 2
toProtoEnumScheduleOverlapPolicy ScheduleOverlapPolicy'ScheduleOverlapPolicyBufferAll = 3
toProtoEnumScheduleOverlapPolicy ScheduleOverlapPolicy'ScheduleOverlapPolicyCancelOther = 4
toProtoEnumScheduleOverlapPolicy ScheduleOverlapPolicy'ScheduleOverlapPolicyTerminateOther = 5
toProtoEnumScheduleOverlapPolicy ScheduleOverlapPolicy'ScheduleOverlapPolicyAllowAll = 6

fromProtoEnumScheduleOverlapPolicy :: Int -> Maybe ScheduleOverlapPolicy
fromProtoEnumScheduleOverlapPolicy 0 = Just ScheduleOverlapPolicy'ScheduleOverlapPolicyUnspecified
fromProtoEnumScheduleOverlapPolicy 1 = Just ScheduleOverlapPolicy'ScheduleOverlapPolicySkip
fromProtoEnumScheduleOverlapPolicy 2 = Just ScheduleOverlapPolicy'ScheduleOverlapPolicyBufferOne
fromProtoEnumScheduleOverlapPolicy 3 = Just ScheduleOverlapPolicy'ScheduleOverlapPolicyBufferAll
fromProtoEnumScheduleOverlapPolicy 4 = Just ScheduleOverlapPolicy'ScheduleOverlapPolicyCancelOther
fromProtoEnumScheduleOverlapPolicy 5 = Just ScheduleOverlapPolicy'ScheduleOverlapPolicyTerminateOther
fromProtoEnumScheduleOverlapPolicy 6 = Just ScheduleOverlapPolicy'ScheduleOverlapPolicyAllowAll
fromProtoEnumScheduleOverlapPolicy _ = Nothing

instance MessageEncode ScheduleOverlapPolicy where
  buildMessage _ = mempty
instance MessageSize ScheduleOverlapPolicy where
  messageSize _ = 0
instance MessageDecode ScheduleOverlapPolicy where
  messageDecoder = pure (toEnum 0)

instance Aeson.ToJSON ScheduleOverlapPolicy where
  toJSON ScheduleOverlapPolicy'ScheduleOverlapPolicyUnspecified = Aeson.String "SCHEDULE_OVERLAP_POLICY_UNSPECIFIED"
  toJSON ScheduleOverlapPolicy'ScheduleOverlapPolicySkip = Aeson.String "SCHEDULE_OVERLAP_POLICY_SKIP"
  toJSON ScheduleOverlapPolicy'ScheduleOverlapPolicyBufferOne = Aeson.String "SCHEDULE_OVERLAP_POLICY_BUFFER_ONE"
  toJSON ScheduleOverlapPolicy'ScheduleOverlapPolicyBufferAll = Aeson.String "SCHEDULE_OVERLAP_POLICY_BUFFER_ALL"
  toJSON ScheduleOverlapPolicy'ScheduleOverlapPolicyCancelOther = Aeson.String "SCHEDULE_OVERLAP_POLICY_CANCEL_OTHER"
  toJSON ScheduleOverlapPolicy'ScheduleOverlapPolicyTerminateOther = Aeson.String "SCHEDULE_OVERLAP_POLICY_TERMINATE_OTHER"
  toJSON ScheduleOverlapPolicy'ScheduleOverlapPolicyAllowAll = Aeson.String "SCHEDULE_OVERLAP_POLICY_ALLOW_ALL"

instance Aeson.FromJSON ScheduleOverlapPolicy where
  parseJSON = \case
    Aeson.String "SCHEDULE_OVERLAP_POLICY_UNSPECIFIED" -> pure ScheduleOverlapPolicy'ScheduleOverlapPolicyUnspecified
    Aeson.String "SCHEDULE_OVERLAP_POLICY_SKIP" -> pure ScheduleOverlapPolicy'ScheduleOverlapPolicySkip
    Aeson.String "SCHEDULE_OVERLAP_POLICY_BUFFER_ONE" -> pure ScheduleOverlapPolicy'ScheduleOverlapPolicyBufferOne
    Aeson.String "SCHEDULE_OVERLAP_POLICY_BUFFER_ALL" -> pure ScheduleOverlapPolicy'ScheduleOverlapPolicyBufferAll
    Aeson.String "SCHEDULE_OVERLAP_POLICY_CANCEL_OTHER" -> pure ScheduleOverlapPolicy'ScheduleOverlapPolicyCancelOther
    Aeson.String "SCHEDULE_OVERLAP_POLICY_TERMINATE_OTHER" -> pure ScheduleOverlapPolicy'ScheduleOverlapPolicyTerminateOther
    Aeson.String "SCHEDULE_OVERLAP_POLICY_ALLOW_ALL" -> pure ScheduleOverlapPolicy'ScheduleOverlapPolicyAllowAll
    Aeson.Number n -> pure (toEnum (round n))
    _ -> fail "Invalid enum value for ScheduleOverlapPolicy"

