{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.enums.v1@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Temporalio.Api.Enums.V1.TaskQueue where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.JSON (jsonObject, (.=:), parseFieldMaybe)
import Data.Proxy (Proxy(..))
import Proto.Message (IsMessage(..))
import qualified Proto.Registry
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)


data TaskQueueKind
  = TaskQueueKind'TaskQueueKindUnspecified
  | TaskQueueKind'TaskQueueKindNormal
  | TaskQueueKind'TaskQueueKindSticky
  deriving stock (Show, Eq, Ord, Enum, Bounded, Generic)
  deriving anyclass NFData

toProtoEnumTaskQueueKind :: TaskQueueKind -> Int
toProtoEnumTaskQueueKind TaskQueueKind'TaskQueueKindUnspecified = 0
toProtoEnumTaskQueueKind TaskQueueKind'TaskQueueKindNormal = 1
toProtoEnumTaskQueueKind TaskQueueKind'TaskQueueKindSticky = 2

fromProtoEnumTaskQueueKind :: Int -> Maybe TaskQueueKind
fromProtoEnumTaskQueueKind 0 = Just TaskQueueKind'TaskQueueKindUnspecified
fromProtoEnumTaskQueueKind 1 = Just TaskQueueKind'TaskQueueKindNormal
fromProtoEnumTaskQueueKind 2 = Just TaskQueueKind'TaskQueueKindSticky
fromProtoEnumTaskQueueKind _ = Nothing

instance MessageEncode TaskQueueKind where
  buildMessage _ = mempty
instance MessageSize TaskQueueKind where
  messageSize _ = 0
instance MessageDecode TaskQueueKind where
  messageDecoder = pure (toEnum 0)

instance Aeson.ToJSON TaskQueueKind where
  toJSON TaskQueueKind'TaskQueueKindUnspecified = Aeson.String "TASK_QUEUE_KIND_UNSPECIFIED"
  toJSON TaskQueueKind'TaskQueueKindNormal = Aeson.String "TASK_QUEUE_KIND_NORMAL"
  toJSON TaskQueueKind'TaskQueueKindSticky = Aeson.String "TASK_QUEUE_KIND_STICKY"

instance Aeson.FromJSON TaskQueueKind where
  parseJSON = \case
    Aeson.String "TASK_QUEUE_KIND_UNSPECIFIED" -> pure TaskQueueKind'TaskQueueKindUnspecified
    Aeson.String "TASK_QUEUE_KIND_NORMAL" -> pure TaskQueueKind'TaskQueueKindNormal
    Aeson.String "TASK_QUEUE_KIND_STICKY" -> pure TaskQueueKind'TaskQueueKindSticky
    Aeson.Number n -> pure (toEnum (round n))
    _ -> fail "Invalid enum value for TaskQueueKind"

data TaskQueueType
  = TaskQueueType'TaskQueueTypeUnspecified
  | TaskQueueType'TaskQueueTypeWorkflow
  | TaskQueueType'TaskQueueTypeActivity
  | TaskQueueType'TaskQueueTypeNexus
  deriving stock (Show, Eq, Ord, Enum, Bounded, Generic)
  deriving anyclass NFData

toProtoEnumTaskQueueType :: TaskQueueType -> Int
toProtoEnumTaskQueueType TaskQueueType'TaskQueueTypeUnspecified = 0
toProtoEnumTaskQueueType TaskQueueType'TaskQueueTypeWorkflow = 1
toProtoEnumTaskQueueType TaskQueueType'TaskQueueTypeActivity = 2
toProtoEnumTaskQueueType TaskQueueType'TaskQueueTypeNexus = 3

fromProtoEnumTaskQueueType :: Int -> Maybe TaskQueueType
fromProtoEnumTaskQueueType 0 = Just TaskQueueType'TaskQueueTypeUnspecified
fromProtoEnumTaskQueueType 1 = Just TaskQueueType'TaskQueueTypeWorkflow
fromProtoEnumTaskQueueType 2 = Just TaskQueueType'TaskQueueTypeActivity
fromProtoEnumTaskQueueType 3 = Just TaskQueueType'TaskQueueTypeNexus
fromProtoEnumTaskQueueType _ = Nothing

instance MessageEncode TaskQueueType where
  buildMessage _ = mempty
instance MessageSize TaskQueueType where
  messageSize _ = 0
instance MessageDecode TaskQueueType where
  messageDecoder = pure (toEnum 0)

instance Aeson.ToJSON TaskQueueType where
  toJSON TaskQueueType'TaskQueueTypeUnspecified = Aeson.String "TASK_QUEUE_TYPE_UNSPECIFIED"
  toJSON TaskQueueType'TaskQueueTypeWorkflow = Aeson.String "TASK_QUEUE_TYPE_WORKFLOW"
  toJSON TaskQueueType'TaskQueueTypeActivity = Aeson.String "TASK_QUEUE_TYPE_ACTIVITY"
  toJSON TaskQueueType'TaskQueueTypeNexus = Aeson.String "TASK_QUEUE_TYPE_NEXUS"

instance Aeson.FromJSON TaskQueueType where
  parseJSON = \case
    Aeson.String "TASK_QUEUE_TYPE_UNSPECIFIED" -> pure TaskQueueType'TaskQueueTypeUnspecified
    Aeson.String "TASK_QUEUE_TYPE_WORKFLOW" -> pure TaskQueueType'TaskQueueTypeWorkflow
    Aeson.String "TASK_QUEUE_TYPE_ACTIVITY" -> pure TaskQueueType'TaskQueueTypeActivity
    Aeson.String "TASK_QUEUE_TYPE_NEXUS" -> pure TaskQueueType'TaskQueueTypeNexus
    Aeson.Number n -> pure (toEnum (round n))
    _ -> fail "Invalid enum value for TaskQueueType"

data TaskReachability
  = TaskReachability'TaskReachabilityUnspecified
  | TaskReachability'TaskReachabilityNewWorkflows
  | TaskReachability'TaskReachabilityExistingWorkflows
  | TaskReachability'TaskReachabilityOpenWorkflows
  | TaskReachability'TaskReachabilityClosedWorkflows
  deriving stock (Show, Eq, Ord, Enum, Bounded, Generic)
  deriving anyclass NFData

toProtoEnumTaskReachability :: TaskReachability -> Int
toProtoEnumTaskReachability TaskReachability'TaskReachabilityUnspecified = 0
toProtoEnumTaskReachability TaskReachability'TaskReachabilityNewWorkflows = 1
toProtoEnumTaskReachability TaskReachability'TaskReachabilityExistingWorkflows = 2
toProtoEnumTaskReachability TaskReachability'TaskReachabilityOpenWorkflows = 3
toProtoEnumTaskReachability TaskReachability'TaskReachabilityClosedWorkflows = 4

fromProtoEnumTaskReachability :: Int -> Maybe TaskReachability
fromProtoEnumTaskReachability 0 = Just TaskReachability'TaskReachabilityUnspecified
fromProtoEnumTaskReachability 1 = Just TaskReachability'TaskReachabilityNewWorkflows
fromProtoEnumTaskReachability 2 = Just TaskReachability'TaskReachabilityExistingWorkflows
fromProtoEnumTaskReachability 3 = Just TaskReachability'TaskReachabilityOpenWorkflows
fromProtoEnumTaskReachability 4 = Just TaskReachability'TaskReachabilityClosedWorkflows
fromProtoEnumTaskReachability _ = Nothing

instance MessageEncode TaskReachability where
  buildMessage _ = mempty
instance MessageSize TaskReachability where
  messageSize _ = 0
instance MessageDecode TaskReachability where
  messageDecoder = pure (toEnum 0)

instance Aeson.ToJSON TaskReachability where
  toJSON TaskReachability'TaskReachabilityUnspecified = Aeson.String "TASK_REACHABILITY_UNSPECIFIED"
  toJSON TaskReachability'TaskReachabilityNewWorkflows = Aeson.String "TASK_REACHABILITY_NEW_WORKFLOWS"
  toJSON TaskReachability'TaskReachabilityExistingWorkflows = Aeson.String "TASK_REACHABILITY_EXISTING_WORKFLOWS"
  toJSON TaskReachability'TaskReachabilityOpenWorkflows = Aeson.String "TASK_REACHABILITY_OPEN_WORKFLOWS"
  toJSON TaskReachability'TaskReachabilityClosedWorkflows = Aeson.String "TASK_REACHABILITY_CLOSED_WORKFLOWS"

instance Aeson.FromJSON TaskReachability where
  parseJSON = \case
    Aeson.String "TASK_REACHABILITY_UNSPECIFIED" -> pure TaskReachability'TaskReachabilityUnspecified
    Aeson.String "TASK_REACHABILITY_NEW_WORKFLOWS" -> pure TaskReachability'TaskReachabilityNewWorkflows
    Aeson.String "TASK_REACHABILITY_EXISTING_WORKFLOWS" -> pure TaskReachability'TaskReachabilityExistingWorkflows
    Aeson.String "TASK_REACHABILITY_OPEN_WORKFLOWS" -> pure TaskReachability'TaskReachabilityOpenWorkflows
    Aeson.String "TASK_REACHABILITY_CLOSED_WORKFLOWS" -> pure TaskReachability'TaskReachabilityClosedWorkflows
    Aeson.Number n -> pure (toEnum (round n))
    _ -> fail "Invalid enum value for TaskReachability"

data BuildIdTaskReachability
  = BuildIdTaskReachability'BuildIdTaskReachabilityUnspecified
  | BuildIdTaskReachability'BuildIdTaskReachabilityReachable
  | BuildIdTaskReachability'BuildIdTaskReachabilityClosedWorkflowsOnly
  | BuildIdTaskReachability'BuildIdTaskReachabilityUnreachable
  deriving stock (Show, Eq, Ord, Enum, Bounded, Generic)
  deriving anyclass NFData

toProtoEnumBuildIdTaskReachability :: BuildIdTaskReachability -> Int
toProtoEnumBuildIdTaskReachability BuildIdTaskReachability'BuildIdTaskReachabilityUnspecified = 0
toProtoEnumBuildIdTaskReachability BuildIdTaskReachability'BuildIdTaskReachabilityReachable = 1
toProtoEnumBuildIdTaskReachability BuildIdTaskReachability'BuildIdTaskReachabilityClosedWorkflowsOnly = 2
toProtoEnumBuildIdTaskReachability BuildIdTaskReachability'BuildIdTaskReachabilityUnreachable = 3

fromProtoEnumBuildIdTaskReachability :: Int -> Maybe BuildIdTaskReachability
fromProtoEnumBuildIdTaskReachability 0 = Just BuildIdTaskReachability'BuildIdTaskReachabilityUnspecified
fromProtoEnumBuildIdTaskReachability 1 = Just BuildIdTaskReachability'BuildIdTaskReachabilityReachable
fromProtoEnumBuildIdTaskReachability 2 = Just BuildIdTaskReachability'BuildIdTaskReachabilityClosedWorkflowsOnly
fromProtoEnumBuildIdTaskReachability 3 = Just BuildIdTaskReachability'BuildIdTaskReachabilityUnreachable
fromProtoEnumBuildIdTaskReachability _ = Nothing

instance MessageEncode BuildIdTaskReachability where
  buildMessage _ = mempty
instance MessageSize BuildIdTaskReachability where
  messageSize _ = 0
instance MessageDecode BuildIdTaskReachability where
  messageDecoder = pure (toEnum 0)

instance Aeson.ToJSON BuildIdTaskReachability where
  toJSON BuildIdTaskReachability'BuildIdTaskReachabilityUnspecified = Aeson.String "BUILD_ID_TASK_REACHABILITY_UNSPECIFIED"
  toJSON BuildIdTaskReachability'BuildIdTaskReachabilityReachable = Aeson.String "BUILD_ID_TASK_REACHABILITY_REACHABLE"
  toJSON BuildIdTaskReachability'BuildIdTaskReachabilityClosedWorkflowsOnly = Aeson.String "BUILD_ID_TASK_REACHABILITY_CLOSED_WORKFLOWS_ONLY"
  toJSON BuildIdTaskReachability'BuildIdTaskReachabilityUnreachable = Aeson.String "BUILD_ID_TASK_REACHABILITY_UNREACHABLE"

instance Aeson.FromJSON BuildIdTaskReachability where
  parseJSON = \case
    Aeson.String "BUILD_ID_TASK_REACHABILITY_UNSPECIFIED" -> pure BuildIdTaskReachability'BuildIdTaskReachabilityUnspecified
    Aeson.String "BUILD_ID_TASK_REACHABILITY_REACHABLE" -> pure BuildIdTaskReachability'BuildIdTaskReachabilityReachable
    Aeson.String "BUILD_ID_TASK_REACHABILITY_CLOSED_WORKFLOWS_ONLY" -> pure BuildIdTaskReachability'BuildIdTaskReachabilityClosedWorkflowsOnly
    Aeson.String "BUILD_ID_TASK_REACHABILITY_UNREACHABLE" -> pure BuildIdTaskReachability'BuildIdTaskReachabilityUnreachable
    Aeson.Number n -> pure (toEnum (round n))
    _ -> fail "Invalid enum value for BuildIdTaskReachability"

data DescribeTaskQueueMode
  = DescribeTaskQueueMode'DescribeTaskQueueModeUnspecified
  | DescribeTaskQueueMode'DescribeTaskQueueModeEnhanced
  deriving stock (Show, Eq, Ord, Enum, Bounded, Generic)
  deriving anyclass NFData

toProtoEnumDescribeTaskQueueMode :: DescribeTaskQueueMode -> Int
toProtoEnumDescribeTaskQueueMode DescribeTaskQueueMode'DescribeTaskQueueModeUnspecified = 0
toProtoEnumDescribeTaskQueueMode DescribeTaskQueueMode'DescribeTaskQueueModeEnhanced = 1

fromProtoEnumDescribeTaskQueueMode :: Int -> Maybe DescribeTaskQueueMode
fromProtoEnumDescribeTaskQueueMode 0 = Just DescribeTaskQueueMode'DescribeTaskQueueModeUnspecified
fromProtoEnumDescribeTaskQueueMode 1 = Just DescribeTaskQueueMode'DescribeTaskQueueModeEnhanced
fromProtoEnumDescribeTaskQueueMode _ = Nothing

instance MessageEncode DescribeTaskQueueMode where
  buildMessage _ = mempty
instance MessageSize DescribeTaskQueueMode where
  messageSize _ = 0
instance MessageDecode DescribeTaskQueueMode where
  messageDecoder = pure (toEnum 0)

instance Aeson.ToJSON DescribeTaskQueueMode where
  toJSON DescribeTaskQueueMode'DescribeTaskQueueModeUnspecified = Aeson.String "DESCRIBE_TASK_QUEUE_MODE_UNSPECIFIED"
  toJSON DescribeTaskQueueMode'DescribeTaskQueueModeEnhanced = Aeson.String "DESCRIBE_TASK_QUEUE_MODE_ENHANCED"

instance Aeson.FromJSON DescribeTaskQueueMode where
  parseJSON = \case
    Aeson.String "DESCRIBE_TASK_QUEUE_MODE_UNSPECIFIED" -> pure DescribeTaskQueueMode'DescribeTaskQueueModeUnspecified
    Aeson.String "DESCRIBE_TASK_QUEUE_MODE_ENHANCED" -> pure DescribeTaskQueueMode'DescribeTaskQueueModeEnhanced
    Aeson.Number n -> pure (toEnum (round n))
    _ -> fail "Invalid enum value for DescribeTaskQueueMode"

data RateLimitSource
  = RateLimitSource'RateLimitSourceUnspecified
  | RateLimitSource'RateLimitSourceApi
  | RateLimitSource'RateLimitSourceWorker
  | RateLimitSource'RateLimitSourceSystem
  deriving stock (Show, Eq, Ord, Enum, Bounded, Generic)
  deriving anyclass NFData

toProtoEnumRateLimitSource :: RateLimitSource -> Int
toProtoEnumRateLimitSource RateLimitSource'RateLimitSourceUnspecified = 0
toProtoEnumRateLimitSource RateLimitSource'RateLimitSourceApi = 1
toProtoEnumRateLimitSource RateLimitSource'RateLimitSourceWorker = 2
toProtoEnumRateLimitSource RateLimitSource'RateLimitSourceSystem = 3

fromProtoEnumRateLimitSource :: Int -> Maybe RateLimitSource
fromProtoEnumRateLimitSource 0 = Just RateLimitSource'RateLimitSourceUnspecified
fromProtoEnumRateLimitSource 1 = Just RateLimitSource'RateLimitSourceApi
fromProtoEnumRateLimitSource 2 = Just RateLimitSource'RateLimitSourceWorker
fromProtoEnumRateLimitSource 3 = Just RateLimitSource'RateLimitSourceSystem
fromProtoEnumRateLimitSource _ = Nothing

instance MessageEncode RateLimitSource where
  buildMessage _ = mempty
instance MessageSize RateLimitSource where
  messageSize _ = 0
instance MessageDecode RateLimitSource where
  messageDecoder = pure (toEnum 0)

instance Aeson.ToJSON RateLimitSource where
  toJSON RateLimitSource'RateLimitSourceUnspecified = Aeson.String "RATE_LIMIT_SOURCE_UNSPECIFIED"
  toJSON RateLimitSource'RateLimitSourceApi = Aeson.String "RATE_LIMIT_SOURCE_API"
  toJSON RateLimitSource'RateLimitSourceWorker = Aeson.String "RATE_LIMIT_SOURCE_WORKER"
  toJSON RateLimitSource'RateLimitSourceSystem = Aeson.String "RATE_LIMIT_SOURCE_SYSTEM"

instance Aeson.FromJSON RateLimitSource where
  parseJSON = \case
    Aeson.String "RATE_LIMIT_SOURCE_UNSPECIFIED" -> pure RateLimitSource'RateLimitSourceUnspecified
    Aeson.String "RATE_LIMIT_SOURCE_API" -> pure RateLimitSource'RateLimitSourceApi
    Aeson.String "RATE_LIMIT_SOURCE_WORKER" -> pure RateLimitSource'RateLimitSourceWorker
    Aeson.String "RATE_LIMIT_SOURCE_SYSTEM" -> pure RateLimitSource'RateLimitSourceSystem
    Aeson.Number n -> pure (toEnum (round n))
    _ -> fail "Invalid enum value for RateLimitSource"

data RoutingConfigUpdateState
  = RoutingConfigUpdateState'RoutingConfigUpdateStateUnspecified
  | RoutingConfigUpdateState'RoutingConfigUpdateStateInProgress
  | RoutingConfigUpdateState'RoutingConfigUpdateStateCompleted
  deriving stock (Show, Eq, Ord, Enum, Bounded, Generic)
  deriving anyclass NFData

toProtoEnumRoutingConfigUpdateState :: RoutingConfigUpdateState -> Int
toProtoEnumRoutingConfigUpdateState RoutingConfigUpdateState'RoutingConfigUpdateStateUnspecified = 0
toProtoEnumRoutingConfigUpdateState RoutingConfigUpdateState'RoutingConfigUpdateStateInProgress = 1
toProtoEnumRoutingConfigUpdateState RoutingConfigUpdateState'RoutingConfigUpdateStateCompleted = 2

fromProtoEnumRoutingConfigUpdateState :: Int -> Maybe RoutingConfigUpdateState
fromProtoEnumRoutingConfigUpdateState 0 = Just RoutingConfigUpdateState'RoutingConfigUpdateStateUnspecified
fromProtoEnumRoutingConfigUpdateState 1 = Just RoutingConfigUpdateState'RoutingConfigUpdateStateInProgress
fromProtoEnumRoutingConfigUpdateState 2 = Just RoutingConfigUpdateState'RoutingConfigUpdateStateCompleted
fromProtoEnumRoutingConfigUpdateState _ = Nothing

instance MessageEncode RoutingConfigUpdateState where
  buildMessage _ = mempty
instance MessageSize RoutingConfigUpdateState where
  messageSize _ = 0
instance MessageDecode RoutingConfigUpdateState where
  messageDecoder = pure (toEnum 0)

instance Aeson.ToJSON RoutingConfigUpdateState where
  toJSON RoutingConfigUpdateState'RoutingConfigUpdateStateUnspecified = Aeson.String "ROUTING_CONFIG_UPDATE_STATE_UNSPECIFIED"
  toJSON RoutingConfigUpdateState'RoutingConfigUpdateStateInProgress = Aeson.String "ROUTING_CONFIG_UPDATE_STATE_IN_PROGRESS"
  toJSON RoutingConfigUpdateState'RoutingConfigUpdateStateCompleted = Aeson.String "ROUTING_CONFIG_UPDATE_STATE_COMPLETED"

instance Aeson.FromJSON RoutingConfigUpdateState where
  parseJSON = \case
    Aeson.String "ROUTING_CONFIG_UPDATE_STATE_UNSPECIFIED" -> pure RoutingConfigUpdateState'RoutingConfigUpdateStateUnspecified
    Aeson.String "ROUTING_CONFIG_UPDATE_STATE_IN_PROGRESS" -> pure RoutingConfigUpdateState'RoutingConfigUpdateStateInProgress
    Aeson.String "ROUTING_CONFIG_UPDATE_STATE_COMPLETED" -> pure RoutingConfigUpdateState'RoutingConfigUpdateStateCompleted
    Aeson.Number n -> pure (toEnum (round n))
    _ -> fail "Invalid enum value for RoutingConfigUpdateState"

