{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.enums.v1@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Temporalio.Api.Enums.V1.Update where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.JSON (jsonObject, (.=:), parseFieldMaybe)
import Data.Proxy (Proxy(..))
import Proto.Message (IsMessage(..))
import qualified Proto.Registry
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)


data UpdateWorkflowExecutionLifecycleStage
  = UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageUnspecified
  | UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageAdmitted
  | UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageAccepted
  | UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageCompleted
  deriving stock (Show, Eq, Ord, Enum, Bounded, Generic)
  deriving anyclass NFData

toProtoEnumUpdateWorkflowExecutionLifecycleStage :: UpdateWorkflowExecutionLifecycleStage -> Int
toProtoEnumUpdateWorkflowExecutionLifecycleStage UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageUnspecified = 0
toProtoEnumUpdateWorkflowExecutionLifecycleStage UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageAdmitted = 1
toProtoEnumUpdateWorkflowExecutionLifecycleStage UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageAccepted = 2
toProtoEnumUpdateWorkflowExecutionLifecycleStage UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageCompleted = 3

fromProtoEnumUpdateWorkflowExecutionLifecycleStage :: Int -> Maybe UpdateWorkflowExecutionLifecycleStage
fromProtoEnumUpdateWorkflowExecutionLifecycleStage 0 = Just UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageUnspecified
fromProtoEnumUpdateWorkflowExecutionLifecycleStage 1 = Just UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageAdmitted
fromProtoEnumUpdateWorkflowExecutionLifecycleStage 2 = Just UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageAccepted
fromProtoEnumUpdateWorkflowExecutionLifecycleStage 3 = Just UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageCompleted
fromProtoEnumUpdateWorkflowExecutionLifecycleStage _ = Nothing

instance MessageEncode UpdateWorkflowExecutionLifecycleStage where
  buildMessage _ = mempty
instance MessageSize UpdateWorkflowExecutionLifecycleStage where
  messageSize _ = 0
instance MessageDecode UpdateWorkflowExecutionLifecycleStage where
  messageDecoder = pure (toEnum 0)

instance Aeson.ToJSON UpdateWorkflowExecutionLifecycleStage where
  toJSON UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageUnspecified = Aeson.String "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_UNSPECIFIED"
  toJSON UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageAdmitted = Aeson.String "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_ADMITTED"
  toJSON UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageAccepted = Aeson.String "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_ACCEPTED"
  toJSON UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageCompleted = Aeson.String "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_COMPLETED"

instance Aeson.FromJSON UpdateWorkflowExecutionLifecycleStage where
  parseJSON = \case
    Aeson.String "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_UNSPECIFIED" -> pure UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageUnspecified
    Aeson.String "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_ADMITTED" -> pure UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageAdmitted
    Aeson.String "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_ACCEPTED" -> pure UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageAccepted
    Aeson.String "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_COMPLETED" -> pure UpdateWorkflowExecutionLifecycleStage'UpdateWorkflowExecutionLifecycleStageCompleted
    Aeson.Number n -> pure (toEnum (round n))
    _ -> fail "Invalid enum value for UpdateWorkflowExecutionLifecycleStage"

data UpdateAdmittedEventOrigin
  = UpdateAdmittedEventOrigin'UpdateAdmittedEventOriginUnspecified
  | UpdateAdmittedEventOrigin'UpdateAdmittedEventOriginReapply
  deriving stock (Show, Eq, Ord, Enum, Bounded, Generic)
  deriving anyclass NFData

toProtoEnumUpdateAdmittedEventOrigin :: UpdateAdmittedEventOrigin -> Int
toProtoEnumUpdateAdmittedEventOrigin UpdateAdmittedEventOrigin'UpdateAdmittedEventOriginUnspecified = 0
toProtoEnumUpdateAdmittedEventOrigin UpdateAdmittedEventOrigin'UpdateAdmittedEventOriginReapply = 1

fromProtoEnumUpdateAdmittedEventOrigin :: Int -> Maybe UpdateAdmittedEventOrigin
fromProtoEnumUpdateAdmittedEventOrigin 0 = Just UpdateAdmittedEventOrigin'UpdateAdmittedEventOriginUnspecified
fromProtoEnumUpdateAdmittedEventOrigin 1 = Just UpdateAdmittedEventOrigin'UpdateAdmittedEventOriginReapply
fromProtoEnumUpdateAdmittedEventOrigin _ = Nothing

instance MessageEncode UpdateAdmittedEventOrigin where
  buildMessage _ = mempty
instance MessageSize UpdateAdmittedEventOrigin where
  messageSize _ = 0
instance MessageDecode UpdateAdmittedEventOrigin where
  messageDecoder = pure (toEnum 0)

instance Aeson.ToJSON UpdateAdmittedEventOrigin where
  toJSON UpdateAdmittedEventOrigin'UpdateAdmittedEventOriginUnspecified = Aeson.String "UPDATE_ADMITTED_EVENT_ORIGIN_UNSPECIFIED"
  toJSON UpdateAdmittedEventOrigin'UpdateAdmittedEventOriginReapply = Aeson.String "UPDATE_ADMITTED_EVENT_ORIGIN_REAPPLY"

instance Aeson.FromJSON UpdateAdmittedEventOrigin where
  parseJSON = \case
    Aeson.String "UPDATE_ADMITTED_EVENT_ORIGIN_UNSPECIFIED" -> pure UpdateAdmittedEventOrigin'UpdateAdmittedEventOriginUnspecified
    Aeson.String "UPDATE_ADMITTED_EVENT_ORIGIN_REAPPLY" -> pure UpdateAdmittedEventOrigin'UpdateAdmittedEventOriginReapply
    Aeson.Number n -> pure (toEnum (round n))
    _ -> fail "Invalid enum value for UpdateAdmittedEventOrigin"

