{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @google.protobuf@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Google.Protobuf.SourceContext where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe)
import Data.Proxy (Proxy(..))
import Proto.Message (IsMessage(..))
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import qualified Proto.Registry
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage,
  archVarintSize, archStringSize, archBytesSize, archBoolSize,
  archFixed32Size, archFixed64Size, archSubmessageSize)

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x24\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x73\x6f\x75\x72\x63\x65\x5f\x63\x6f\x6e\x74\x65\x78\x74\x2e\x70\x72\x6f\x74\x6f\x12\x0f\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x22\x22\x0a\x0d\x53\x6f\x75\x72\x63\x65\x43\x6f\x6e\x74\x65\x78\x74\x12\x11\x0a\x09\x66\x69\x6c\x65\x5f\x6e\x61\x6d\x65\x18\x01\x20\x01\x28\x09\x62\x06\x70\x72\x6f\x74\x6f\x33"


data SourceContext = SourceContext
  { sourceContextFileName :: !Text
  , sourceContextUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultSourceContext :: SourceContext
defaultSourceContext = SourceContext
  { sourceContextFileName = ""
  , sourceContextUnknownFields = []
  }

instance MessageEncode SourceContext where
  buildMessage msg =
    (if msg.sourceContextFileName == T.empty then mempty else archString 10 msg.sourceContextFileName)
    <> encodeUnknownFields msg.sourceContextUnknownFields

instance MessageSize SourceContext where
  messageSize msg =
    (if msg.sourceContextFileName == T.empty then 0 else archStringSize msg.sourceContextFileName)
    + unknownFieldsSize msg.sourceContextUnknownFields

instance MessageDecode SourceContext where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop "" []
    where
      loop acc_0 acc_unknown_ = do
        mTag <- getTagOrU
        case mTag of
          UNothing -> pure (SourceContext {sourceContextFileName = acc_0, sourceContextUnknownFields = reverse acc_unknown_})
          UJust (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_unknown_
            _ -> do
              uf <- captureUnknownField fn wt
              loop acc_0 (uf : acc_unknown_)

instance IsMessage SourceContext where
  messageTypeName _ = "google.protobuf.SourceContext"

instance ProtoMessage SourceContext where
  protoMessageName _ = "google.protobuf.SourceContext"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultSourceContext
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "file_name"
        , fdNumber = 1
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelOptional
        , fdGet = sourceContextFileName
        , fdSet = \v m -> m { sourceContextFileName = v }
        })
    ]

instance Aeson.ToJSON SourceContext where
  toJSON msg = jsonObject
      [ "fileName" .=: msg.sourceContextFileName

      ]

instance Aeson.FromJSON SourceContext where
  parseJSON = Aeson.withObject "SourceContext" $ \obj -> do
    fld_sourceContextFileName <- parseFieldMaybe obj "fileName"
    pure defaultSourceContext
      { sourceContextFileName = maybe (sourceContextFileName defaultSourceContext) id fld_sourceContextFileName
      }

instance Hashable SourceContext where
  hashWithSalt salt msg = hashWithSalt (salt) msg.sourceContextFileName

-- | Register all message types defined in this module.
registerModuleTypes :: Proto.Registry.MessageRegistry -> Proto.Registry.MessageRegistry
registerModuleTypes =
  Proto.Registry.registerType (Proxy :: Proxy SourceContext) .  id