{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @google.protobuf@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Google.Protobuf.SourceContext where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Proto.Encode
import Proto.Decode
import Proto.JSON
import Data.Proxy (Proxy(..))
import Proto.Message (IsMessage(..))
import qualified Proto.Registry
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)


data SourceContext = SourceContext
  { sourceContextFilename :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultSourceContext :: SourceContext
defaultSourceContext = SourceContext
  { sourceContextFilename = ""
  }

instance MessageEncode SourceContext where
  buildMessage msg =
    (if msg.sourceContextFilename == T.empty then mempty else encodeFieldString 1 msg.sourceContextFilename)

instance MessageSize SourceContext where
  messageSize msg =
    (if msg.sourceContextFilename == T.empty then 0 else fieldTextSize 1 msg.sourceContextFilename)

instance MessageDecode SourceContext where
  messageDecoder = loop ""
    where
      loop acc_0 = do
        mTag <- getTagOrU
        case mTag of
          UNothing -> pure (SourceContext {sourceContextFilename = acc_0})
          UJust (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v
            _ -> skipField wt >> loop acc_0

instance IsMessage SourceContext where
  messageTypeName _ = "google.protobuf.SourceContext"

instance ProtoToJSON SourceContext where
  protoToJSON msg = jsonObject
      [ "fileName" .= msg.sourceContextFilename

      ]

instance ProtoFromJSON SourceContext where
  protoFromJSON (JsonObject obj) = do
    fld_sourceContextFilename <- obj .:? "fileName"
    pure defaultSourceContext
      { sourceContextFilename = maybe (sourceContextFilename defaultSourceContext) id fld_sourceContextFilename
      }
  protoFromJSON _ = Right defaultSourceContext

-- | Register all message types defined in this module.
registerModuleTypes :: Proto.Registry.MessageRegistry -> Proto.Registry.MessageRegistry
registerModuleTypes =
  Proto.Registry.registerType (Proxy :: Proxy SourceContext) .  id