{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.sdk.v1@.
--
-- __THIS FILE IS AUTO-GENERATED BY hs-proto. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Temporalio.Api.Sdk.V1.WorkerConfig where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe)
import Data.Proxy (Proxy(..))
import Proto.Message (IsMessage(..))
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import qualified Data.ByteString.Base16 as Base16
import qualified Proto.Registry
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = case Base16.decode "0a2774656d706f72616c2f6170692f73646b2f76312f776f726b65725f636f6e6669672e70726f746f121374656d706f72616c2e6170692e73646b2e763122c1020a0c576f726b6572436f6e666967121b0a13776f726b666c6f775f63616368655f73697a6518012001280512340a1673696d706c655f706f6c6c65725f6265686176696f7218022001280b321453696d706c65506f6c6c65724265686176696f72123e0a1b6175746f7363616c696e675f706f6c6c65725f6265686176696f7218032001280b32194175746f7363616c696e67506f6c6c65724265686176696f721a2b0a1453696d706c65506f6c6c65724265686176696f7212130a0b6d61785f706f6c6c6572731801200128051a5e0a194175746f7363616c696e67506f6c6c65724265686176696f7212130a0b6d696e5f706f6c6c65727318012001280512130a0b6d61785f706f6c6c65727318022001280512170a0f696e697469616c5f706f6c6c65727318032001280542110a0f706f6c6c65725f6265686176696f72620670726f746f33" of
  Right bs -> bs
  Left _ -> ""


data WorkerConfig = WorkerConfig
  { workerConfigWorkflowcachesize :: {-# UNPACK #-} !Int32
  , workerConfigPollerbehavior :: !(Maybe WorkerConfig'PollerBehavior)
  , workerConfigUnknownfields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

data WorkerConfig'SimplePollerBehavior = WorkerConfig'SimplePollerBehavior
  { workerConfigSimplePollerBehaviorMaxpollers :: {-# UNPACK #-} !Int32
  , workerConfigSimplePollerBehaviorUnknownfields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkerConfig'SimplePollerBehavior :: WorkerConfig'SimplePollerBehavior
defaultWorkerConfig'SimplePollerBehavior = WorkerConfig'SimplePollerBehavior
  { workerConfigSimplePollerBehaviorMaxpollers = 0
  , workerConfigSimplePollerBehaviorUnknownfields = []
  }

instance MessageEncode WorkerConfig'SimplePollerBehavior where
  buildMessage msg =
    (if msg.workerConfigSimplePollerBehaviorMaxpollers == 0 then mempty else encodeFieldVarint 1 (fromIntegral msg.workerConfigSimplePollerBehaviorMaxpollers))
    <> encodeUnknownFields msg.workerConfigSimplePollerBehaviorUnknownfields

instance MessageSize WorkerConfig'SimplePollerBehavior where
  messageSize msg =
    (if msg.workerConfigSimplePollerBehaviorMaxpollers == 0 then 0 else fieldVarintSize 1 (fromIntegral msg.workerConfigSimplePollerBehaviorMaxpollers))
    + unknownFieldsSize msg.workerConfigSimplePollerBehaviorUnknownfields

instance MessageDecode WorkerConfig'SimplePollerBehavior where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop 0 []
    where
      loop acc_0 acc_unknown_ = do
        mTag <- getTagOrU
        case mTag of
          UNothing -> pure (WorkerConfig'SimplePollerBehavior {workerConfigSimplePollerBehaviorMaxpollers = acc_0, workerConfigSimplePollerBehaviorUnknownfields = reverse acc_unknown_})
          UJust (Tag fn wt) -> case fn of
            1 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop v acc_unknown_
            _ -> do
              uf <- captureUnknownField fn wt
              loop acc_0 (uf : acc_unknown_)

instance IsMessage WorkerConfig'SimplePollerBehavior where
  messageTypeName _ = "temporal.api.sdk.v1.WorkerConfig.SimplePollerBehavior"

instance ProtoMessage WorkerConfig'SimplePollerBehavior where
  protoMessageName _ = "temporal.api.sdk.v1.WorkerConfig.SimplePollerBehavior"
  protoPackageName _ = "temporal.api.sdk.v1"
  protoDefaultValue = defaultWorkerConfig'SimplePollerBehavior
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "max_pollers"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = workerConfigSimplePollerBehaviorMaxpollers
        , fdSet = \v m -> m { workerConfigSimplePollerBehaviorMaxpollers = v }
        })
    ]

instance Aeson.ToJSON WorkerConfig'SimplePollerBehavior where
  toJSON msg = jsonObject
      [ "maxPollers" .=: msg.workerConfigSimplePollerBehaviorMaxpollers

      ]

instance Aeson.FromJSON WorkerConfig'SimplePollerBehavior where
  parseJSON = Aeson.withObject "WorkerConfig'SimplePollerBehavior" $ \obj -> do
    fld_workerConfigSimplePollerBehaviorMaxpollers <- parseFieldMaybe obj "maxPollers"
    pure defaultWorkerConfig'SimplePollerBehavior
      { workerConfigSimplePollerBehaviorMaxpollers = maybe (workerConfigSimplePollerBehaviorMaxpollers defaultWorkerConfig'SimplePollerBehavior) id fld_workerConfigSimplePollerBehaviorMaxpollers
      }

instance Hashable WorkerConfig'SimplePollerBehavior where
  hashWithSalt salt msg = hashWithSalt (salt) msg.workerConfigSimplePollerBehaviorMaxpollers

data WorkerConfig'AutoscalingPollerBehavior = WorkerConfig'AutoscalingPollerBehavior
  { workerConfigAutoscalingPollerBehaviorMinpollers :: {-# UNPACK #-} !Int32
  , workerConfigAutoscalingPollerBehaviorMaxpollers :: {-# UNPACK #-} !Int32
  , workerConfigAutoscalingPollerBehaviorInitialpollers :: {-# UNPACK #-} !Int32
  , workerConfigAutoscalingPollerBehaviorUnknownfields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkerConfig'AutoscalingPollerBehavior :: WorkerConfig'AutoscalingPollerBehavior
defaultWorkerConfig'AutoscalingPollerBehavior = WorkerConfig'AutoscalingPollerBehavior
  { workerConfigAutoscalingPollerBehaviorMinpollers = 0
  , workerConfigAutoscalingPollerBehaviorMaxpollers = 0
  , workerConfigAutoscalingPollerBehaviorInitialpollers = 0
  , workerConfigAutoscalingPollerBehaviorUnknownfields = []
  }

instance MessageEncode WorkerConfig'AutoscalingPollerBehavior where
  buildMessage msg =
    (if msg.workerConfigAutoscalingPollerBehaviorMinpollers == 0 then mempty else encodeFieldVarint 1 (fromIntegral msg.workerConfigAutoscalingPollerBehaviorMinpollers))
    <> (if msg.workerConfigAutoscalingPollerBehaviorMaxpollers == 0 then mempty else encodeFieldVarint 2 (fromIntegral msg.workerConfigAutoscalingPollerBehaviorMaxpollers))
    <> (if msg.workerConfigAutoscalingPollerBehaviorInitialpollers == 0 then mempty else encodeFieldVarint 3 (fromIntegral msg.workerConfigAutoscalingPollerBehaviorInitialpollers))
    <> encodeUnknownFields msg.workerConfigAutoscalingPollerBehaviorUnknownfields

instance MessageSize WorkerConfig'AutoscalingPollerBehavior where
  messageSize msg =
    (if msg.workerConfigAutoscalingPollerBehaviorMinpollers == 0 then 0 else fieldVarintSize 1 (fromIntegral msg.workerConfigAutoscalingPollerBehaviorMinpollers))
    + (if msg.workerConfigAutoscalingPollerBehaviorMaxpollers == 0 then 0 else fieldVarintSize 2 (fromIntegral msg.workerConfigAutoscalingPollerBehaviorMaxpollers))
    + (if msg.workerConfigAutoscalingPollerBehaviorInitialpollers == 0 then 0 else fieldVarintSize 3 (fromIntegral msg.workerConfigAutoscalingPollerBehaviorInitialpollers))
    + unknownFieldsSize msg.workerConfigAutoscalingPollerBehaviorUnknownfields

instance MessageDecode WorkerConfig'AutoscalingPollerBehavior where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop 0 0 0 []
    where
      loop acc_0 acc_1 acc_2 acc_unknown_ = do
        mTag <- getTagOrU
        case mTag of
          UNothing -> pure (WorkerConfig'AutoscalingPollerBehavior {workerConfigAutoscalingPollerBehaviorMinpollers = acc_0, workerConfigAutoscalingPollerBehaviorMaxpollers = acc_1, workerConfigAutoscalingPollerBehaviorInitialpollers = acc_2, workerConfigAutoscalingPollerBehaviorUnknownfields = reverse acc_unknown_})
          UJust (Tag fn wt) -> case fn of
            1 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop v acc_1 acc_2 acc_unknown_
            2 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop acc_0 v acc_2 acc_unknown_
            3 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop acc_0 acc_1 v acc_unknown_
            _ -> do
              uf <- captureUnknownField fn wt
              loop acc_0 acc_1 acc_2 (uf : acc_unknown_)

instance IsMessage WorkerConfig'AutoscalingPollerBehavior where
  messageTypeName _ = "temporal.api.sdk.v1.WorkerConfig.AutoscalingPollerBehavior"

instance ProtoMessage WorkerConfig'AutoscalingPollerBehavior where
  protoMessageName _ = "temporal.api.sdk.v1.WorkerConfig.AutoscalingPollerBehavior"
  protoPackageName _ = "temporal.api.sdk.v1"
  protoDefaultValue = defaultWorkerConfig'AutoscalingPollerBehavior
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "min_pollers"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = workerConfigAutoscalingPollerBehaviorMinpollers
        , fdSet = \v m -> m { workerConfigAutoscalingPollerBehaviorMinpollers = v }
        }), (2, SomeField FieldDescriptor
        { fdName = "max_pollers"
        , fdNumber = 2
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = workerConfigAutoscalingPollerBehaviorMaxpollers
        , fdSet = \v m -> m { workerConfigAutoscalingPollerBehaviorMaxpollers = v }
        })
    , (3, SomeField FieldDescriptor
        { fdName = "initial_pollers"
        , fdNumber = 3
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = workerConfigAutoscalingPollerBehaviorInitialpollers
        , fdSet = \v m -> m { workerConfigAutoscalingPollerBehaviorInitialpollers = v }
        })
    ]

instance Aeson.ToJSON WorkerConfig'AutoscalingPollerBehavior where
  toJSON msg = jsonObject
      [ "minPollers" .=: msg.workerConfigAutoscalingPollerBehaviorMinpollers
      , "maxPollers" .=: msg.workerConfigAutoscalingPollerBehaviorMaxpollers
      , "initialPollers" .=: msg.workerConfigAutoscalingPollerBehaviorInitialpollers
      ]

instance Aeson.FromJSON WorkerConfig'AutoscalingPollerBehavior where
  parseJSON = Aeson.withObject "WorkerConfig'AutoscalingPollerBehavior" $ \obj -> do
    fld_workerConfigAutoscalingPollerBehaviorMinpollers <- parseFieldMaybe obj "minPollers"
    fld_workerConfigAutoscalingPollerBehaviorMaxpollers <- parseFieldMaybe obj "maxPollers"
    fld_workerConfigAutoscalingPollerBehaviorInitialpollers <- parseFieldMaybe obj "initialPollers"
    pure defaultWorkerConfig'AutoscalingPollerBehavior
      { workerConfigAutoscalingPollerBehaviorMinpollers = maybe (workerConfigAutoscalingPollerBehaviorMinpollers defaultWorkerConfig'AutoscalingPollerBehavior) id fld_workerConfigAutoscalingPollerBehaviorMinpollers
      , workerConfigAutoscalingPollerBehaviorMaxpollers = maybe (workerConfigAutoscalingPollerBehaviorMaxpollers defaultWorkerConfig'AutoscalingPollerBehavior) id fld_workerConfigAutoscalingPollerBehaviorMaxpollers
      , workerConfigAutoscalingPollerBehaviorInitialpollers = maybe (workerConfigAutoscalingPollerBehaviorInitialpollers defaultWorkerConfig'AutoscalingPollerBehavior) id fld_workerConfigAutoscalingPollerBehaviorInitialpollers
      }

instance Hashable WorkerConfig'AutoscalingPollerBehavior where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (hashWithSalt (salt) msg.workerConfigAutoscalingPollerBehaviorMinpollers) msg.workerConfigAutoscalingPollerBehaviorMaxpollers) msg.workerConfigAutoscalingPollerBehaviorInitialpollers
data WorkerConfig'PollerBehavior
  = WorkerConfig'PollerBehavior'SimplePollerBehavior !WorkerConfig'SimplePollerBehavior
  | WorkerConfig'PollerBehavior'AutoscalingPollerBehavior !WorkerConfig'AutoscalingPollerBehavior
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
instance Aeson.ToJSON WorkerConfig'PollerBehavior where
  toJSON _ = Aeson.Null
instance Aeson.FromJSON WorkerConfig'PollerBehavior where
  parseJSON _ = fail "Cannot parse oneof from JSON"
instance Hashable WorkerConfig'PollerBehavior where
  hashWithSalt salt (WorkerConfig'PollerBehavior'SimplePollerBehavior v) = salt `hashWithSalt` (0 :: Int) `hashWithSalt` v
  hashWithSalt salt (WorkerConfig'PollerBehavior'AutoscalingPollerBehavior v) = salt `hashWithSalt` (1 :: Int) `hashWithSalt` v

defaultWorkerConfig :: WorkerConfig
defaultWorkerConfig = WorkerConfig
  { workerConfigWorkflowcachesize = 0
  , workerConfigPollerbehavior = Nothing
  , workerConfigUnknownfields = []
  }

instance MessageEncode WorkerConfig where
  buildMessage msg =
    (if msg.workerConfigWorkflowcachesize == 0 then mempty else encodeFieldVarint 1 (fromIntegral msg.workerConfigWorkflowcachesize))
    <> (case msg.workerConfigPollerbehavior of
      Nothing -> mempty
      Just (WorkerConfig'PollerBehavior'SimplePollerBehavior v) -> encodeFieldMessage 2 v
      Just (WorkerConfig'PollerBehavior'AutoscalingPollerBehavior v) -> encodeFieldMessage 3 v)
    <> encodeUnknownFields msg.workerConfigUnknownfields

instance MessageSize WorkerConfig where
  messageSize msg =
    (if msg.workerConfigWorkflowcachesize == 0 then 0 else fieldVarintSize 1 (fromIntegral msg.workerConfigWorkflowcachesize))
    + (case msg.workerConfigPollerbehavior of { Nothing -> 0; Just (WorkerConfig'PollerBehavior'SimplePollerBehavior v) -> fieldMessageSize 2 (messageSize v)
    ; Just (WorkerConfig'PollerBehavior'AutoscalingPollerBehavior v) -> fieldMessageSize 3 (messageSize v) })
    + unknownFieldsSize msg.workerConfigUnknownfields

instance MessageDecode WorkerConfig where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop 0 Nothing []
    where
      loop acc_0 acc_1 acc_unknown_ = do
        mTag <- getTagOrU
        case mTag of
          UNothing -> pure (WorkerConfig {workerConfigWorkflowcachesize = acc_0, workerConfigPollerbehavior = acc_1, workerConfigUnknownfields = reverse acc_unknown_})
          UJust (Tag fn wt) -> case fn of
            1 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop v acc_1 acc_unknown_
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just (WorkerConfig'PollerBehavior'SimplePollerBehavior v)) acc_unknown_
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just (WorkerConfig'PollerBehavior'AutoscalingPollerBehavior v)) acc_unknown_
            _ -> do
              uf <- captureUnknownField fn wt
              loop acc_0 acc_1 (uf : acc_unknown_)

instance IsMessage WorkerConfig where
  messageTypeName _ = "temporal.api.sdk.v1.WorkerConfig"

instance ProtoMessage WorkerConfig where
  protoMessageName _ = "temporal.api.sdk.v1.WorkerConfig"
  protoPackageName _ = "temporal.api.sdk.v1"
  protoDefaultValue = defaultWorkerConfig
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "workflow_cache_size"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = workerConfigWorkflowcachesize
        , fdSet = \v m -> m { workerConfigWorkflowcachesize = v }
        }), (2, SomeField FieldDescriptor
        { fdName = "poller_behavior"
        , fdNumber = 2
        , fdTypeDesc = MessageType "poller_behavior"
        , fdLabel = LabelOptional
        , fdGet = workerConfigPollerbehavior
        , fdSet = \v m -> m { workerConfigPollerbehavior = v }
        })
    ]

instance Aeson.ToJSON WorkerConfig where
  toJSON msg = jsonObject
      [ "workflowCacheSize" .=: msg.workerConfigWorkflowcachesize
      , "pollerBehavior" .=: msg.workerConfigPollerbehavior
      ]

instance Aeson.FromJSON WorkerConfig where
  parseJSON = Aeson.withObject "WorkerConfig" $ \obj -> do
    fld_workerConfigWorkflowcachesize <- parseFieldMaybe obj "workflowCacheSize"
    fld_workerConfigPollerbehavior <- parseFieldMaybe obj "pollerBehavior"
    pure defaultWorkerConfig
      { workerConfigWorkflowcachesize = maybe (workerConfigWorkflowcachesize defaultWorkerConfig) id fld_workerConfigWorkflowcachesize
      , workerConfigPollerbehavior = maybe (workerConfigPollerbehavior defaultWorkerConfig) id fld_workerConfigPollerbehavior
      }

instance Hashable WorkerConfig where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (salt) msg.workerConfigWorkflowcachesize) msg.workerConfigPollerbehavior

-- | Register all message types defined in this module.
registerModuleTypes :: Proto.Registry.MessageRegistry -> Proto.Registry.MessageRegistry
registerModuleTypes =
  Proto.Registry.registerType (Proxy :: Proxy WorkerConfig) .
  Proto.Registry.registerType (Proxy :: Proxy WorkerConfig'SimplePollerBehavior) .
  Proto.Registry.registerType (Proxy :: Proxy WorkerConfig'AutoscalingPollerBehavior) .  id