{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StrictData #-}

{- | Auto-generated protobuf types from package @google.protobuf@.

__THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__

Any manual changes will be overwritten the next time code
generation is run.  To modify the types or instances, edit the
@.proto@ source file and re-run the code generator.
-}
module Proto.Google.Protobuf.FieldMask where

import Control.DeepSeq (NFData (..))
import Data.Aeson qualified as Aeson
import Data.Aeson.Key qualified as AesonKey
import Data.Aeson.KeyMap qualified as AesonKM
import Data.Aeson.Types qualified as Aeson
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Hashable (Hashable (..))
import Data.Int (Int32, Int64)
import Data.Map.Strict qualified as Map
import Data.Proxy (Proxy (..))
import Data.Text (Text)
import Data.Text qualified as T
import Data.Vector qualified as V
import Data.Vector.Unboxed qualified as VU
import Data.Word (Word32, Word64)
import GHC.Generics (Generic)
import Proto.Decode
import Proto.Encode
import Proto.Encode.Archetype (
  archBool,
  archBoolSize,
  archBytes,
  archBytesSize,
  archDouble,
  archFixed32,
  archFixed32Size,
  archFixed64,
  archFixed64Size,
  archFloat,
  archSVarint32,
  archSVarint64,
  archString,
  archStringSize,
  archSubmessage,
  archSubmessageSize,
  archVarint,
  archVarintSize,
 )
import Proto.Extension qualified
import Proto.JSON (bytesFieldToJSON, bytesMapFieldToJSON, jsonObject, parseBytesFieldMaybe, parseBytesMapFieldMaybe, parseFieldMaybe, protoBytesToJSON, (.=:))
import Proto.Message (IsMessage (..))
import Proto.Registry qualified
import Proto.Schema (FieldDescriptor (..), FieldLabel' (..), FieldTypeDescriptor (..), ProtoMessage (..), ScalarFieldType (..), SomeFieldDescriptor (..))
import Proto.Wire (Tag (..), WireType (..))
import Proto.Wire.Encode (
  fieldBoolSize,
  fieldBytesSize,
  fieldDoubleSize,
  fieldFixed32Size,
  fieldFixed64Size,
  fieldFloatSize,
  fieldMessageSize,
  fieldSVarint32Size,
  fieldSVarint64Size,
  fieldTextSize,
  fieldVarintSize,
  putByteString,
  putDouble,
  putFixed32,
  putFixed64,
  putFloat,
  putLengthDelimited,
  putSVarint32,
  putSVarint64,
  putTag,
  putText,
  putVarint,
  putVarintSigned,
  tagSize,
  varintSize,
  varintSize32,
  zigZag32,
  zigZag64,
 )
import Wireform.Builder qualified as B


{- | Serialized FileDescriptorProto for this .proto file.
Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
-}
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x20\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x66\x69\x65\x6c\x64\x5f\x6d\x61\x73\x6b\x2e\x70\x72\x6f\x74\x6f\x12\x0f\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x22\x1a\x0a\x09\x46\x69\x65\x6c\x64\x4d\x61\x73\x6b\x12\x0d\x0a\x05\x70\x61\x74\x68\x73\x18\x01\x20\x03\x28\x09\x62\x06\x70\x72\x6f\x74\x6f\x33"


data FieldMask = FieldMask
  { fieldMaskPaths :: !(V.Vector Text)
  , fieldMaskUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass (NFData)


defaultFieldMask :: FieldMask
defaultFieldMask =
  FieldMask
    { fieldMaskPaths = V.empty
    , fieldMaskUnknownFields = []
    }


instance MessageEncode FieldMask where
  buildMessage msg =
    V.foldl' (\acc v -> acc <> archString 10 v) mempty msg.fieldMaskPaths
      <> encodeUnknownFields msg.fieldMaskUnknownFields


instance MessageSize FieldMask where
  messageSize msg =
    (V.foldl' (\acc v -> acc + fieldTextSize 1 v) 0 msg.fieldMaskPaths)
      + unknownFieldsSize msg.fieldMaskUnknownFields


instance MessageDecode FieldMask where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop V.empty []
    where
      loop acc_0 acc_unknown_ =
        withTagM
          (pure (FieldMask {fieldMaskPaths = acc_0, fieldMaskUnknownFields = reverse acc_unknown_}))
          ( \fn wt -> case fn of
              1 -> do
                v <- decodeFieldString
                loop (acc_0 <> V.singleton v) acc_unknown_
              _ -> do
                uf <- captureUnknownField fn (toEnum wt)
                loop acc_0 (uf : acc_unknown_)
          )


instance IsMessage FieldMask where
  messageTypeName _ = "google.protobuf.FieldMask"


instance ProtoMessage FieldMask where
  protoMessageName _ = "google.protobuf.FieldMask"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultFieldMask
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ =
    Map.fromList
      [
        ( 1
        , SomeField
            FieldDescriptor
              { fdName = "paths"
              , fdNumber = 1
              , fdTypeDesc = ScalarType StringField
              , fdLabel = LabelRepeated
              , fdGet = fieldMaskPaths
              , fdSet = \v m -> m {fieldMaskPaths = v}
              }
        )
      ]


instance Aeson.ToJSON FieldMask where
  toJSON msg =
    jsonObject
      [ "paths" .=: msg.fieldMaskPaths
      ]


instance Aeson.FromJSON FieldMask where
  parseJSON = Aeson.withObject "FieldMask" $ \obj -> do
    fld_fieldMaskPaths <- parseFieldMaybe obj "paths"
    pure
      defaultFieldMask
        { fieldMaskPaths = maybe (fieldMaskPaths defaultFieldMask) id fld_fieldMaskPaths
        }


instance Hashable FieldMask where
  hashWithSalt salt msg = V.foldl' hashWithSalt (salt) msg.fieldMaskPaths


instance Proto.Extension.HasExtensions FieldMask where
  messageUnknownFields = fieldMaskUnknownFields
  setMessageUnknownFields !ufs msg = msg {fieldMaskUnknownFields = ufs}


-- | Register all message types defined in this module.
registerModuleTypes :: Proto.Registry.MessageRegistry -> Proto.Registry.MessageRegistry
registerModuleTypes =
  Proto.Registry.registerType (Proxy :: Proxy FieldMask) . id
