{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.query.v1@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Temporal.Temporal.Api.Query.V1.Message where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Proto.Encode
import Proto.Decode
import Proto.JSON
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize)
import Proto.Temporal.Temporal.Api.Common.V1.Message (Header(..), Payloads(..))
import Proto.Temporal.Temporal.Api.Enums.V1.Query (QueryResultType(..))
import Proto.Temporal.Temporal.Api.Enums.V1.Workflow (WorkflowExecutionStatus(..))
import Proto.Temporal.Temporal.Api.Failure.V1.Message (Failure(..))


data WorkflowQuery = WorkflowQuery
  { workflowQueryQuerytype :: !Text
  , workflowQueryQueryargs :: !(Maybe Payloads)
  , workflowQueryHeader :: !(Maybe Header)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkflowQuery :: WorkflowQuery
defaultWorkflowQuery = WorkflowQuery
  { workflowQueryQuerytype = ""
  , workflowQueryQueryargs = Nothing
  , workflowQueryHeader = Nothing
  }

instance MessageEncode WorkflowQuery where
  buildMessage msg =
    (if msg.workflowQueryQuerytype == T.empty then mempty else encodeFieldString 1 msg.workflowQueryQuerytype)
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.workflowQueryQueryargs)
    <> (maybe mempty (\v -> encodeFieldMessage 3 v) msg.workflowQueryHeader)

instance MessageSize WorkflowQuery where
  messageSize msg =
    (if msg.workflowQueryQuerytype == T.empty then 0 else fieldTextSize 1 msg.workflowQueryQuerytype)
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.workflowQueryQueryargs)
    + (maybe 0 (\v -> fieldMessageSize 3 (messageSize v)) msg.workflowQueryHeader)

instance MessageDecode WorkflowQuery where
  messageDecoder = loop "" Nothing Nothing
    where
      loop acc_0 acc_1 acc_2 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (WorkflowQuery {workflowQueryQuerytype = acc_0, workflowQueryQueryargs = acc_1, workflowQueryHeader = acc_2})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (Just v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2

instance ProtoToJSON WorkflowQuery where
  protoToJSON msg = jsonObject
      [ "queryType" .= msg.workflowQueryQuerytype
      , "queryArgs" .= msg.workflowQueryQueryargs
      , "header" .= msg.workflowQueryHeader
      ]

instance ProtoFromJSON WorkflowQuery where
  protoFromJSON _ = Right defaultWorkflowQuery

data WorkflowQueryResult = WorkflowQueryResult
  { workflowQueryResultResulttype :: !QueryResultType
  , workflowQueryResultAnswer :: !(Maybe Payloads)
  , workflowQueryResultErrormessage :: !Text
  , workflowQueryResultFailure :: !(Maybe Failure)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkflowQueryResult :: WorkflowQueryResult
defaultWorkflowQueryResult = WorkflowQueryResult
  { workflowQueryResultResulttype = (toEnum 0)
  , workflowQueryResultAnswer = Nothing
  , workflowQueryResultErrormessage = ""
  , workflowQueryResultFailure = Nothing
  }

instance MessageEncode WorkflowQueryResult where
  buildMessage msg =
    (if fromEnum msg.workflowQueryResultResulttype == 0 then mempty else encodeFieldVarint 1 (fromIntegral (fromEnum msg.workflowQueryResultResulttype)))
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.workflowQueryResultAnswer)
    <> (if msg.workflowQueryResultErrormessage == T.empty then mempty else encodeFieldString 3 msg.workflowQueryResultErrormessage)
    <> (maybe mempty (\v -> encodeFieldMessage 4 v) msg.workflowQueryResultFailure)

instance MessageSize WorkflowQueryResult where
  messageSize msg =
    (if fromEnum msg.workflowQueryResultResulttype == 0 then 0 else fieldVarintSize 1 (fromIntegral (fromEnum msg.workflowQueryResultResulttype)))
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.workflowQueryResultAnswer)
    + (if msg.workflowQueryResultErrormessage == T.empty then 0 else fieldTextSize 3 msg.workflowQueryResultErrormessage)
    + (maybe 0 (\v -> fieldMessageSize 4 (messageSize v)) msg.workflowQueryResultFailure)

instance MessageDecode WorkflowQueryResult where
  messageDecoder = loop (toEnum 0) Nothing "" Nothing
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (WorkflowQueryResult {workflowQueryResultResulttype = acc_0, workflowQueryResultAnswer = acc_1, workflowQueryResultErrormessage = acc_2, workflowQueryResultFailure = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldEnum
              loop v acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2 acc_3
            3 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 v acc_3
            4 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 (Just v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON WorkflowQueryResult where
  protoToJSON msg = jsonObject
      [ "resultType" .= msg.workflowQueryResultResulttype
      , "answer" .= msg.workflowQueryResultAnswer
      , "errorMessage" .= msg.workflowQueryResultErrormessage
      , "failure" .= msg.workflowQueryResultFailure
      ]

instance ProtoFromJSON WorkflowQueryResult where
  protoFromJSON _ = Right defaultWorkflowQueryResult

data QueryRejected = QueryRejected
  { queryRejectedStatus :: !WorkflowExecutionStatus
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultQueryRejected :: QueryRejected
defaultQueryRejected = QueryRejected
  { queryRejectedStatus = (toEnum 0)
  }

instance MessageEncode QueryRejected where
  buildMessage msg =
    (if fromEnum msg.queryRejectedStatus == 0 then mempty else encodeFieldVarint 1 (fromIntegral (fromEnum msg.queryRejectedStatus)))

instance MessageSize QueryRejected where
  messageSize msg =
    (if fromEnum msg.queryRejectedStatus == 0 then 0 else fieldVarintSize 1 (fromIntegral (fromEnum msg.queryRejectedStatus)))

instance MessageDecode QueryRejected where
  messageDecoder = loop (toEnum 0)
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (QueryRejected {queryRejectedStatus = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldEnum
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON QueryRejected where
  protoToJSON msg = jsonObject
      [ "status" .= msg.queryRejectedStatus

      ]

instance ProtoFromJSON QueryRejected where
  protoFromJSON _ = Right defaultQueryRejected