{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.batch.v1@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Temporal.Temporal.Api.Batch.V1.Message where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Proto.Encode
import Proto.Decode
import Proto.JSON
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize)
import Proto.Google.Protobuf.Duration (Duration)
import Proto.Google.Protobuf.FieldMask (FieldMask)
import Proto.Google.Protobuf.Timestamp (Timestamp)
import Proto.Temporal.Temporal.Api.Activity.V1.Message (ActivityOptions)
import Proto.Temporal.Temporal.Api.Common.V1.Message (Header, Payloads, ResetOptions)
import Proto.Temporal.Temporal.Api.Enums.V1.BatchOperation (BatchOperationState)
import Proto.Temporal.Temporal.Api.Enums.V1.Reset (ResetReapplyType, ResetType)
import Proto.Temporal.Temporal.Api.Rules.V1.Message (WorkflowRuleSpec)
import Proto.Temporal.Temporal.Api.Workflow.V1.Message (PostResetOperation, WorkflowExecutionOptions)


data BatchOperationInfo = BatchOperationInfo
  { batchOperationInfoJobid :: !Text
  , batchOperationInfoState :: !BatchOperationState
  , batchOperationInfoStarttime :: !(Maybe Timestamp)
  , batchOperationInfoClosetime :: !(Maybe Timestamp)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationInfo :: BatchOperationInfo
defaultBatchOperationInfo = BatchOperationInfo
  { batchOperationInfoJobid = ""
  , batchOperationInfoState = (toEnum 0)
  , batchOperationInfoStarttime = Nothing
  , batchOperationInfoClosetime = Nothing
  }

instance MessageEncode BatchOperationInfo where
  buildMessage msg =
    (if msg.batchOperationInfoJobid == T.empty then mempty else encodeFieldString 1 msg.batchOperationInfoJobid)
    <> (if fromEnum msg.batchOperationInfoState == 0 then mempty else encodeFieldVarint 2 (fromIntegral (fromEnum msg.batchOperationInfoState)))
    <> (maybe mempty (\v -> encodeFieldMessage 3 v) msg.batchOperationInfoStarttime)
    <> (maybe mempty (\v -> encodeFieldMessage 4 v) msg.batchOperationInfoClosetime)

instance MessageSize BatchOperationInfo where
  messageSize msg =
    (if msg.batchOperationInfoJobid == T.empty then 0 else fieldTextSize 1 msg.batchOperationInfoJobid)
    + (if fromEnum msg.batchOperationInfoState == 0 then 0 else fieldVarintSize 2 (fromIntegral (fromEnum msg.batchOperationInfoState)))
    + (maybe 0 (\v -> fieldMessageSize 3 (messageSize v)) msg.batchOperationInfoStarttime)
    + (maybe 0 (\v -> fieldMessageSize 4 (messageSize v)) msg.batchOperationInfoClosetime)

instance MessageDecode BatchOperationInfo where
  messageDecoder = loop "" (toEnum 0) Nothing Nothing
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationInfo {batchOperationInfoJobid = acc_0, batchOperationInfoState = acc_1, batchOperationInfoStarttime = acc_2, batchOperationInfoClosetime = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldEnum
              loop acc_0 v acc_2 acc_3
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (Just v) acc_3
            4 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 (Just v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON BatchOperationInfo where
  protoToJSON msg = jsonObject
      [ "jobId" .= msg.batchOperationInfoJobid
      , "state" .= msg.batchOperationInfoState
      , "startTime" .= msg.batchOperationInfoStarttime
      , "closeTime" .= msg.batchOperationInfoClosetime
      ]

instance ProtoFromJSON BatchOperationInfo where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationInfoJobid <- obj .:? "jobId"
    v_batchOperationInfoState <- obj .:? "state"
    v_batchOperationInfoStarttime <- obj .:? "startTime"
    v_batchOperationInfoClosetime <- obj .:? "closeTime"
    pure (BatchOperationInfo {
       batchOperationInfoJobid = v_batchOperationInfoJobid
      , batchOperationInfoState = v_batchOperationInfoState
      , batchOperationInfoStarttime = v_batchOperationInfoStarttime
      , batchOperationInfoClosetime = v_batchOperationInfoClosetime
    })
  protoFromJSON _ = Left "Expected JSON object"

data BatchOperationTermination = BatchOperationTermination
  { batchOperationTerminationDetails :: !(Maybe Payloads)
  , batchOperationTerminationIdentity :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationTermination :: BatchOperationTermination
defaultBatchOperationTermination = BatchOperationTermination
  { batchOperationTerminationDetails = Nothing
  , batchOperationTerminationIdentity = ""
  }

instance MessageEncode BatchOperationTermination where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.batchOperationTerminationDetails)
    <> (if msg.batchOperationTerminationIdentity == T.empty then mempty else encodeFieldString 2 msg.batchOperationTerminationIdentity)

instance MessageSize BatchOperationTermination where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.batchOperationTerminationDetails)
    + (if msg.batchOperationTerminationIdentity == T.empty then 0 else fieldTextSize 2 msg.batchOperationTerminationIdentity)

instance MessageDecode BatchOperationTermination where
  messageDecoder = loop Nothing ""
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationTermination {batchOperationTerminationDetails = acc_0, batchOperationTerminationIdentity = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v) acc_1
            2 -> do
              v <- decodeFieldString
              loop acc_0 v
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON BatchOperationTermination where
  protoToJSON msg = jsonObject
      [ "details" .= msg.batchOperationTerminationDetails
      , "identity" .= msg.batchOperationTerminationIdentity
      ]

instance ProtoFromJSON BatchOperationTermination where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationTerminationDetails <- obj .:? "details"
    v_batchOperationTerminationIdentity <- obj .:? "identity"
    pure (BatchOperationTermination {
       batchOperationTerminationDetails = v_batchOperationTerminationDetails
      , batchOperationTerminationIdentity = v_batchOperationTerminationIdentity
    })
  protoFromJSON _ = Left "Expected JSON object"

data BatchOperationSignal = BatchOperationSignal
  { batchOperationSignalSignal :: !Text
  , batchOperationSignalInput :: !(Maybe Payloads)
  , batchOperationSignalHeader :: !(Maybe Header)
  , batchOperationSignalIdentity :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationSignal :: BatchOperationSignal
defaultBatchOperationSignal = BatchOperationSignal
  { batchOperationSignalSignal = ""
  , batchOperationSignalInput = Nothing
  , batchOperationSignalHeader = Nothing
  , batchOperationSignalIdentity = ""
  }

instance MessageEncode BatchOperationSignal where
  buildMessage msg =
    (if msg.batchOperationSignalSignal == T.empty then mempty else encodeFieldString 1 msg.batchOperationSignalSignal)
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.batchOperationSignalInput)
    <> (maybe mempty (\v -> encodeFieldMessage 3 v) msg.batchOperationSignalHeader)
    <> (if msg.batchOperationSignalIdentity == T.empty then mempty else encodeFieldString 4 msg.batchOperationSignalIdentity)

instance MessageSize BatchOperationSignal where
  messageSize msg =
    (if msg.batchOperationSignalSignal == T.empty then 0 else fieldTextSize 1 msg.batchOperationSignalSignal)
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.batchOperationSignalInput)
    + (maybe 0 (\v -> fieldMessageSize 3 (messageSize v)) msg.batchOperationSignalHeader)
    + (if msg.batchOperationSignalIdentity == T.empty then 0 else fieldTextSize 4 msg.batchOperationSignalIdentity)

instance MessageDecode BatchOperationSignal where
  messageDecoder = loop "" Nothing Nothing ""
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationSignal {batchOperationSignalSignal = acc_0, batchOperationSignalInput = acc_1, batchOperationSignalHeader = acc_2, batchOperationSignalIdentity = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2 acc_3
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (Just v) acc_3
            4 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON BatchOperationSignal where
  protoToJSON msg = jsonObject
      [ "signal" .= msg.batchOperationSignalSignal
      , "input" .= msg.batchOperationSignalInput
      , "header" .= msg.batchOperationSignalHeader
      , "identity" .= msg.batchOperationSignalIdentity
      ]

instance ProtoFromJSON BatchOperationSignal where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationSignalSignal <- obj .:? "signal"
    v_batchOperationSignalInput <- obj .:? "input"
    v_batchOperationSignalHeader <- obj .:? "header"
    v_batchOperationSignalIdentity <- obj .:? "identity"
    pure (BatchOperationSignal {
       batchOperationSignalSignal = v_batchOperationSignalSignal
      , batchOperationSignalInput = v_batchOperationSignalInput
      , batchOperationSignalHeader = v_batchOperationSignalHeader
      , batchOperationSignalIdentity = v_batchOperationSignalIdentity
    })
  protoFromJSON _ = Left "Expected JSON object"

data BatchOperationCancellation = BatchOperationCancellation
  { batchOperationCancellationIdentity :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationCancellation :: BatchOperationCancellation
defaultBatchOperationCancellation = BatchOperationCancellation
  { batchOperationCancellationIdentity = ""
  }

instance MessageEncode BatchOperationCancellation where
  buildMessage msg =
    (if msg.batchOperationCancellationIdentity == T.empty then mempty else encodeFieldString 1 msg.batchOperationCancellationIdentity)

instance MessageSize BatchOperationCancellation where
  messageSize msg =
    (if msg.batchOperationCancellationIdentity == T.empty then 0 else fieldTextSize 1 msg.batchOperationCancellationIdentity)

instance MessageDecode BatchOperationCancellation where
  messageDecoder = loop ""
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationCancellation {batchOperationCancellationIdentity = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON BatchOperationCancellation where
  protoToJSON msg = jsonObject
      [ "identity" .= msg.batchOperationCancellationIdentity

      ]

instance ProtoFromJSON BatchOperationCancellation where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationCancellationIdentity <- obj .:? "identity"
    pure (BatchOperationCancellation {
       batchOperationCancellationIdentity = v_batchOperationCancellationIdentity
    })
  protoFromJSON _ = Left "Expected JSON object"

data BatchOperationDeletion = BatchOperationDeletion
  { batchOperationDeletionIdentity :: !Text
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationDeletion :: BatchOperationDeletion
defaultBatchOperationDeletion = BatchOperationDeletion
  { batchOperationDeletionIdentity = ""
  }

instance MessageEncode BatchOperationDeletion where
  buildMessage msg =
    (if msg.batchOperationDeletionIdentity == T.empty then mempty else encodeFieldString 1 msg.batchOperationDeletionIdentity)

instance MessageSize BatchOperationDeletion where
  messageSize msg =
    (if msg.batchOperationDeletionIdentity == T.empty then 0 else fieldTextSize 1 msg.batchOperationDeletionIdentity)

instance MessageDecode BatchOperationDeletion where
  messageDecoder = loop ""
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationDeletion {batchOperationDeletionIdentity = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON BatchOperationDeletion where
  protoToJSON msg = jsonObject
      [ "identity" .= msg.batchOperationDeletionIdentity

      ]

instance ProtoFromJSON BatchOperationDeletion where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationDeletionIdentity <- obj .:? "identity"
    pure (BatchOperationDeletion {
       batchOperationDeletionIdentity = v_batchOperationDeletionIdentity
    })
  protoFromJSON _ = Left "Expected JSON object"

data BatchOperationReset = BatchOperationReset
  { batchOperationResetIdentity :: !Text
  , batchOperationResetOptions :: !(Maybe ResetOptions)
  , batchOperationResetResettype :: !ResetType
  , batchOperationResetResetreapplytype :: !ResetReapplyType
  , batchOperationResetPostresetoperations :: !(V.Vector PostResetOperation)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationReset :: BatchOperationReset
defaultBatchOperationReset = BatchOperationReset
  { batchOperationResetIdentity = ""
  , batchOperationResetOptions = Nothing
  , batchOperationResetResettype = (toEnum 0)
  , batchOperationResetResetreapplytype = (toEnum 0)
  , batchOperationResetPostresetoperations = V.empty
  }

instance MessageEncode BatchOperationReset where
  buildMessage msg =
    (if msg.batchOperationResetIdentity == T.empty then mempty else encodeFieldString 3 msg.batchOperationResetIdentity)
    <> (maybe mempty (\v -> encodeFieldMessage 4 v) msg.batchOperationResetOptions)
    <> (if fromEnum msg.batchOperationResetResettype == 0 then mempty else encodeFieldVarint 1 (fromIntegral (fromEnum msg.batchOperationResetResettype)))
    <> (if fromEnum msg.batchOperationResetResetreapplytype == 0 then mempty else encodeFieldVarint 2 (fromIntegral (fromEnum msg.batchOperationResetResetreapplytype)))
    <> V.foldl' (\acc v -> acc <> encodeFieldMessage 5 v) mempty msg.batchOperationResetPostresetoperations

instance MessageSize BatchOperationReset where
  messageSize msg =
    (if msg.batchOperationResetIdentity == T.empty then 0 else fieldTextSize 3 msg.batchOperationResetIdentity)
    + (maybe 0 (\v -> fieldMessageSize 4 (messageSize v)) msg.batchOperationResetOptions)
    + (if fromEnum msg.batchOperationResetResettype == 0 then 0 else fieldVarintSize 1 (fromIntegral (fromEnum msg.batchOperationResetResettype)))
    + (if fromEnum msg.batchOperationResetResetreapplytype == 0 then 0 else fieldVarintSize 2 (fromIntegral (fromEnum msg.batchOperationResetResetreapplytype)))
    + (V.foldl' (\acc v -> acc + fieldMessageSize 5 (messageSize v)) 0 msg.batchOperationResetPostresetoperations)

instance MessageDecode BatchOperationReset where
  messageDecoder = loop "" Nothing (toEnum 0) (toEnum 0) V.empty
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationReset {batchOperationResetIdentity = acc_0, batchOperationResetOptions = acc_1, batchOperationResetResettype = acc_2, batchOperationResetResetreapplytype = acc_3, batchOperationResetPostresetoperations = acc_4})
          Just (Tag fn wt) -> case fn of
            3 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3 acc_4
            4 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2 acc_3 acc_4
            1 -> do
              v <- decodeFieldEnum
              loop acc_0 acc_1 v acc_3 acc_4
            2 -> do
              v <- decodeFieldEnum
              loop acc_0 acc_1 acc_2 v acc_4
            5 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 (acc_4 <> V.singleton v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4

instance ProtoToJSON BatchOperationReset where
  protoToJSON msg = jsonObject
      [ "identity" .= msg.batchOperationResetIdentity
      , "options" .= msg.batchOperationResetOptions
      , "resetType" .= msg.batchOperationResetResettype
      , "resetReapplyType" .= msg.batchOperationResetResetreapplytype
      , "postResetOperations" .= msg.batchOperationResetPostresetoperations
      ]

instance ProtoFromJSON BatchOperationReset where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationResetIdentity <- obj .:? "identity"
    v_batchOperationResetOptions <- obj .:? "options"
    v_batchOperationResetResettype <- obj .:? "resetType"
    v_batchOperationResetResetreapplytype <- obj .:? "resetReapplyType"
    v_batchOperationResetPostresetoperations <- obj .:? "postResetOperations"
    pure (BatchOperationReset {
       batchOperationResetIdentity = v_batchOperationResetIdentity
      , batchOperationResetOptions = v_batchOperationResetOptions
      , batchOperationResetResettype = v_batchOperationResetResettype
      , batchOperationResetResetreapplytype = v_batchOperationResetResetreapplytype
      , batchOperationResetPostresetoperations = v_batchOperationResetPostresetoperations
    })
  protoFromJSON _ = Left "Expected JSON object"

data BatchOperationUpdateWorkflowExecutionOptions = BatchOperationUpdateWorkflowExecutionOptions
  { batchOperationUpdateWorkflowExecutionOptionsIdentity :: !Text
  , batchOperationUpdateWorkflowExecutionOptionsWorkflowexecutionoptions :: !(Maybe WorkflowExecutionOptions)
  , batchOperationUpdateWorkflowExecutionOptionsUpdatemask :: !(Maybe FieldMask)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationUpdateWorkflowExecutionOptions :: BatchOperationUpdateWorkflowExecutionOptions
defaultBatchOperationUpdateWorkflowExecutionOptions = BatchOperationUpdateWorkflowExecutionOptions
  { batchOperationUpdateWorkflowExecutionOptionsIdentity = ""
  , batchOperationUpdateWorkflowExecutionOptionsWorkflowexecutionoptions = Nothing
  , batchOperationUpdateWorkflowExecutionOptionsUpdatemask = Nothing
  }

instance MessageEncode BatchOperationUpdateWorkflowExecutionOptions where
  buildMessage msg =
    (if msg.batchOperationUpdateWorkflowExecutionOptionsIdentity == T.empty then mempty else encodeFieldString 1 msg.batchOperationUpdateWorkflowExecutionOptionsIdentity)
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.batchOperationUpdateWorkflowExecutionOptionsWorkflowexecutionoptions)
    <> (maybe mempty (\v -> encodeFieldMessage 3 v) msg.batchOperationUpdateWorkflowExecutionOptionsUpdatemask)

instance MessageSize BatchOperationUpdateWorkflowExecutionOptions where
  messageSize msg =
    (if msg.batchOperationUpdateWorkflowExecutionOptionsIdentity == T.empty then 0 else fieldTextSize 1 msg.batchOperationUpdateWorkflowExecutionOptionsIdentity)
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.batchOperationUpdateWorkflowExecutionOptionsWorkflowexecutionoptions)
    + (maybe 0 (\v -> fieldMessageSize 3 (messageSize v)) msg.batchOperationUpdateWorkflowExecutionOptionsUpdatemask)

instance MessageDecode BatchOperationUpdateWorkflowExecutionOptions where
  messageDecoder = loop "" Nothing Nothing
    where
      loop acc_0 acc_1 acc_2 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationUpdateWorkflowExecutionOptions {batchOperationUpdateWorkflowExecutionOptionsIdentity = acc_0, batchOperationUpdateWorkflowExecutionOptionsWorkflowexecutionoptions = acc_1, batchOperationUpdateWorkflowExecutionOptionsUpdatemask = acc_2})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (Just v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2

instance ProtoToJSON BatchOperationUpdateWorkflowExecutionOptions where
  protoToJSON msg = jsonObject
      [ "identity" .= msg.batchOperationUpdateWorkflowExecutionOptionsIdentity
      , "workflowExecutionOptions" .= msg.batchOperationUpdateWorkflowExecutionOptionsWorkflowexecutionoptions
      , "updateMask" .= msg.batchOperationUpdateWorkflowExecutionOptionsUpdatemask
      ]

instance ProtoFromJSON BatchOperationUpdateWorkflowExecutionOptions where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationUpdateWorkflowExecutionOptionsIdentity <- obj .:? "identity"
    v_batchOperationUpdateWorkflowExecutionOptionsWorkflowexecutionoptions <- obj .:? "workflowExecutionOptions"
    v_batchOperationUpdateWorkflowExecutionOptionsUpdatemask <- obj .:? "updateMask"
    pure (BatchOperationUpdateWorkflowExecutionOptions {
       batchOperationUpdateWorkflowExecutionOptionsIdentity = v_batchOperationUpdateWorkflowExecutionOptionsIdentity
      , batchOperationUpdateWorkflowExecutionOptionsWorkflowexecutionoptions = v_batchOperationUpdateWorkflowExecutionOptionsWorkflowexecutionoptions
      , batchOperationUpdateWorkflowExecutionOptionsUpdatemask = v_batchOperationUpdateWorkflowExecutionOptionsUpdatemask
    })
  protoFromJSON _ = Left "Expected JSON object"

data BatchOperationUnpauseActivities = BatchOperationUnpauseActivities
  { batchOperationUnpauseActivitiesIdentity :: !Text
  , batchOperationUnpauseActivitiesActivity :: !(Maybe BatchOperationUnpauseActivities'Activity)
  , batchOperationUnpauseActivitiesResetattempts :: {-# UNPACK #-} !Bool
  , batchOperationUnpauseActivitiesResetheartbeat :: {-# UNPACK #-} !Bool
  , batchOperationUnpauseActivitiesJitter :: !(Maybe Duration)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
data BatchOperationUnpauseActivities'Activity
  = BatchOperationUnpauseActivities'Type !Text
  | BatchOperationUnpauseActivities'MatchAll {-# UNPACK #-} !Bool
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationUnpauseActivities :: BatchOperationUnpauseActivities
defaultBatchOperationUnpauseActivities = BatchOperationUnpauseActivities
  { batchOperationUnpauseActivitiesIdentity = ""
  , batchOperationUnpauseActivitiesActivity = Nothing
  , batchOperationUnpauseActivitiesResetattempts = False
  , batchOperationUnpauseActivitiesResetheartbeat = False
  , batchOperationUnpauseActivitiesJitter = Nothing
  }

instance MessageEncode BatchOperationUnpauseActivities where
  buildMessage msg =
    (if msg.batchOperationUnpauseActivitiesIdentity == T.empty then mempty else encodeFieldString 1 msg.batchOperationUnpauseActivitiesIdentity)
    <> (case msg.batchOperationUnpauseActivitiesActivity of
      Nothing -> mempty
      Just (BatchOperationUnpauseActivities'Type v) -> encodeFieldString 2 v
      Just (BatchOperationUnpauseActivities'MatchAll v) -> encodeFieldBool 3 v)
    <> (if msg.batchOperationUnpauseActivitiesResetattempts == False then mempty else encodeFieldBool 4 msg.batchOperationUnpauseActivitiesResetattempts)
    <> (if msg.batchOperationUnpauseActivitiesResetheartbeat == False then mempty else encodeFieldBool 5 msg.batchOperationUnpauseActivitiesResetheartbeat)
    <> (maybe mempty (\v -> encodeFieldMessage 6 v) msg.batchOperationUnpauseActivitiesJitter)

instance MessageSize BatchOperationUnpauseActivities where
  messageSize msg =
    (if msg.batchOperationUnpauseActivitiesIdentity == T.empty then 0 else fieldTextSize 1 msg.batchOperationUnpauseActivitiesIdentity)
    + (case msg.batchOperationUnpauseActivitiesActivity of { Nothing -> 0; Just (BatchOperationUnpauseActivities'Type v) -> fieldTextSize 2 v
    ; Just (BatchOperationUnpauseActivities'MatchAll v) -> fieldBoolSize 3 })
    + (if msg.batchOperationUnpauseActivitiesResetattempts == False then 0 else fieldBoolSize 4)
    + (if msg.batchOperationUnpauseActivitiesResetheartbeat == False then 0 else fieldBoolSize 5)
    + (maybe 0 (\v -> fieldMessageSize 6 (messageSize v)) msg.batchOperationUnpauseActivitiesJitter)

instance MessageDecode BatchOperationUnpauseActivities where
  messageDecoder = loop "" Nothing False False Nothing
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationUnpauseActivities {batchOperationUnpauseActivitiesIdentity = acc_0, batchOperationUnpauseActivitiesActivity = acc_1, batchOperationUnpauseActivitiesResetattempts = acc_2, batchOperationUnpauseActivitiesResetheartbeat = acc_3, batchOperationUnpauseActivitiesJitter = acc_4})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3 acc_4
            2 -> do
              v <- decodeFieldString
              loop acc_0 (Just (BatchOperationUnpauseActivities'Type v)) acc_2 acc_3 acc_4
            3 -> do
              v <- decodeFieldBool
              loop acc_0 (Just (BatchOperationUnpauseActivities'MatchAll v)) acc_2 acc_3 acc_4
            4 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 v acc_3 acc_4
            5 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 v acc_4
            6 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 (Just v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4

instance ProtoToJSON BatchOperationUnpauseActivities where
  protoToJSON msg = jsonObject
      [ "identity" .= msg.batchOperationUnpauseActivitiesIdentity
      , "activity" .= msg.batchOperationUnpauseActivitiesActivity
      , "resetAttempts" .= msg.batchOperationUnpauseActivitiesResetattempts
      , "resetHeartbeat" .= msg.batchOperationUnpauseActivitiesResetheartbeat
      , "jitter" .= msg.batchOperationUnpauseActivitiesJitter
      ]

instance ProtoFromJSON BatchOperationUnpauseActivities where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationUnpauseActivitiesIdentity <- obj .:? "identity"
    v_batchOperationUnpauseActivitiesActivity <- obj .:? "activity"
    v_batchOperationUnpauseActivitiesResetattempts <- obj .:? "resetAttempts"
    v_batchOperationUnpauseActivitiesResetheartbeat <- obj .:? "resetHeartbeat"
    v_batchOperationUnpauseActivitiesJitter <- obj .:? "jitter"
    pure (BatchOperationUnpauseActivities {
       batchOperationUnpauseActivitiesIdentity = v_batchOperationUnpauseActivitiesIdentity
      , batchOperationUnpauseActivitiesActivity = v_batchOperationUnpauseActivitiesActivity
      , batchOperationUnpauseActivitiesResetattempts = v_batchOperationUnpauseActivitiesResetattempts
      , batchOperationUnpauseActivitiesResetheartbeat = v_batchOperationUnpauseActivitiesResetheartbeat
      , batchOperationUnpauseActivitiesJitter = v_batchOperationUnpauseActivitiesJitter
    })
  protoFromJSON _ = Left "Expected JSON object"

data BatchOperationTriggerWorkflowRule = BatchOperationTriggerWorkflowRule
  { batchOperationTriggerWorkflowRuleIdentity :: !Text
  , batchOperationTriggerWorkflowRuleRule :: !(Maybe BatchOperationTriggerWorkflowRule'Rule)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
data BatchOperationTriggerWorkflowRule'Rule
  = BatchOperationTriggerWorkflowRule'Id !Text
  | BatchOperationTriggerWorkflowRule'Spec !WorkflowRuleSpec
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationTriggerWorkflowRule :: BatchOperationTriggerWorkflowRule
defaultBatchOperationTriggerWorkflowRule = BatchOperationTriggerWorkflowRule
  { batchOperationTriggerWorkflowRuleIdentity = ""
  , batchOperationTriggerWorkflowRuleRule = Nothing
  }

instance MessageEncode BatchOperationTriggerWorkflowRule where
  buildMessage msg =
    (if msg.batchOperationTriggerWorkflowRuleIdentity == T.empty then mempty else encodeFieldString 1 msg.batchOperationTriggerWorkflowRuleIdentity)
    <> (case msg.batchOperationTriggerWorkflowRuleRule of
      Nothing -> mempty
      Just (BatchOperationTriggerWorkflowRule'Id v) -> encodeFieldString 2 v
      Just (BatchOperationTriggerWorkflowRule'Spec v) -> encodeFieldMessage 3 v)

instance MessageSize BatchOperationTriggerWorkflowRule where
  messageSize msg =
    (if msg.batchOperationTriggerWorkflowRuleIdentity == T.empty then 0 else fieldTextSize 1 msg.batchOperationTriggerWorkflowRuleIdentity)
    + (case msg.batchOperationTriggerWorkflowRuleRule of { Nothing -> 0; Just (BatchOperationTriggerWorkflowRule'Id v) -> fieldTextSize 2 v
    ; Just (BatchOperationTriggerWorkflowRule'Spec v) -> fieldMessageSize 3 (messageSize v) })

instance MessageDecode BatchOperationTriggerWorkflowRule where
  messageDecoder = loop "" Nothing
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationTriggerWorkflowRule {batchOperationTriggerWorkflowRuleIdentity = acc_0, batchOperationTriggerWorkflowRuleRule = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1
            2 -> do
              v <- decodeFieldString
              loop acc_0 (Just (BatchOperationTriggerWorkflowRule'Id v))
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just (BatchOperationTriggerWorkflowRule'Spec v))
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON BatchOperationTriggerWorkflowRule where
  protoToJSON msg = jsonObject
      [ "identity" .= msg.batchOperationTriggerWorkflowRuleIdentity
      , "rule" .= msg.batchOperationTriggerWorkflowRuleRule
      ]

instance ProtoFromJSON BatchOperationTriggerWorkflowRule where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationTriggerWorkflowRuleIdentity <- obj .:? "identity"
    v_batchOperationTriggerWorkflowRuleRule <- obj .:? "rule"
    pure (BatchOperationTriggerWorkflowRule {
       batchOperationTriggerWorkflowRuleIdentity = v_batchOperationTriggerWorkflowRuleIdentity
      , batchOperationTriggerWorkflowRuleRule = v_batchOperationTriggerWorkflowRuleRule
    })
  protoFromJSON _ = Left "Expected JSON object"

data BatchOperationResetActivities = BatchOperationResetActivities
  { batchOperationResetActivitiesIdentity :: !Text
  , batchOperationResetActivitiesActivity :: !(Maybe BatchOperationResetActivities'Activity)
  , batchOperationResetActivitiesResetattempts :: {-# UNPACK #-} !Bool
  , batchOperationResetActivitiesResetheartbeat :: {-# UNPACK #-} !Bool
  , batchOperationResetActivitiesKeeppaused :: {-# UNPACK #-} !Bool
  , batchOperationResetActivitiesJitter :: !(Maybe Duration)
  , batchOperationResetActivitiesRestoreoriginaloptions :: {-# UNPACK #-} !Bool
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
data BatchOperationResetActivities'Activity
  = BatchOperationResetActivities'Type !Text
  | BatchOperationResetActivities'MatchAll {-# UNPACK #-} !Bool
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationResetActivities :: BatchOperationResetActivities
defaultBatchOperationResetActivities = BatchOperationResetActivities
  { batchOperationResetActivitiesIdentity = ""
  , batchOperationResetActivitiesActivity = Nothing
  , batchOperationResetActivitiesResetattempts = False
  , batchOperationResetActivitiesResetheartbeat = False
  , batchOperationResetActivitiesKeeppaused = False
  , batchOperationResetActivitiesJitter = Nothing
  , batchOperationResetActivitiesRestoreoriginaloptions = False
  }

instance MessageEncode BatchOperationResetActivities where
  buildMessage msg =
    (if msg.batchOperationResetActivitiesIdentity == T.empty then mempty else encodeFieldString 1 msg.batchOperationResetActivitiesIdentity)
    <> (case msg.batchOperationResetActivitiesActivity of
      Nothing -> mempty
      Just (BatchOperationResetActivities'Type v) -> encodeFieldString 2 v
      Just (BatchOperationResetActivities'MatchAll v) -> encodeFieldBool 3 v)
    <> (if msg.batchOperationResetActivitiesResetattempts == False then mempty else encodeFieldBool 4 msg.batchOperationResetActivitiesResetattempts)
    <> (if msg.batchOperationResetActivitiesResetheartbeat == False then mempty else encodeFieldBool 5 msg.batchOperationResetActivitiesResetheartbeat)
    <> (if msg.batchOperationResetActivitiesKeeppaused == False then mempty else encodeFieldBool 6 msg.batchOperationResetActivitiesKeeppaused)
    <> (maybe mempty (\v -> encodeFieldMessage 7 v) msg.batchOperationResetActivitiesJitter)
    <> (if msg.batchOperationResetActivitiesRestoreoriginaloptions == False then mempty else encodeFieldBool 8 msg.batchOperationResetActivitiesRestoreoriginaloptions)

instance MessageSize BatchOperationResetActivities where
  messageSize msg =
    (if msg.batchOperationResetActivitiesIdentity == T.empty then 0 else fieldTextSize 1 msg.batchOperationResetActivitiesIdentity)
    + (case msg.batchOperationResetActivitiesActivity of { Nothing -> 0; Just (BatchOperationResetActivities'Type v) -> fieldTextSize 2 v
    ; Just (BatchOperationResetActivities'MatchAll v) -> fieldBoolSize 3 })
    + (if msg.batchOperationResetActivitiesResetattempts == False then 0 else fieldBoolSize 4)
    + (if msg.batchOperationResetActivitiesResetheartbeat == False then 0 else fieldBoolSize 5)
    + (if msg.batchOperationResetActivitiesKeeppaused == False then 0 else fieldBoolSize 6)
    + (maybe 0 (\v -> fieldMessageSize 7 (messageSize v)) msg.batchOperationResetActivitiesJitter)
    + (if msg.batchOperationResetActivitiesRestoreoriginaloptions == False then 0 else fieldBoolSize 8)

instance MessageDecode BatchOperationResetActivities where
  messageDecoder = loop "" Nothing False False False Nothing False
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationResetActivities {batchOperationResetActivitiesIdentity = acc_0, batchOperationResetActivitiesActivity = acc_1, batchOperationResetActivitiesResetattempts = acc_2, batchOperationResetActivitiesResetheartbeat = acc_3, batchOperationResetActivitiesKeeppaused = acc_4, batchOperationResetActivitiesJitter = acc_5, batchOperationResetActivitiesRestoreoriginaloptions = acc_6})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3 acc_4 acc_5 acc_6
            2 -> do
              v <- decodeFieldString
              loop acc_0 (Just (BatchOperationResetActivities'Type v)) acc_2 acc_3 acc_4 acc_5 acc_6
            3 -> do
              v <- decodeFieldBool
              loop acc_0 (Just (BatchOperationResetActivities'MatchAll v)) acc_2 acc_3 acc_4 acc_5 acc_6
            4 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 v acc_3 acc_4 acc_5 acc_6
            5 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 v acc_4 acc_5 acc_6
            6 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 acc_3 v acc_5 acc_6
            7 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 (Just v) acc_6
            8 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6

instance ProtoToJSON BatchOperationResetActivities where
  protoToJSON msg = jsonObject
      [ "identity" .= msg.batchOperationResetActivitiesIdentity
      , "activity" .= msg.batchOperationResetActivitiesActivity
      , "resetAttempts" .= msg.batchOperationResetActivitiesResetattempts
      , "resetHeartbeat" .= msg.batchOperationResetActivitiesResetheartbeat
      , "keepPaused" .= msg.batchOperationResetActivitiesKeeppaused
      , "jitter" .= msg.batchOperationResetActivitiesJitter
      , "restoreOriginalOptions" .= msg.batchOperationResetActivitiesRestoreoriginaloptions
      ]

instance ProtoFromJSON BatchOperationResetActivities where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationResetActivitiesIdentity <- obj .:? "identity"
    v_batchOperationResetActivitiesActivity <- obj .:? "activity"
    v_batchOperationResetActivitiesResetattempts <- obj .:? "resetAttempts"
    v_batchOperationResetActivitiesResetheartbeat <- obj .:? "resetHeartbeat"
    v_batchOperationResetActivitiesKeeppaused <- obj .:? "keepPaused"
    v_batchOperationResetActivitiesJitter <- obj .:? "jitter"
    v_batchOperationResetActivitiesRestoreoriginaloptions <- obj .:? "restoreOriginalOptions"
    pure (BatchOperationResetActivities {
       batchOperationResetActivitiesIdentity = v_batchOperationResetActivitiesIdentity
      , batchOperationResetActivitiesActivity = v_batchOperationResetActivitiesActivity
      , batchOperationResetActivitiesResetattempts = v_batchOperationResetActivitiesResetattempts
      , batchOperationResetActivitiesResetheartbeat = v_batchOperationResetActivitiesResetheartbeat
      , batchOperationResetActivitiesKeeppaused = v_batchOperationResetActivitiesKeeppaused
      , batchOperationResetActivitiesJitter = v_batchOperationResetActivitiesJitter
      , batchOperationResetActivitiesRestoreoriginaloptions = v_batchOperationResetActivitiesRestoreoriginaloptions
    })
  protoFromJSON _ = Left "Expected JSON object"

data BatchOperationUpdateActivityOptions = BatchOperationUpdateActivityOptions
  { batchOperationUpdateActivityOptionsIdentity :: !Text
  , batchOperationUpdateActivityOptionsActivity :: !(Maybe BatchOperationUpdateActivityOptions'Activity)
  , batchOperationUpdateActivityOptionsActivityoptions :: !(Maybe ActivityOptions)
  , batchOperationUpdateActivityOptionsUpdatemask :: !(Maybe FieldMask)
  , batchOperationUpdateActivityOptionsRestoreoriginal :: {-# UNPACK #-} !Bool
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
data BatchOperationUpdateActivityOptions'Activity
  = BatchOperationUpdateActivityOptions'Type !Text
  | BatchOperationUpdateActivityOptions'MatchAll {-# UNPACK #-} !Bool
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBatchOperationUpdateActivityOptions :: BatchOperationUpdateActivityOptions
defaultBatchOperationUpdateActivityOptions = BatchOperationUpdateActivityOptions
  { batchOperationUpdateActivityOptionsIdentity = ""
  , batchOperationUpdateActivityOptionsActivity = Nothing
  , batchOperationUpdateActivityOptionsActivityoptions = Nothing
  , batchOperationUpdateActivityOptionsUpdatemask = Nothing
  , batchOperationUpdateActivityOptionsRestoreoriginal = False
  }

instance MessageEncode BatchOperationUpdateActivityOptions where
  buildMessage msg =
    (if msg.batchOperationUpdateActivityOptionsIdentity == T.empty then mempty else encodeFieldString 1 msg.batchOperationUpdateActivityOptionsIdentity)
    <> (case msg.batchOperationUpdateActivityOptionsActivity of
      Nothing -> mempty
      Just (BatchOperationUpdateActivityOptions'Type v) -> encodeFieldString 2 v
      Just (BatchOperationUpdateActivityOptions'MatchAll v) -> encodeFieldBool 3 v)
    <> (maybe mempty (\v -> encodeFieldMessage 4 v) msg.batchOperationUpdateActivityOptionsActivityoptions)
    <> (maybe mempty (\v -> encodeFieldMessage 5 v) msg.batchOperationUpdateActivityOptionsUpdatemask)
    <> (if msg.batchOperationUpdateActivityOptionsRestoreoriginal == False then mempty else encodeFieldBool 6 msg.batchOperationUpdateActivityOptionsRestoreoriginal)

instance MessageSize BatchOperationUpdateActivityOptions where
  messageSize msg =
    (if msg.batchOperationUpdateActivityOptionsIdentity == T.empty then 0 else fieldTextSize 1 msg.batchOperationUpdateActivityOptionsIdentity)
    + (case msg.batchOperationUpdateActivityOptionsActivity of { Nothing -> 0; Just (BatchOperationUpdateActivityOptions'Type v) -> fieldTextSize 2 v
    ; Just (BatchOperationUpdateActivityOptions'MatchAll v) -> fieldBoolSize 3 })
    + (maybe 0 (\v -> fieldMessageSize 4 (messageSize v)) msg.batchOperationUpdateActivityOptionsActivityoptions)
    + (maybe 0 (\v -> fieldMessageSize 5 (messageSize v)) msg.batchOperationUpdateActivityOptionsUpdatemask)
    + (if msg.batchOperationUpdateActivityOptionsRestoreoriginal == False then 0 else fieldBoolSize 6)

instance MessageDecode BatchOperationUpdateActivityOptions where
  messageDecoder = loop "" Nothing Nothing Nothing False
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BatchOperationUpdateActivityOptions {batchOperationUpdateActivityOptionsIdentity = acc_0, batchOperationUpdateActivityOptionsActivity = acc_1, batchOperationUpdateActivityOptionsActivityoptions = acc_2, batchOperationUpdateActivityOptionsUpdatemask = acc_3, batchOperationUpdateActivityOptionsRestoreoriginal = acc_4})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3 acc_4
            2 -> do
              v <- decodeFieldString
              loop acc_0 (Just (BatchOperationUpdateActivityOptions'Type v)) acc_2 acc_3 acc_4
            3 -> do
              v <- decodeFieldBool
              loop acc_0 (Just (BatchOperationUpdateActivityOptions'MatchAll v)) acc_2 acc_3 acc_4
            4 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (Just v) acc_3 acc_4
            5 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 (Just v) acc_4
            6 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 acc_3 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4

instance ProtoToJSON BatchOperationUpdateActivityOptions where
  protoToJSON msg = jsonObject
      [ "identity" .= msg.batchOperationUpdateActivityOptionsIdentity
      , "activity" .= msg.batchOperationUpdateActivityOptionsActivity
      , "activityOptions" .= msg.batchOperationUpdateActivityOptionsActivityoptions
      , "updateMask" .= msg.batchOperationUpdateActivityOptionsUpdatemask
      , "restoreOriginal" .= msg.batchOperationUpdateActivityOptionsRestoreoriginal
      ]

instance ProtoFromJSON BatchOperationUpdateActivityOptions where
  protoFromJSON (JsonObject obj) = do
    v_batchOperationUpdateActivityOptionsIdentity <- obj .:? "identity"
    v_batchOperationUpdateActivityOptionsActivity <- obj .:? "activity"
    v_batchOperationUpdateActivityOptionsActivityoptions <- obj .:? "activityOptions"
    v_batchOperationUpdateActivityOptionsUpdatemask <- obj .:? "updateMask"
    v_batchOperationUpdateActivityOptionsRestoreoriginal <- obj .:? "restoreOriginal"
    pure (BatchOperationUpdateActivityOptions {
       batchOperationUpdateActivityOptionsIdentity = v_batchOperationUpdateActivityOptionsIdentity
      , batchOperationUpdateActivityOptionsActivity = v_batchOperationUpdateActivityOptionsActivity
      , batchOperationUpdateActivityOptionsActivityoptions = v_batchOperationUpdateActivityOptionsActivityoptions
      , batchOperationUpdateActivityOptionsUpdatemask = v_batchOperationUpdateActivityOptionsUpdatemask
      , batchOperationUpdateActivityOptionsRestoreoriginal = v_batchOperationUpdateActivityOptionsRestoreoriginal
    })
  protoFromJSON _ = Left "Expected JSON object"