-- | Code generation for Haskell modules from parsed proto files.
--
-- Generates complete, compilable Haskell modules with Haddock documentation.
module Proto.CodeGen
  ( generateModule
  , generateModuleText
  , GenerateOpts (..)
  , defaultGenerateOpts
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Prettyprinter
import Prettyprinter.Render.Text (renderStrict)

import Proto.AST
import Proto.CodeGen.Types
import Proto.CodeGen.Encode (genEncodeInstance, genSizeInstance)
import Proto.CodeGen.Decode (genDecodeInstance)
import Proto.Options

data GenerateOpts = GenerateOpts
  { genModulePrefix    :: Text
  , genStrictFields    :: Bool
  , genUnpackPrims     :: Bool
  , genDeriveGeneric   :: Bool
  , genDeriveNFData    :: Bool
  , genPackedRepeated  :: Bool
  , genLazySubmessages :: Bool
  } deriving stock (Show, Eq)

defaultGenerateOpts :: GenerateOpts
defaultGenerateOpts = GenerateOpts
  { genModulePrefix    = "Proto.Gen"
  , genStrictFields    = True
  , genUnpackPrims     = True
  , genDeriveGeneric   = True
  , genDeriveNFData    = True
  , genPackedRepeated  = True
  , genLazySubmessages = False
  }

generateModule :: GenerateOpts -> ProtoFile -> Doc ann
generateModule opts pf =
  vsep
    [ genModuleHeader opts pf
    , mempty
    , genImports
    , mempty
    , vsep (concatMap (genTopLevel (protoPackage pf)) (protoTopLevels pf))
    ]

generateModuleText :: GenerateOpts -> ProtoFile -> Text
generateModuleText opts pf =
  renderStrict (layoutPretty defaultLayoutOptions (generateModule opts pf))

genModuleHeader :: GenerateOpts -> ProtoFile -> Doc ann
genModuleHeader opts pf =
  let modName = case protoPackage pf of
        Just pkg -> genModulePrefix opts <> "." <> hsModuleName pkg
        Nothing  -> genModulePrefix opts <> ".Generated"
      pkgDoc = maybe "" (\p -> " from package @" <> p <> "@") (protoPackage pf)
      lp = extractLanguagePackages pf
      langLines = concatMap (\(lbl, mval) -> case mval of
        Nothing -> []
        Just v  -> [pretty ("-- " :: Text) <> pretty lbl <> pretty (": " :: Text) <> pretty v]) langMappings
      langMappings =
        [ ("Java package" :: Text, lpJavaPackage lp)
        , ("Go package", lpGoPackage lp)
        , ("C# namespace", lpCsharpNamespace lp)
        , ("PHP namespace", lpPhpNamespace lp)
        , ("Ruby package", lpRubyPackage lp)
        , ("Swift prefix", lpSwiftPrefix lp)
        , ("ObjC prefix", lpObjcPrefix lp)
        ]
      fo = extractFileOptions (protoOptions pf)
      deprLine = if foDeprecated fo
        then [pretty ("--" :: Text), pretty ("-- __This file is deprecated.__" :: Text)]
        else []
  in vsep $
    [ pretty ("{-# LANGUAGE StrictData #-}" :: Text)
    , pretty ("{-# LANGUAGE DeriveGeneric #-}" :: Text)
    , pretty ("{-# LANGUAGE DeriveAnyClass #-}" :: Text)
    , pretty ("{-# LANGUAGE DerivingStrategies #-}" :: Text)
    , pretty ("{-# LANGUAGE OverloadedStrings #-}" :: Text)
    , pretty ("{-# LANGUAGE BangPatterns #-}" :: Text)
    , pretty ("-- | Auto-generated protobuf types" :: Text) <> pretty pkgDoc <> pretty ("." :: Text)
    , pretty ("--" :: Text)
    , pretty ("-- Generated by hs-proto. Do not edit." :: Text)
    ]
    <> (if null langLines then [] else pretty ("--" :: Text) : pretty ("-- Cross-language packages:" :: Text) : langLines)
    <> deprLine
    <> [ pretty ("module" :: Text) <+> pretty modName <+> pretty ("where" :: Text) ]

genImports :: Doc ann
genImports = vsep
  [ pretty ("import Data.ByteString (ByteString)" :: Text)
  , pretty ("import qualified Data.ByteString as BS" :: Text)
  , pretty ("import qualified Data.ByteString.Builder as B" :: Text)
  , pretty ("import Data.Int (Int32, Int64)" :: Text)
  , pretty ("import Data.Text (Text)" :: Text)
  , pretty ("import Data.Word (Word32, Word64)" :: Text)
  , pretty ("import qualified Data.Map.Strict as Map" :: Text)
  , pretty ("import qualified Data.Vector as V" :: Text)
  , pretty ("import qualified Data.Vector.Unboxed as VU" :: Text)
  , pretty ("import GHC.Generics (Generic)" :: Text)
  , pretty ("import Control.DeepSeq (NFData(..))" :: Text)
  , pretty ("import Proto.Encode" :: Text)
  , pretty ("import Proto.Decode" :: Text)
  , pretty ("import Proto.Wire (Tag(..), WireType(..))" :: Text)
  , pretty ("import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64," :: Text)
  , pretty ("  putFloat, putDouble, putText, putByteString, putLengthDelimited," :: Text)
  , pretty ("  putSVarint32, putSVarint64, putVarintSigned," :: Text)
  , pretty ("  varintSize, tagSize, fieldMessageSize)" :: Text)
  ]

genTopLevel :: Maybe Text -> TopLevel -> [Doc ann]
genTopLevel pkg = genTopLevelScoped pkg []

genTopLevelScoped :: Maybe Text -> [Text] -> TopLevel -> [Doc ann]
genTopLevelScoped pkg scope = \case
  TLMessage msg ->
    let scope' = scope <> [msgName msg]
        tyN = hsScopedTypeName scope (msgName msg)
        mopts = extractMessageOptions (concatMap msgOpts (msgElements msg))
    in genMessageDoc pkg msg : genTypeDecls msg
    <> (if moDeprecated mopts
        then [pretty ("{-# DEPRECATED " :: Text) <> pretty tyN
              <+> pretty ("\"This message is deprecated in the proto schema.\" #-}" :: Text)]
        else [])
    <> genDeprecatedFieldPragmas scope' msg
    <> [ mempty
       , genDefaultDoc msg
       , genDefaultInstance scope' msg
       , mempty
       , genEncodeInstance msg
       , mempty
       , genMessageSizeInstance msg
       , mempty
       , genDecodeInstance msg
       ]
  TLEnum ed ->
    let tyN = hsScopedTypeName scope (enumName ed)
        eopts = extractEnumOptions (enumOptions ed)
    in [ genEnumDoc ed
       , genEnumDecl ed
       ]
    <> (if eoDeprecated eopts
        then [pretty ("{-# DEPRECATED " :: Text) <> pretty tyN
              <+> pretty ("\"This enum is deprecated in the proto schema.\" #-}" :: Text)]
        else [])
    <> [ mempty
       , genEnumProtoInstance scope ed
       ]
  TLService _svc -> []
  TLExtend _ _   -> []
  TLOption _     -> []
  where
    msgOpts (MEOption o) = [o]
    msgOpts _            = []

genDeprecatedFieldPragmas :: [Text] -> MessageDef -> [Doc ann]
genDeprecatedFieldPragmas scope msg =
  concatMap go (msgElements msg)
  where
    go (MEField fd) =
      if isDeprecated (fieldOptions fd)
      then [pretty ("{-# DEPRECATED " :: Text) <> pretty (hsScopedFieldName scope (fieldName fd))
            <+> pretty ("\"This field is deprecated in the proto schema.\" #-}" :: Text)]
      else []
    go _ = []

-- Haddock comment generators

genMessageDoc :: Maybe Text -> MessageDef -> Doc ann
genMessageDoc pkg msg =
  let qualified = maybe (msgName msg) (\p -> p <> "." <> msgName msg) pkg
      fieldDocs = concatMap extractFieldDoc (msgElements msg)
  in vsep $
    [ pretty ("-- | Protobuf message @" :: Text) <> pretty qualified <> pretty ("@." :: Text)
    , pretty ("--" :: Text)
    , pretty ("-- Fields:" :: Text)
    ] <>
    fmap (\(fn, ft, fnum) ->
      pretty ("--" :: Text) <> line <>
      pretty ("-- * @" :: Text) <> pretty fn <> pretty ("@ (" :: Text) <>
      pretty ft <> pretty (", field " :: Text) <> pretty (T.pack (show fnum)) <>
      pretty (")" :: Text)
    ) fieldDocs <>
    [ mempty ]

extractFieldDoc :: MessageElement -> [(Text, Text, Int)]
extractFieldDoc = \case
  MEField fd ->
    [(fieldName fd, showFieldType (fieldType fd), unFieldNumber (fieldNumber fd))]
  MEMapField mf ->
    [(mapFieldName mf, "map<" <> showScalar (mapKeyType mf) <> ", " <> showFieldType (mapValueType mf) <> ">", unFieldNumber (mapFieldNum mf))]
  MEOneof od ->
    fmap (\f -> (oneofFieldName f, "oneof " <> oneofName od <> ": " <> showFieldType (oneofFieldType f), unFieldNumber (oneofFieldNumber f))) (oneofFields od)
  _ -> []

showFieldType :: FieldType -> Text
showFieldType = \case
  FTScalar s -> showScalar s
  FTNamed n  -> n

showScalar :: ScalarType -> Text
showScalar = \case
  SDouble   -> "double"
  SFloat    -> "float"
  SInt32    -> "int32"
  SInt64    -> "int64"
  SUInt32   -> "uint32"
  SUInt64   -> "uint64"
  SSInt32   -> "sint32"
  SSInt64   -> "sint64"
  SFixed32  -> "fixed32"
  SFixed64  -> "fixed64"
  SSFixed32 -> "sfixed32"
  SSFixed64 -> "sfixed64"
  SBool     -> "bool"
  SString   -> "string"
  SBytes    -> "bytes"

genDefaultDoc :: MessageDef -> Doc ann
genDefaultDoc msg =
  pretty ("-- | Default value for @" :: Text) <> pretty (msgName msg) <>
  pretty ("@ with all fields set to their proto default." :: Text)

genEnumDoc :: EnumDef -> Doc ann
genEnumDoc ed =
  let vals = enumValues ed
  in vsep $
    [ pretty ("-- | Protobuf enum @" :: Text) <> pretty (enumName ed) <> pretty ("@." :: Text)
    , pretty ("--" :: Text)
    , pretty ("-- Values:" :: Text)
    ] <>
    fmap (\ev ->
      pretty ("--" :: Text) <> line <>
      pretty ("-- * @" :: Text) <> pretty (evName ev) <> pretty ("@ = " :: Text) <>
      pretty (T.pack (show (evNumber ev)))
    ) vals <>
    [ mempty ]

-- Default and enum instance generation (unchanged except for doc additions)

genDefaultInstance :: [Text] -> MessageDef -> Doc ann
genDefaultInstance scope msg =
  let tyN = T.intercalate "'" (fmap hsTypeName scope)
  in vsep
    [ pretty ("default" :: Text) <> pretty tyN <+> pretty ("::" :: Text) <+> pretty tyN
    , pretty ("default" :: Text) <> pretty tyN <+> pretty ("=" :: Text) <+> pretty tyN
    , indent 2 (genDefaultFields scope (msgElements msg))
    ]

genDefaultFields :: [Text] -> [MessageElement] -> Doc ann
genDefaultFields scope elems =
  let fields = concatMap extractDefault elems
  in case fields of
    []     -> pretty ("{ }" :: Text)
    (f:fs) -> vsep (pretty ("{ " :: Text) <> f : fmap (\x -> pretty (", " :: Text) <> x) fs) <> line <> pretty ("}" :: Text)
  where
    extractDefault = \case
      MEField fd ->
        [pretty (hsScopedFieldName scope (fieldName fd)) <+> pretty ("=" :: Text) <+> defaultValue (fieldLabel fd) (fieldType fd)]
      MEMapField mf ->
        [pretty (hsScopedFieldName scope (mapFieldName mf)) <+> pretty ("=" :: Text) <+> pretty ("Map.empty" :: Text)]
      MEOneof od ->
        [pretty (hsScopedFieldName scope (oneofName od)) <+> pretty ("=" :: Text) <+> pretty ("Nothing" :: Text)]
      _ -> []

    defaultValue lbl ft = case lbl of
      Just Repeated -> case ft of
        FTScalar s | isUnboxableScalar s -> pretty ("VU.empty" :: Text)
        _                                -> pretty ("V.empty" :: Text)
      Just Optional -> pretty ("Nothing" :: Text)
      _ -> case ft of
        FTScalar SBool   -> pretty ("False" :: Text)
        FTScalar SString -> pretty ("\"\"" :: Text)
        FTScalar SBytes  -> pretty ("\"\"" :: Text)
        FTScalar _       -> pretty ("0" :: Text)
        FTNamed _        -> pretty ("Nothing" :: Text)

    isUnboxableScalar = \case
      SString -> False
      SBytes  -> False
      _       -> True

genMessageSizeInstance :: MessageDef -> Doc ann
genMessageSizeInstance = genSizeInstance

genEnumProtoInstance :: [Text] -> EnumDef -> Doc ann
genEnumProtoInstance scope ed =
  let tyN = hsScopedTypeName scope (enumName ed)
      genToProto ev =
        pretty ("toProtoEnum" :: Text) <> pretty tyN <+>
        pretty (hsScopedEnumCon scope (enumName ed) (evName ev)) <+> pretty ("=" :: Text) <+>
        pretty (T.pack (show (evNumber ev)))
      genFromProto ev =
        pretty ("fromProtoEnum" :: Text) <> pretty tyN <+>
        pretty (T.pack (show (evNumber ev))) <+> pretty ("= Just" :: Text) <+>
        pretty (hsScopedEnumCon scope (enumName ed) (evName ev))
  in vsep
    [ pretty ("-- | Convert @" :: Text) <> pretty tyN <> pretty ("@ to its proto numeric value." :: Text)
    , pretty ("toProtoEnum" :: Text) <> pretty tyN <+>
      pretty ("::" :: Text) <+> pretty tyN <+> pretty ("-> Int" :: Text)
    , vsep (fmap genToProto (enumValues ed))
    , mempty
    , pretty ("-- | Convert a proto numeric value to @" :: Text) <> pretty tyN <> pretty ("@." :: Text)
    , pretty ("fromProtoEnum" :: Text) <> pretty tyN <+>
      pretty ("::" :: Text) <+> pretty ("Int ->" :: Text) <+> pretty ("Maybe" :: Text) <+> pretty tyN
    , vsep (fmap genFromProto (enumValues ed))
    , pretty ("fromProtoEnum" :: Text) <> pretty tyN <+>
      pretty ("_ = Nothing" :: Text)
    ]
