{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @temporal.api.namespace.v1@.
--
-- Generated by hs-proto. Do not edit.
module Proto.Temporal.Temporal.Api.Namespace.V1.Message where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Proto.Encode
import Proto.Decode
import Proto.JSON
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Google.Protobuf.Duration (Duration(..))
import Proto.Google.Protobuf.Timestamp (Timestamp(..))
import Proto.Temporal.Temporal.Api.Enums.V1.Namespace (ArchivalState(..), NamespaceState(..))


data NamespaceInfo = NamespaceInfo
  { namespaceInfoName :: !Text
  , namespaceInfoState :: !NamespaceState
  , namespaceInfoDescription :: !Text
  , namespaceInfoOwneremail :: !Text
  , namespaceInfoData :: !(Map.Map Text Text)
  , namespaceInfoId :: !Text
  , namespaceInfoCapabilities :: !(Maybe NamespaceInfo'Capabilities)
  , namespaceInfoLimits :: !(Maybe NamespaceInfo'Limits)
  , namespaceInfoSupportsschedules :: {-# UNPACK #-} !Bool
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

data NamespaceInfo'Capabilities = NamespaceInfo'Capabilities
  { namespaceInfoCapabilitiesEagerworkflowstart :: {-# UNPACK #-} !Bool
  , namespaceInfoCapabilitiesSyncupdate :: {-# UNPACK #-} !Bool
  , namespaceInfoCapabilitiesAsyncupdate :: {-# UNPACK #-} !Bool
  , namespaceInfoCapabilitiesWorkerheartbeats :: {-# UNPACK #-} !Bool
  , namespaceInfoCapabilitiesReportedproblemssearchattribute :: {-# UNPACK #-} !Bool
  , namespaceInfoCapabilitiesWorkflowpause :: {-# UNPACK #-} !Bool
  , namespaceInfoCapabilitiesStandaloneactivities :: {-# UNPACK #-} !Bool
  , namespaceInfoCapabilitiesWorkerpollcompleteonshutdown :: {-# UNPACK #-} !Bool
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultNamespaceInfo'Capabilities :: NamespaceInfo'Capabilities
defaultNamespaceInfo'Capabilities = NamespaceInfo'Capabilities
  { namespaceInfoCapabilitiesEagerworkflowstart = False
  , namespaceInfoCapabilitiesSyncupdate = False
  , namespaceInfoCapabilitiesAsyncupdate = False
  , namespaceInfoCapabilitiesWorkerheartbeats = False
  , namespaceInfoCapabilitiesReportedproblemssearchattribute = False
  , namespaceInfoCapabilitiesWorkflowpause = False
  , namespaceInfoCapabilitiesStandaloneactivities = False
  , namespaceInfoCapabilitiesWorkerpollcompleteonshutdown = False
  }

instance MessageEncode NamespaceInfo'Capabilities where
  buildMessage msg =
    (if msg.namespaceInfoCapabilitiesEagerworkflowstart == False then mempty else encodeFieldBool 1 msg.namespaceInfoCapabilitiesEagerworkflowstart)
    <> (if msg.namespaceInfoCapabilitiesSyncupdate == False then mempty else encodeFieldBool 2 msg.namespaceInfoCapabilitiesSyncupdate)
    <> (if msg.namespaceInfoCapabilitiesAsyncupdate == False then mempty else encodeFieldBool 3 msg.namespaceInfoCapabilitiesAsyncupdate)
    <> (if msg.namespaceInfoCapabilitiesWorkerheartbeats == False then mempty else encodeFieldBool 4 msg.namespaceInfoCapabilitiesWorkerheartbeats)
    <> (if msg.namespaceInfoCapabilitiesReportedproblemssearchattribute == False then mempty else encodeFieldBool 5 msg.namespaceInfoCapabilitiesReportedproblemssearchattribute)
    <> (if msg.namespaceInfoCapabilitiesWorkflowpause == False then mempty else encodeFieldBool 6 msg.namespaceInfoCapabilitiesWorkflowpause)
    <> (if msg.namespaceInfoCapabilitiesStandaloneactivities == False then mempty else encodeFieldBool 7 msg.namespaceInfoCapabilitiesStandaloneactivities)
    <> (if msg.namespaceInfoCapabilitiesWorkerpollcompleteonshutdown == False then mempty else encodeFieldBool 8 msg.namespaceInfoCapabilitiesWorkerpollcompleteonshutdown)

instance MessageSize NamespaceInfo'Capabilities where
  messageSize msg =
    (if msg.namespaceInfoCapabilitiesEagerworkflowstart == False then 0 else fieldBoolSize 1)
    + (if msg.namespaceInfoCapabilitiesSyncupdate == False then 0 else fieldBoolSize 2)
    + (if msg.namespaceInfoCapabilitiesAsyncupdate == False then 0 else fieldBoolSize 3)
    + (if msg.namespaceInfoCapabilitiesWorkerheartbeats == False then 0 else fieldBoolSize 4)
    + (if msg.namespaceInfoCapabilitiesReportedproblemssearchattribute == False then 0 else fieldBoolSize 5)
    + (if msg.namespaceInfoCapabilitiesWorkflowpause == False then 0 else fieldBoolSize 6)
    + (if msg.namespaceInfoCapabilitiesStandaloneactivities == False then 0 else fieldBoolSize 7)
    + (if msg.namespaceInfoCapabilitiesWorkerpollcompleteonshutdown == False then 0 else fieldBoolSize 8)

instance MessageDecode NamespaceInfo'Capabilities where
  messageDecoder = loop False False False False False False False False
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (NamespaceInfo'Capabilities {namespaceInfoCapabilitiesEagerworkflowstart = acc_0, namespaceInfoCapabilitiesSyncupdate = acc_1, namespaceInfoCapabilitiesAsyncupdate = acc_2, namespaceInfoCapabilitiesWorkerheartbeats = acc_3, namespaceInfoCapabilitiesReportedproblemssearchattribute = acc_4, namespaceInfoCapabilitiesWorkflowpause = acc_5, namespaceInfoCapabilitiesStandaloneactivities = acc_6, namespaceInfoCapabilitiesWorkerpollcompleteonshutdown = acc_7})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldBool
              loop v acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7
            2 -> do
              v <- decodeFieldBool
              loop acc_0 v acc_2 acc_3 acc_4 acc_5 acc_6 acc_7
            3 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 v acc_3 acc_4 acc_5 acc_6 acc_7
            4 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 v acc_4 acc_5 acc_6 acc_7
            5 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 acc_3 v acc_5 acc_6 acc_7
            6 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 acc_3 acc_4 v acc_6 acc_7
            7 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 v acc_7
            8 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7

instance ProtoToJSON NamespaceInfo'Capabilities where
  protoToJSON msg = jsonObject
      [ "eagerWorkflowStart" .= msg.namespaceInfoCapabilitiesEagerworkflowstart
      , "syncUpdate" .= msg.namespaceInfoCapabilitiesSyncupdate
      , "asyncUpdate" .= msg.namespaceInfoCapabilitiesAsyncupdate
      , "workerHeartbeats" .= msg.namespaceInfoCapabilitiesWorkerheartbeats
      , "reportedProblemsSearchAttribute" .= msg.namespaceInfoCapabilitiesReportedproblemssearchattribute
      , "workflowPause" .= msg.namespaceInfoCapabilitiesWorkflowpause
      , "standaloneActivities" .= msg.namespaceInfoCapabilitiesStandaloneactivities
      , "workerPollCompleteOnShutdown" .= msg.namespaceInfoCapabilitiesWorkerpollcompleteonshutdown
      ]

instance ProtoFromJSON NamespaceInfo'Capabilities where
  protoFromJSON (JsonObject obj) = do
    fld_namespaceInfoCapabilitiesEagerworkflowstart <- obj .:? "eagerWorkflowStart"
    fld_namespaceInfoCapabilitiesSyncupdate <- obj .:? "syncUpdate"
    fld_namespaceInfoCapabilitiesAsyncupdate <- obj .:? "asyncUpdate"
    fld_namespaceInfoCapabilitiesWorkerheartbeats <- obj .:? "workerHeartbeats"
    fld_namespaceInfoCapabilitiesReportedproblemssearchattribute <- obj .:? "reportedProblemsSearchAttribute"
    fld_namespaceInfoCapabilitiesWorkflowpause <- obj .:? "workflowPause"
    fld_namespaceInfoCapabilitiesStandaloneactivities <- obj .:? "standaloneActivities"
    fld_namespaceInfoCapabilitiesWorkerpollcompleteonshutdown <- obj .:? "workerPollCompleteOnShutdown"
    pure defaultNamespaceInfo'Capabilities
      { namespaceInfoCapabilitiesEagerworkflowstart = maybe (namespaceInfoCapabilitiesEagerworkflowstart defaultNamespaceInfo'Capabilities) id fld_namespaceInfoCapabilitiesEagerworkflowstart
      , namespaceInfoCapabilitiesSyncupdate = maybe (namespaceInfoCapabilitiesSyncupdate defaultNamespaceInfo'Capabilities) id fld_namespaceInfoCapabilitiesSyncupdate
      , namespaceInfoCapabilitiesAsyncupdate = maybe (namespaceInfoCapabilitiesAsyncupdate defaultNamespaceInfo'Capabilities) id fld_namespaceInfoCapabilitiesAsyncupdate
      , namespaceInfoCapabilitiesWorkerheartbeats = maybe (namespaceInfoCapabilitiesWorkerheartbeats defaultNamespaceInfo'Capabilities) id fld_namespaceInfoCapabilitiesWorkerheartbeats
      , namespaceInfoCapabilitiesReportedproblemssearchattribute = maybe (namespaceInfoCapabilitiesReportedproblemssearchattribute defaultNamespaceInfo'Capabilities) id fld_namespaceInfoCapabilitiesReportedproblemssearchattribute
      , namespaceInfoCapabilitiesWorkflowpause = maybe (namespaceInfoCapabilitiesWorkflowpause defaultNamespaceInfo'Capabilities) id fld_namespaceInfoCapabilitiesWorkflowpause
      , namespaceInfoCapabilitiesStandaloneactivities = maybe (namespaceInfoCapabilitiesStandaloneactivities defaultNamespaceInfo'Capabilities) id fld_namespaceInfoCapabilitiesStandaloneactivities
      , namespaceInfoCapabilitiesWorkerpollcompleteonshutdown = maybe (namespaceInfoCapabilitiesWorkerpollcompleteonshutdown defaultNamespaceInfo'Capabilities) id fld_namespaceInfoCapabilitiesWorkerpollcompleteonshutdown
      }
  protoFromJSON _ = Right defaultNamespaceInfo'Capabilities

data NamespaceInfo'Limits = NamespaceInfo'Limits
  { namespaceInfoLimitsBlobsizelimiterror :: {-# UNPACK #-} !Int64
  , namespaceInfoLimitsMemosizelimiterror :: {-# UNPACK #-} !Int64
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultNamespaceInfo'Limits :: NamespaceInfo'Limits
defaultNamespaceInfo'Limits = NamespaceInfo'Limits
  { namespaceInfoLimitsBlobsizelimiterror = 0
  , namespaceInfoLimitsMemosizelimiterror = 0
  }

instance MessageEncode NamespaceInfo'Limits where
  buildMessage msg =
    (if msg.namespaceInfoLimitsBlobsizelimiterror == 0 then mempty else encodeFieldVarint 1 (fromIntegral msg.namespaceInfoLimitsBlobsizelimiterror))
    <> (if msg.namespaceInfoLimitsMemosizelimiterror == 0 then mempty else encodeFieldVarint 2 (fromIntegral msg.namespaceInfoLimitsMemosizelimiterror))

instance MessageSize NamespaceInfo'Limits where
  messageSize msg =
    (if msg.namespaceInfoLimitsBlobsizelimiterror == 0 then 0 else fieldVarintSize 1 (fromIntegral msg.namespaceInfoLimitsBlobsizelimiterror))
    + (if msg.namespaceInfoLimitsMemosizelimiterror == 0 then 0 else fieldVarintSize 2 (fromIntegral msg.namespaceInfoLimitsMemosizelimiterror))

instance MessageDecode NamespaceInfo'Limits where
  messageDecoder = loop 0 0
    where
      loop acc_0 acc_1 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (NamespaceInfo'Limits {namespaceInfoLimitsBlobsizelimiterror = acc_0, namespaceInfoLimitsMemosizelimiterror = acc_1})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop v acc_1
            2 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop acc_0 v
            _ -> skipField wt >> loop acc_0 acc_1

instance ProtoToJSON NamespaceInfo'Limits where
  protoToJSON msg = jsonObject
      [ "blobSizeLimitError" .= msg.namespaceInfoLimitsBlobsizelimiterror
      , "memoSizeLimitError" .= msg.namespaceInfoLimitsMemosizelimiterror
      ]

instance ProtoFromJSON NamespaceInfo'Limits where
  protoFromJSON (JsonObject obj) = do
    fld_namespaceInfoLimitsBlobsizelimiterror <- obj .:? "blobSizeLimitError"
    fld_namespaceInfoLimitsMemosizelimiterror <- obj .:? "memoSizeLimitError"
    pure defaultNamespaceInfo'Limits
      { namespaceInfoLimitsBlobsizelimiterror = maybe (namespaceInfoLimitsBlobsizelimiterror defaultNamespaceInfo'Limits) id fld_namespaceInfoLimitsBlobsizelimiterror
      , namespaceInfoLimitsMemosizelimiterror = maybe (namespaceInfoLimitsMemosizelimiterror defaultNamespaceInfo'Limits) id fld_namespaceInfoLimitsMemosizelimiterror
      }
  protoFromJSON _ = Right defaultNamespaceInfo'Limits

defaultNamespaceInfo :: NamespaceInfo
defaultNamespaceInfo = NamespaceInfo
  { namespaceInfoName = ""
  , namespaceInfoState = (toEnum 0)
  , namespaceInfoDescription = ""
  , namespaceInfoOwneremail = ""
  , namespaceInfoData = Map.empty
  , namespaceInfoId = ""
  , namespaceInfoCapabilities = Nothing
  , namespaceInfoLimits = Nothing
  , namespaceInfoSupportsschedules = False
  }

instance MessageEncode NamespaceInfo where
  buildMessage msg =
    (if msg.namespaceInfoName == T.empty then mempty else encodeFieldString 1 msg.namespaceInfoName)
    <> (if fromEnum msg.namespaceInfoState == 0 then mempty else encodeFieldVarint 2 (fromIntegral (fromEnum msg.namespaceInfoState)))
    <> (if msg.namespaceInfoDescription == T.empty then mempty else encodeFieldString 3 msg.namespaceInfoDescription)
    <> (if msg.namespaceInfoOwneremail == T.empty then mempty else encodeFieldString 4 msg.namespaceInfoOwneremail)
    <> Map.foldlWithKey' (\acc k v -> acc <> encodeMapField 5 (encodeFieldString 1 k) (encodeFieldString 2 v)) mempty msg.namespaceInfoData
    <> (if msg.namespaceInfoId == T.empty then mempty else encodeFieldString 6 msg.namespaceInfoId)
    <> (maybe mempty (\v -> encodeFieldMessage 7 v) msg.namespaceInfoCapabilities)
    <> (maybe mempty (\v -> encodeFieldMessage 8 v) msg.namespaceInfoLimits)
    <> (if msg.namespaceInfoSupportsschedules == False then mempty else encodeFieldBool 100 msg.namespaceInfoSupportsschedules)

instance MessageSize NamespaceInfo where
  messageSize msg =
    (if msg.namespaceInfoName == T.empty then 0 else fieldTextSize 1 msg.namespaceInfoName)
    + (if fromEnum msg.namespaceInfoState == 0 then 0 else fieldVarintSize 2 (fromIntegral (fromEnum msg.namespaceInfoState)))
    + (if msg.namespaceInfoDescription == T.empty then 0 else fieldTextSize 3 msg.namespaceInfoDescription)
    + (if msg.namespaceInfoOwneremail == T.empty then 0 else fieldTextSize 4 msg.namespaceInfoOwneremail)
    + (Map.foldlWithKey' (\acc k v -> let entrySz = fieldTextSize 1 k + fieldTextSize 2 v in acc + tagSize 5 + varintSize (fromIntegral entrySz) + entrySz) 0 msg.namespaceInfoData)
    + (if msg.namespaceInfoId == T.empty then 0 else fieldTextSize 6 msg.namespaceInfoId)
    + (maybe 0 (\v -> fieldMessageSize 7 (messageSize v)) msg.namespaceInfoCapabilities)
    + (maybe 0 (\v -> fieldMessageSize 8 (messageSize v)) msg.namespaceInfoLimits)
    + (if msg.namespaceInfoSupportsschedules == False then 0 else fieldBoolSize 100)

instance MessageDecode NamespaceInfo where
  messageDecoder = loop "" (toEnum 0) "" "" Map.empty "" Nothing Nothing False
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (NamespaceInfo {namespaceInfoName = acc_0, namespaceInfoState = acc_1, namespaceInfoDescription = acc_2, namespaceInfoOwneremail = acc_3, namespaceInfoData = acc_4, namespaceInfoId = acc_5, namespaceInfoCapabilities = acc_6, namespaceInfoLimits = acc_7, namespaceInfoSupportsschedules = acc_8})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8
            2 -> do
              v <- decodeFieldEnum
              loop acc_0 v acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8
            3 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 v acc_3 acc_4 acc_5 acc_6 acc_7 acc_8
            4 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 v acc_4 acc_5 acc_6 acc_7 acc_8
            5 -> do
              bs' <- getLengthDelimited
              let decodeEntry = runDecoder (decodeMapEntry decodeFieldString decodeFieldString "" "") bs'
              case decodeEntry of
                Left _ -> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8
                Right (mk', mv') -> loop acc_0 acc_1 acc_2 acc_3 (Map.union acc_4 (Map.singleton mk' mv')) acc_5 acc_6 acc_7 acc_8
            6 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 acc_3 acc_4 v acc_6 acc_7 acc_8
            7 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 (Just v) acc_7 acc_8
            8 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 (Just v) acc_8
            100 -> do
              v <- decodeFieldBool
              loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_7 acc_8

instance ProtoToJSON NamespaceInfo where
  protoToJSON msg = jsonObject
      [ "name" .= msg.namespaceInfoName
      , "state" .= msg.namespaceInfoState
      , "description" .= msg.namespaceInfoDescription
      , "ownerEmail" .= msg.namespaceInfoOwneremail
      , "data" .= msg.namespaceInfoData
      , "id" .= msg.namespaceInfoId
      , "capabilities" .= msg.namespaceInfoCapabilities
      , "limits" .= msg.namespaceInfoLimits
      , "supportsSchedules" .= msg.namespaceInfoSupportsschedules
      ]

instance ProtoFromJSON NamespaceInfo where
  protoFromJSON (JsonObject obj) = do
    fld_namespaceInfoName <- obj .:? "name"
    fld_namespaceInfoState <- obj .:? "state"
    fld_namespaceInfoDescription <- obj .:? "description"
    fld_namespaceInfoOwneremail <- obj .:? "ownerEmail"
    fld_namespaceInfoData <- obj .:? "data"
    fld_namespaceInfoId <- obj .:? "id"
    fld_namespaceInfoCapabilities <- obj .:? "capabilities"
    fld_namespaceInfoLimits <- obj .:? "limits"
    fld_namespaceInfoSupportsschedules <- obj .:? "supportsSchedules"
    pure defaultNamespaceInfo
      { namespaceInfoName = maybe (namespaceInfoName defaultNamespaceInfo) id fld_namespaceInfoName
      , namespaceInfoState = maybe (namespaceInfoState defaultNamespaceInfo) id fld_namespaceInfoState
      , namespaceInfoDescription = maybe (namespaceInfoDescription defaultNamespaceInfo) id fld_namespaceInfoDescription
      , namespaceInfoOwneremail = maybe (namespaceInfoOwneremail defaultNamespaceInfo) id fld_namespaceInfoOwneremail
      , namespaceInfoData = maybe (namespaceInfoData defaultNamespaceInfo) id fld_namespaceInfoData
      , namespaceInfoId = maybe (namespaceInfoId defaultNamespaceInfo) id fld_namespaceInfoId
      , namespaceInfoCapabilities = maybe (namespaceInfoCapabilities defaultNamespaceInfo) id fld_namespaceInfoCapabilities
      , namespaceInfoLimits = maybe (namespaceInfoLimits defaultNamespaceInfo) id fld_namespaceInfoLimits
      , namespaceInfoSupportsschedules = maybe (namespaceInfoSupportsschedules defaultNamespaceInfo) id fld_namespaceInfoSupportsschedules
      }
  protoFromJSON _ = Right defaultNamespaceInfo

data NamespaceConfig = NamespaceConfig
  { namespaceConfigWorkflowexecutionretentionttl :: !(Maybe Duration)
  , namespaceConfigBadbinaries :: !(Maybe BadBinaries)
  , namespaceConfigHistoryarchivalstate :: !ArchivalState
  , namespaceConfigHistoryarchivaluri :: !Text
  , namespaceConfigVisibilityarchivalstate :: !ArchivalState
  , namespaceConfigVisibilityarchivaluri :: !Text
  , namespaceConfigCustomsearchattributealiases :: !(Map.Map Text Text)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultNamespaceConfig :: NamespaceConfig
defaultNamespaceConfig = NamespaceConfig
  { namespaceConfigWorkflowexecutionretentionttl = Nothing
  , namespaceConfigBadbinaries = Nothing
  , namespaceConfigHistoryarchivalstate = (toEnum 0)
  , namespaceConfigHistoryarchivaluri = ""
  , namespaceConfigVisibilityarchivalstate = (toEnum 0)
  , namespaceConfigVisibilityarchivaluri = ""
  , namespaceConfigCustomsearchattributealiases = Map.empty
  }

instance MessageEncode NamespaceConfig where
  buildMessage msg =
    (maybe mempty (\v -> encodeFieldMessage 1 v) msg.namespaceConfigWorkflowexecutionretentionttl)
    <> (maybe mempty (\v -> encodeFieldMessage 2 v) msg.namespaceConfigBadbinaries)
    <> (if fromEnum msg.namespaceConfigHistoryarchivalstate == 0 then mempty else encodeFieldVarint 3 (fromIntegral (fromEnum msg.namespaceConfigHistoryarchivalstate)))
    <> (if msg.namespaceConfigHistoryarchivaluri == T.empty then mempty else encodeFieldString 4 msg.namespaceConfigHistoryarchivaluri)
    <> (if fromEnum msg.namespaceConfigVisibilityarchivalstate == 0 then mempty else encodeFieldVarint 5 (fromIntegral (fromEnum msg.namespaceConfigVisibilityarchivalstate)))
    <> (if msg.namespaceConfigVisibilityarchivaluri == T.empty then mempty else encodeFieldString 6 msg.namespaceConfigVisibilityarchivaluri)
    <> Map.foldlWithKey' (\acc k v -> acc <> encodeMapField 7 (encodeFieldString 1 k) (encodeFieldString 2 v)) mempty msg.namespaceConfigCustomsearchattributealiases

instance MessageSize NamespaceConfig where
  messageSize msg =
    (maybe 0 (\v -> fieldMessageSize 1 (messageSize v)) msg.namespaceConfigWorkflowexecutionretentionttl)
    + (maybe 0 (\v -> fieldMessageSize 2 (messageSize v)) msg.namespaceConfigBadbinaries)
    + (if fromEnum msg.namespaceConfigHistoryarchivalstate == 0 then 0 else fieldVarintSize 3 (fromIntegral (fromEnum msg.namespaceConfigHistoryarchivalstate)))
    + (if msg.namespaceConfigHistoryarchivaluri == T.empty then 0 else fieldTextSize 4 msg.namespaceConfigHistoryarchivaluri)
    + (if fromEnum msg.namespaceConfigVisibilityarchivalstate == 0 then 0 else fieldVarintSize 5 (fromIntegral (fromEnum msg.namespaceConfigVisibilityarchivalstate)))
    + (if msg.namespaceConfigVisibilityarchivaluri == T.empty then 0 else fieldTextSize 6 msg.namespaceConfigVisibilityarchivaluri)
    + (Map.foldlWithKey' (\acc k v -> let entrySz = fieldTextSize 1 k + fieldTextSize 2 v in acc + tagSize 7 + varintSize (fromIntegral entrySz) + entrySz) 0 msg.namespaceConfigCustomsearchattributealiases)

instance MessageDecode NamespaceConfig where
  messageDecoder = loop Nothing Nothing (toEnum 0) "" (toEnum 0) "" Map.empty
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (NamespaceConfig {namespaceConfigWorkflowexecutionretentionttl = acc_0, namespaceConfigBadbinaries = acc_1, namespaceConfigHistoryarchivalstate = acc_2, namespaceConfigHistoryarchivaluri = acc_3, namespaceConfigVisibilityarchivalstate = acc_4, namespaceConfigVisibilityarchivaluri = acc_5, namespaceConfigCustomsearchattributealiases = acc_6})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldMessage
              loop (Just v) acc_1 acc_2 acc_3 acc_4 acc_5 acc_6
            2 -> do
              v <- decodeFieldMessage
              loop acc_0 (Just v) acc_2 acc_3 acc_4 acc_5 acc_6
            3 -> do
              v <- decodeFieldEnum
              loop acc_0 acc_1 v acc_3 acc_4 acc_5 acc_6
            4 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 v acc_4 acc_5 acc_6
            5 -> do
              v <- decodeFieldEnum
              loop acc_0 acc_1 acc_2 acc_3 v acc_5 acc_6
            6 -> do
              v <- decodeFieldString
              loop acc_0 acc_1 acc_2 acc_3 acc_4 v acc_6
            7 -> do
              bs' <- getLengthDelimited
              let decodeEntry = runDecoder (decodeMapEntry decodeFieldString decodeFieldString "" "") bs'
              case decodeEntry of
                Left _ -> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6
                Right (mk', mv') -> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 (Map.union acc_6 (Map.singleton mk' mv'))
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6

instance ProtoToJSON NamespaceConfig where
  protoToJSON msg = jsonObject
      [ "workflowExecutionRetentionTtl" .= msg.namespaceConfigWorkflowexecutionretentionttl
      , "badBinaries" .= msg.namespaceConfigBadbinaries
      , "historyArchivalState" .= msg.namespaceConfigHistoryarchivalstate
      , "historyArchivalUri" .= msg.namespaceConfigHistoryarchivaluri
      , "visibilityArchivalState" .= msg.namespaceConfigVisibilityarchivalstate
      , "visibilityArchivalUri" .= msg.namespaceConfigVisibilityarchivaluri
      , "customSearchAttributeAliases" .= msg.namespaceConfigCustomsearchattributealiases
      ]

instance ProtoFromJSON NamespaceConfig where
  protoFromJSON (JsonObject obj) = do
    fld_namespaceConfigWorkflowexecutionretentionttl <- obj .:? "workflowExecutionRetentionTtl"
    fld_namespaceConfigBadbinaries <- obj .:? "badBinaries"
    fld_namespaceConfigHistoryarchivalstate <- obj .:? "historyArchivalState"
    fld_namespaceConfigHistoryarchivaluri <- obj .:? "historyArchivalUri"
    fld_namespaceConfigVisibilityarchivalstate <- obj .:? "visibilityArchivalState"
    fld_namespaceConfigVisibilityarchivaluri <- obj .:? "visibilityArchivalUri"
    fld_namespaceConfigCustomsearchattributealiases <- obj .:? "customSearchAttributeAliases"
    pure defaultNamespaceConfig
      { namespaceConfigWorkflowexecutionretentionttl = maybe (namespaceConfigWorkflowexecutionretentionttl defaultNamespaceConfig) id fld_namespaceConfigWorkflowexecutionretentionttl
      , namespaceConfigBadbinaries = maybe (namespaceConfigBadbinaries defaultNamespaceConfig) id fld_namespaceConfigBadbinaries
      , namespaceConfigHistoryarchivalstate = maybe (namespaceConfigHistoryarchivalstate defaultNamespaceConfig) id fld_namespaceConfigHistoryarchivalstate
      , namespaceConfigHistoryarchivaluri = maybe (namespaceConfigHistoryarchivaluri defaultNamespaceConfig) id fld_namespaceConfigHistoryarchivaluri
      , namespaceConfigVisibilityarchivalstate = maybe (namespaceConfigVisibilityarchivalstate defaultNamespaceConfig) id fld_namespaceConfigVisibilityarchivalstate
      , namespaceConfigVisibilityarchivaluri = maybe (namespaceConfigVisibilityarchivaluri defaultNamespaceConfig) id fld_namespaceConfigVisibilityarchivaluri
      , namespaceConfigCustomsearchattributealiases = maybe (namespaceConfigCustomsearchattributealiases defaultNamespaceConfig) id fld_namespaceConfigCustomsearchattributealiases
      }
  protoFromJSON _ = Right defaultNamespaceConfig

data BadBinaries = BadBinaries
  { badBinariesBinaries :: !(Map.Map Text BadBinaryInfo)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBadBinaries :: BadBinaries
defaultBadBinaries = BadBinaries
  { badBinariesBinaries = Map.empty
  }

instance MessageEncode BadBinaries where
  buildMessage msg =
    Map.foldlWithKey' (\acc k v -> acc <> encodeMapField 1 (encodeFieldString 1 k) (encodeFieldMessage 2 v)) mempty msg.badBinariesBinaries

instance MessageSize BadBinaries where
  messageSize msg =
    (Map.foldlWithKey' (\acc k v -> let entrySz = fieldTextSize 1 k + fieldMessageSize 2 (messageSize v) in acc + tagSize 1 + varintSize (fromIntegral entrySz) + entrySz) 0 msg.badBinariesBinaries)

instance MessageDecode BadBinaries where
  messageDecoder = loop Map.empty
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BadBinaries {badBinariesBinaries = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              bs' <- getLengthDelimited
              let decodeEntry = runDecoder (decodeMapEntry decodeFieldString decodeFieldMessage "" undefined) bs'
              case decodeEntry of
                Left _ -> loop acc_0
                Right (mk', mv') -> loop (Map.union acc_0 (Map.singleton mk' mv'))
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON BadBinaries where
  protoToJSON msg = jsonObject
      [ "binaries" .= msg.badBinariesBinaries

      ]

instance ProtoFromJSON BadBinaries where
  protoFromJSON (JsonObject obj) = do
    fld_badBinariesBinaries <- obj .:? "binaries"
    pure defaultBadBinaries
      { badBinariesBinaries = maybe (badBinariesBinaries defaultBadBinaries) id fld_badBinariesBinaries
      }
  protoFromJSON _ = Right defaultBadBinaries

data BadBinaryInfo = BadBinaryInfo
  { badBinaryInfoReason :: !Text
  , badBinaryInfoOperator :: !Text
  , badBinaryInfoCreatetime :: !(Maybe Timestamp)
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBadBinaryInfo :: BadBinaryInfo
defaultBadBinaryInfo = BadBinaryInfo
  { badBinaryInfoReason = ""
  , badBinaryInfoOperator = ""
  , badBinaryInfoCreatetime = Nothing
  }

instance MessageEncode BadBinaryInfo where
  buildMessage msg =
    (if msg.badBinaryInfoReason == T.empty then mempty else encodeFieldString 1 msg.badBinaryInfoReason)
    <> (if msg.badBinaryInfoOperator == T.empty then mempty else encodeFieldString 2 msg.badBinaryInfoOperator)
    <> (maybe mempty (\v -> encodeFieldMessage 3 v) msg.badBinaryInfoCreatetime)

instance MessageSize BadBinaryInfo where
  messageSize msg =
    (if msg.badBinaryInfoReason == T.empty then 0 else fieldTextSize 1 msg.badBinaryInfoReason)
    + (if msg.badBinaryInfoOperator == T.empty then 0 else fieldTextSize 2 msg.badBinaryInfoOperator)
    + (maybe 0 (\v -> fieldMessageSize 3 (messageSize v)) msg.badBinaryInfoCreatetime)

instance MessageDecode BadBinaryInfo where
  messageDecoder = loop "" "" Nothing
    where
      loop acc_0 acc_1 acc_2 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (BadBinaryInfo {badBinaryInfoReason = acc_0, badBinaryInfoOperator = acc_1, badBinaryInfoCreatetime = acc_2})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2
            2 -> do
              v <- decodeFieldString
              loop acc_0 v acc_2
            3 -> do
              v <- decodeFieldMessage
              loop acc_0 acc_1 (Just v)
            _ -> skipField wt >> loop acc_0 acc_1 acc_2

instance ProtoToJSON BadBinaryInfo where
  protoToJSON msg = jsonObject
      [ "reason" .= msg.badBinaryInfoReason
      , "operator" .= msg.badBinaryInfoOperator
      , "createTime" .= msg.badBinaryInfoCreatetime
      ]

instance ProtoFromJSON BadBinaryInfo where
  protoFromJSON (JsonObject obj) = do
    fld_badBinaryInfoReason <- obj .:? "reason"
    fld_badBinaryInfoOperator <- obj .:? "operator"
    fld_badBinaryInfoCreatetime <- obj .:? "createTime"
    pure defaultBadBinaryInfo
      { badBinaryInfoReason = maybe (badBinaryInfoReason defaultBadBinaryInfo) id fld_badBinaryInfoReason
      , badBinaryInfoOperator = maybe (badBinaryInfoOperator defaultBadBinaryInfo) id fld_badBinaryInfoOperator
      , badBinaryInfoCreatetime = maybe (badBinaryInfoCreatetime defaultBadBinaryInfo) id fld_badBinaryInfoCreatetime
      }
  protoFromJSON _ = Right defaultBadBinaryInfo

data UpdateNamespaceInfo = UpdateNamespaceInfo
  { updateNamespaceInfoDescription :: !Text
  , updateNamespaceInfoOwneremail :: !Text
  , updateNamespaceInfoData :: !(Map.Map Text Text)
  , updateNamespaceInfoState :: !NamespaceState
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultUpdateNamespaceInfo :: UpdateNamespaceInfo
defaultUpdateNamespaceInfo = UpdateNamespaceInfo
  { updateNamespaceInfoDescription = ""
  , updateNamespaceInfoOwneremail = ""
  , updateNamespaceInfoData = Map.empty
  , updateNamespaceInfoState = (toEnum 0)
  }

instance MessageEncode UpdateNamespaceInfo where
  buildMessage msg =
    (if msg.updateNamespaceInfoDescription == T.empty then mempty else encodeFieldString 1 msg.updateNamespaceInfoDescription)
    <> (if msg.updateNamespaceInfoOwneremail == T.empty then mempty else encodeFieldString 2 msg.updateNamespaceInfoOwneremail)
    <> Map.foldlWithKey' (\acc k v -> acc <> encodeMapField 3 (encodeFieldString 1 k) (encodeFieldString 2 v)) mempty msg.updateNamespaceInfoData
    <> (if fromEnum msg.updateNamespaceInfoState == 0 then mempty else encodeFieldVarint 4 (fromIntegral (fromEnum msg.updateNamespaceInfoState)))

instance MessageSize UpdateNamespaceInfo where
  messageSize msg =
    (if msg.updateNamespaceInfoDescription == T.empty then 0 else fieldTextSize 1 msg.updateNamespaceInfoDescription)
    + (if msg.updateNamespaceInfoOwneremail == T.empty then 0 else fieldTextSize 2 msg.updateNamespaceInfoOwneremail)
    + (Map.foldlWithKey' (\acc k v -> let entrySz = fieldTextSize 1 k + fieldTextSize 2 v in acc + tagSize 3 + varintSize (fromIntegral entrySz) + entrySz) 0 msg.updateNamespaceInfoData)
    + (if fromEnum msg.updateNamespaceInfoState == 0 then 0 else fieldVarintSize 4 (fromIntegral (fromEnum msg.updateNamespaceInfoState)))

instance MessageDecode UpdateNamespaceInfo where
  messageDecoder = loop "" "" Map.empty (toEnum 0)
    where
      loop acc_0 acc_1 acc_2 acc_3 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (UpdateNamespaceInfo {updateNamespaceInfoDescription = acc_0, updateNamespaceInfoOwneremail = acc_1, updateNamespaceInfoData = acc_2, updateNamespaceInfoState = acc_3})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop v acc_1 acc_2 acc_3
            2 -> do
              v <- decodeFieldString
              loop acc_0 v acc_2 acc_3
            3 -> do
              bs' <- getLengthDelimited
              let decodeEntry = runDecoder (decodeMapEntry decodeFieldString decodeFieldString "" "") bs'
              case decodeEntry of
                Left _ -> loop acc_0 acc_1 acc_2 acc_3
                Right (mk', mv') -> loop acc_0 acc_1 (Map.union acc_2 (Map.singleton mk' mv')) acc_3
            4 -> do
              v <- decodeFieldEnum
              loop acc_0 acc_1 acc_2 v
            _ -> skipField wt >> loop acc_0 acc_1 acc_2 acc_3

instance ProtoToJSON UpdateNamespaceInfo where
  protoToJSON msg = jsonObject
      [ "description" .= msg.updateNamespaceInfoDescription
      , "ownerEmail" .= msg.updateNamespaceInfoOwneremail
      , "data" .= msg.updateNamespaceInfoData
      , "state" .= msg.updateNamespaceInfoState
      ]

instance ProtoFromJSON UpdateNamespaceInfo where
  protoFromJSON (JsonObject obj) = do
    fld_updateNamespaceInfoDescription <- obj .:? "description"
    fld_updateNamespaceInfoOwneremail <- obj .:? "ownerEmail"
    fld_updateNamespaceInfoData <- obj .:? "data"
    fld_updateNamespaceInfoState <- obj .:? "state"
    pure defaultUpdateNamespaceInfo
      { updateNamespaceInfoDescription = maybe (updateNamespaceInfoDescription defaultUpdateNamespaceInfo) id fld_updateNamespaceInfoDescription
      , updateNamespaceInfoOwneremail = maybe (updateNamespaceInfoOwneremail defaultUpdateNamespaceInfo) id fld_updateNamespaceInfoOwneremail
      , updateNamespaceInfoData = maybe (updateNamespaceInfoData defaultUpdateNamespaceInfo) id fld_updateNamespaceInfoData
      , updateNamespaceInfoState = maybe (updateNamespaceInfoState defaultUpdateNamespaceInfo) id fld_updateNamespaceInfoState
      }
  protoFromJSON _ = Right defaultUpdateNamespaceInfo

data NamespaceFilter = NamespaceFilter
  { namespaceFilterIncludedeleted :: {-# UNPACK #-} !Bool
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultNamespaceFilter :: NamespaceFilter
defaultNamespaceFilter = NamespaceFilter
  { namespaceFilterIncludedeleted = False
  }

instance MessageEncode NamespaceFilter where
  buildMessage msg =
    (if msg.namespaceFilterIncludedeleted == False then mempty else encodeFieldBool 1 msg.namespaceFilterIncludedeleted)

instance MessageSize NamespaceFilter where
  messageSize msg =
    (if msg.namespaceFilterIncludedeleted == False then 0 else fieldBoolSize 1)

instance MessageDecode NamespaceFilter where
  messageDecoder = loop False
    where
      loop acc_0 = do
        mTag <- getTagOr
        case mTag of
          Nothing -> pure (NamespaceFilter {namespaceFilterIncludedeleted = acc_0})
          Just (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldBool
              loop v
            _ -> skipField wt >> loop acc_0

instance ProtoToJSON NamespaceFilter where
  protoToJSON msg = jsonObject
      [ "includeDeleted" .= msg.namespaceFilterIncludedeleted

      ]

instance ProtoFromJSON NamespaceFilter where
  protoFromJSON (JsonObject obj) = do
    fld_namespaceFilterIncludedeleted <- obj .:? "includeDeleted"
    pure defaultNamespaceFilter
      { namespaceFilterIncludedeleted = maybe (namespaceFilterIncludedeleted defaultNamespaceFilter) id fld_namespaceFilterIncludedeleted
      }
  protoFromJSON _ = Right defaultNamespaceFilter